### ISSUE TITLE
Flask-Restful doesn't support posting a list of entities to the service

### ISSUE THREAD

**Issue by houmie** [flask-restful/flask-restful#138]
http://stackoverflow.com/questions/19384526/how-to-parse-the-post-argument-to-a-rest-service

Please advice if I am doing something wrong, or if that is a bug?

Thanks

**Comment by OmkarNeogi** [comment]
Hi, I have a similar question - I want to receive a list as a parameter with a GET request. 
I have asked the question on stack-overflow: [https://stackoverflow.com/questions/48095713/accepting-multiple-parameters-in-flask-restful-add-resource?noredirect=1#comment83166151_48095713](url).

Basically, I want to accept two arguments, one is a Boolean variable, and another is a list which will come over a GET request. I have a Flask-RESTful Resource whose get() these should be passed to, but I am not able to figure out I can do this. 

How do you accept them in the add_resource() function and how do you unpack them inside the get() function? My sincere thanks!
