### ISSUE TITLE
Support validation of nested arguments

### ISSUE THREAD

**Issue by matomesc** [flask-restful/flask-restful#149]
Suppose the body of a request is:

``` json
{
  "a": {
    "b": {
      "c": "stuff"
    }
  }
}
```

There is no way to validate the body using the current request parser.

I've currently subclassed the `RequestParser` class to add this functionality. See the current implementation at https://gist.github.com/matomesc/7443750.

Using `NestedRequestParser` you'd declare the argument above as follows:

``` python
parser = NestedRequestParser()
parser.add_argument('a.b.c', type=str)
```

We could also add support for validating arrays. Given the following request body:

``` json
{
  "a": {
    "b": [{"c": 10}, {"c": 20}]
  }
}
```

You can declare the array arguments with:

``` python
parser = NestedRequestParser()
parser.add_argument('a.b.$.c', type=int)
```

What do you guys think?

**Comment by novalic** [comment]
Just in case....

That page is down, you can see the original post here:

https://web.archive.org/web/20170911150336/http://wiredmonk.me/customizing-flask-restful.html
