### ISSUE TITLE
JSON Parsing on empty request content with RequestParser

### ISSUE THREAD

**Issue by lastmikoi** [flask-restful/flask-restful#163]
```
class ClientListResource(Resource):

    @staticmethod
    def get():
        parser = reqparse.RequestParser()
        parser.add_argument('name', type=str, default=None, help='Firstname or Lastname to search')
        args = parser.parse_args()
        return ClientList(args.name)
```

Using this 'simple' resource (which maps a non-ORM-based python object `Client`), I ended up having an issue when using, on the client end, [slumber](https://github.com/dstufft/slumber) or [drest](https://github.com/datafolklabs/drest/).

Indeed, both of theses RESTful clients are adding a `Content-Type: application/json` header to theirs GET requests, but obviously without providing any extra data.

This strange (but still compliant with [RFC2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1)) behavior ends up with triggering a `BadRequest` exception, because of the final `json.loads` being given an empty string (with will raise a `ValueError` exception)

Here is the stacktrace I managed to retrieve with [pdb](http://docs.python.org/3.3/library/pdb.html):

```
  (...)lib/python3.3/site-packages/flask/app.py(1817)wsgi_app()
-> response = self.full_dispatch_request()
  (...)lib/python3.3/site-packages/flask/app.py(1475)full_dispatch_request()
-> rv = self.dispatch_request()
  (...)lib/python3.3/site-packages/flask/app.py(1461)dispatch_request()
-> return self.view_functions[rule.endpoint](**req.view_args)
  (...)lib/python3.3/site-packages/flask_restful/__init__.py(384)wrapper()
-> resp = resource(*args, **kwargs)
  (...)lib/python3.3/site-packages/flask/views.py(84)view()
-> return self.dispatch_request(*args, **kwargs)
  (...)lib/python3.3/site-packages/flask_restful/__init__.py(473)dispatch_request()
-> resp = meth(*args, **kwargs)
  /home/mfalck/Work/gunter-server/app/clients.py(67)get()
-> args = parser.parse_args()
  (...)lib/python3.3/site-packages/flask_restful/reqparse.py(209)parse_args()
-> namespace[arg.dest or arg.name] = arg.parse(req)
  (...)lib/python3.3/site-packages/flask_restful/reqparse.py(117)parse()
-> source = self.source(request)
  (...)lib/python3.3/site-packages/flask_restful/reqparse.py(81)source()
-> value = getattr(request, l, None)
  (...)lib/python3.3/site-packages/werkzeug/local.py(338)__getattr__()
-> return getattr(self._get_current_object(), name)
  (...)lib/python3.3/site-packages/flask/wrappers.py(108)json()
-> return self.get_json()
  (...)lib/python3.3/site-packages/flask/wrappers.py(145)get_json()
-> rv = self.on_json_loading_failed(e)
> (...)lib/python3.3/site-packages/flask/wrappers.py(162)on_json_loading_failed()
-> raise BadRequest()
```

I managed to workaround this problem by adding `location='args'` to my `add_argument` call, but I think it would be interesting to fix this issue, since 
all other RESTful API I tested against these clients seems to be perfectly fine (github, django-tastypie based ones, etc).

**Comment by thanhtungka91** [comment]
@dougblack any solution from flask?
