### ISSUE TITLE
Custom error handling

### ISSUE THREAD

**Issue by computmaxer** [flask-restful/flask-restful#221]
After using flask-restful on a number of projects, I have found that I often need an easy way to handle exceptions raised in the project's internal/logic code. The goal is to get the REST API to return more meaningful status codes and messages (e.g. not 500 Internal Server Error) without putting a bunch of try/except blocks in my REST module.

My first iteration of solving this problem involved extending the `Api` class and overriding the `handle_error(self, e)` function. You could then put a big if/elif to match custom exceptions and return messages like so:

``` py
class ExceptionAwareApi(Api):
    def handle_error(self, e):
        if isinstance(e, UserAlreadyExistsException):
            code = 400
            data = {'status_code': code, 'message': "User already exists."}
        elif isinstance(e, ServerAlreadyExistsException):
            code = 400
            data = {'status_code': code, 'message': "Server already exists."}
        elif isinstance(e, OAuthKeyMismatchException):
            code = 401
            data = {'status_code': code, 'message': "Invalid OAuth key."}
        else:
            # Did not match a custom exception, continue normally
            return super(ExceptionAwareApi, self).handle_error(e)
        return self.make_response(data, code)
```

This works fine, but gets looking kind of messy. Also extending `Api` in order to do this is somewhat of an annoyance.

Instead, what if `Api` was able to take a dictionary of errors mapped to custom messages and status codes?
I imagine it would look something like this:

``` py
errors = {
    UserAlreadyExistsError: ("User already exists.", 400),
    ServerAlreadyExistsError: ("Server already exists.", 400),
    OAuthKeyMismatchException: ("Invalid OAuth key.", 401),
}

api = Api(app, errors=errors)
```

Then inside `Api`'s `handle_error` would be something like this, right before line 307:

``` py
if type(e) in self.errors:
    message, code = errors.get(type(e))
    data = {'status_code': code, 'message': message}

# -- existing code --
resp = self.make_response(data, code)
```

If anyone likes this idea I would like to actually code it up and submit a PR. Just wanted to get the idea validated before I spent any time on it.

Let me know what you think!

**Comment by ainsophical** [comment]
is there any way to add logging to this as is, when handling an exception? i know it might be an edge case but I have an app with predetermined routes to my api that are not even available to the user so i would like to log 404s from my logger as an indicator that someone is poking around my api that shouldn't. trying to get away from customizing the api class if i don't have to.
