### ISSUE TITLE
Argument parser should validate all arguments

### ISSUE THREAD

**Issue by svenstaro** [flask-restful/flask-restful#258]
Currently the argument parser only validates a single argument at a time. This is obviously not optimal. It should validate all arguments and provide errors for all of them at the same time. As such, it should provide a list of errors, one per failed field. Perhaps with an option to enable/disable multiple errors such as fail_fast=True or validate_all=True.

**Comment by joshfriend** [comment]
Is this still worth fixing due to #335?

**Comment by joshfriend** [comment]
Taken care of by #431
