### ISSUE TITLE
Can't return (unescaped JSON strings) instead of JSON serializable objects

### ISSUE THREAD

**Issue by s-celles** [flask-restful/flask-restful#269]
Hello,

I'm trying to build a RESTful api with Flask-RESTful which will return a Pandas DataFrame as JSON data.

```
from flask import Flask
from flask.ext import restful
from flask.ext.restful import Resource, Api
import pandas as pd
import click
import logging

app = Flask(__name__)
api = restful.Api(app)

class DataWebservice(Resource):
    def get(self, size):
        logging.info("get %d" % size)
        # get DB conn
        # df = pd.read_sql(...) # USE LIMIT
        df = pd.DataFrame({"col1": [1]*size, "col2": [2]*size})
        #return(df.to_json())
        return(df)

api.add_resource(DataWebservice, '/api/v1/solar/df/get/<int:size>')

@click.command()
@click.option('--host', default='127.0.0.1', \
    help="host (127.0.0.1 or 0.0.0.0 to accept all ip)")
@click.option('--debug/--no-debug', default=False, help="debug mode")
def main(debug, host):
    app.run(host=host, debug=debug)

if __name__ == '__main__':
    main()
```

I run server using
$ python server.py --debug

I run client using
$ curl http://127.0.0.1:5000/api/v1/solar/df/get/10

but I get the following error

```
TypeError:    col1  col2
0     1     2
1     1     2
...
8     1     2
9     1     2

[10 rows x 2 columns] is not JSON serializable
```

So it seems that Pandas DataFrame are not JSON serializable.
see https://github.com/pydata/pandas/issues/7689

I tried to output data using the to_json() method of DataFrame
but it doesn't help me much as my server returns escaped strings such as

```
"{\"col1\":{\"0\":1,\"1\":1,\"2\":1,\"3\":1,\"4\":1,\"5\":1,\"6\":1,\"7\":1,\"8\":1,\"9\":1},\"col2\":{\"0\":2,\"1\":2,\"2\":2,\"3\":2,\"4\":2,\"5\":2,\"6\":2,\"7\":2,\"8\":2,\"9\":2}}"
```

I didn't find in the manual how I could return unescaped JSON strings instead of JSON serializable objects.

Kind regards

**Comment by nfrik** [comment]
from flask import make_response
.....
response = make_response(json.dumps(result))
response.headers['content-type'] = 'application/json'
return response
