### ISSUE TITLE
Allow validation error messages to override help, or enable better handling of required arguments

### ISSUE THREAD

**Issue by rtoal** [flask-restful/flask-restful#275]
When using a custom validator such as

    def customer(customer_data):
        if type(customer_data) != dict:
            raise ValidationError('Customer must be an object')
        if 'id' not in customer_data:
            raise ValidationError('Customer must have an id')
        return customer_data

in conjunction with an `add_argument` call that specifies that the `customer` argument is required, e.g.,

    parser.add_argument('customer', type=customer, required=True, location='json', help='Customer is required')

I find that my validation errors are not respected; instead the help text in `add_argument` takes precedence.  I know this from the source code:

        :param help: A brief description of the argument, returned in the
            response when the argument is invalid. This takes precedence over
            the message passed to a ValidationError raised by a type converter.

The problem is that this is not at all what is expected.  I would like the help text to kick in only for required=True failures.  Is there another way to do what I like, or is this out of line?

**Comment by joshfriend** [comment]
I don't think this will be worth fixing due to #335.
