### ISSUE TITLE
RequestParser 'type' kwarg useless for file uploads

### ISSUE THREAD

**Issue by bbenne10** [flask-restful/flask-restful#279]
In `reqparse.py` (line 141),  FileStorage values in arguments are specifically gated from validation, but [here](http://flask-restful.readthedocs.org/en/latest/reqparse.html?highlight=other%20locations#other-locations) it implies that the validation against FileStorage type actually means something. This should either A) be disallowed at instantiation time so that a user doesn't spend 2 hours trying to figure out what's wrong or B) be modified to work. I'm working on a pull request to get B to work (since I need it here), and I'm curious if a pull request (of adequate quality and containing passing tests)  would be considered for this functionality. Are there any reasons this **SHOULDN'T** work? 

Use case:
``` python
def allowed_file(f):
    allowed = current_app.config.get("ALLOWED_TYPES", set())
     if isinstance(f, FileStorage): 
         f = f.read()
         file_type = magic.from_buffer(f, mime=True)
         f.seek(0)
         file_name = f.filename
     else:
         raise ValueError("'{}' is not a valid file!".format(f))

     if file_type in allowed:
            return {'file': f,
                      'type': file_type,
                     'name': secure_filename(file_name)}
         
        raise ValueError("'{}' is not allowed. Allowed types are: {}".format(
            file_type, ",".join(allowed)))

def post(self):
    parser = reqparse.RequestParser()
    parser.add_argument('file',
                        type=allowed_file,
                        required=True,
                        location='files')
    args = parser.parse_args()
```

**Comment by joshfriend** [comment]
I would try using [`webargs`](https://webargs.readthedocs.org/en/latest) instead. Due to #335, this might not be worth fixing (though I'll review a pull request if you make one).

**Comment by bbenne10** [comment]
I completely forgot about this. I'll see if I still have the changes. It's pretty simple to get it to work, if I remember correctly.

**Comment by bbenne10** [comment]
Pull request opened. WRT switching to webargs, you're likely right - but this isn't a new product so switching 100-200 routes to a new library is a non-trivial undertaking. Thanks for the recommendation though!
