### ISSUE TITLE
Why doesn't Flask-RESTful use custom error handlers

### ISSUE THREAD

**Issue by dmikhaylov** [flask-restful/flask-restful#280]
As you know, Flask provides the ability to create [custom errors and handlers for them](http://flask.pocoo.org/docs/patterns/apierrors/).

But as I can see, I can't use this feature in Flask-RESTful. Could anyone please explain why?
If you have working web app with it's own exceptions it would be easier to create RESTful API then.

[This](https://github.com/twilio/flask-restful/issues/221) thing with custom error messages doesn't seem to be that flexible. For example, if I validate data and then raise exception with message that describes what is wrong, I can't pass it to the errors dict. Correct me if I'm wrong, please.

**Comment by zykis** [comment]
oh gush

**Comment by zykis** [comment]
oh, gush.
can we just have something like 
abort(409, 'my custom error message')
without extra sublcassing?

**Comment by billmccord** [comment]
Workaround:
```
handle_exceptions = app.handle_exception
handle_user_exception = app.handle_user_exception
api = Api(app)
app.handle_user_exception = handle_exceptions
app.handle_user_exception = handle_user_exception
```

**Comment by cedmt** [comment]
@billmccord you might to fix your snippet but it did the job for me 👍 
`   handle_exception = app.handle_exception
    handle_user_exception = app.handle_user_exception
    api = Api(app)
    app.handle_exception = handle_exception
    app.handle_user_exception = handle_user_exception
    
   app.register_error_handler(404, custom_404_handler_here_we_go)
`

**Comment by Stark-X** [comment]
I've used the Blueprint to work with the flask-restful, and I've found that the solution @billmccord and @cedmt provided not worked for this case, because the Blueprint don't have the `handle_exception` and `handle_user_exception` functions. 

My workaround is that enhance the function `handle_error` of the `Api`, if the "error handler" of the "Exception" have been registered, just raise it, the "error handler" registered on app will deal with that Exception, or the Exception will be passed to the "flask-restful" controlled "custom error handler".
```python
class ImprovedApi(Api):
    def handle_error(self, e):
        for val in current_app.error_handler_spec.values():
            for handler in val.values():
                registered_error_handlers = list(filter(lambda x: isinstance(e, x), handler.keys()))
                if len(registered_error_handlers) > 0:
                    raise e
        return super().handle_error(e)


api_entry = ImprovedApi(api_entry_bp)
```

BTW, seems this repository had been deprecated...

**Comment by bcho** [comment]
For those coming from the internet, a quick way to "fix" this behavior is to set:

```
app.config['PROPAGATE_EXCEPTIONS'] = True
```

So the exceptions will be reraised and handled by flask.

ref: https://github.com/flask-restful/flask-restful/issues/578#issuecomment-373308124

**Comment by iteratelance** [comment]
Hello all, after using this library for several projects I've found it easier to just use flask's built in MethodView https://flask.palletsprojects.com/en/1.1.x/api/#flask.views.MethodView rather than monkey patching error handling.

```python
import flask
from flask.views import MethodView

blueprint = flask.Blueprint('api', __name__, url_prefix='/api')

class MyClass(MethodView):

    def get(self):
        return flask.make_response(flask.jsonify({}), 200)

    def post(self):
        return flask.make_response(flask.jsonify({}), 200)

blueprint.add_url_rule('/my-url', view_func=MyClass.as_view('my_url'))
```

More info here: https://pythonise.com/feed/flask/flask-api-methodview

**Comment by joshfriend** [comment]
@iteratelance this is what I moved to doing as well

**Comment by flazz** [comment]
I did something similar to @Stark-X, error_router seems to work with error_handler

```.py
class ErrorPropagatingApi(Api):
    """Flask-Restful has its own error handling facilities, this propagates errors to flask"""

    def error_router(self, original_handler, e):
        return original_handler(e)
```

**Comment by zobayer1** [comment]
> For those coming from the internet, a quick way to "fix" this behavior is to set:
> 
> ```
> app.config['PROPAGATE_EXCEPTIONS'] = True
> ```
> 
> So the exceptions will be reraised and handled by flask.
> 
> ref: [#578 (comment)](https://github.com/flask-restful/flask-restful/issues/578#issuecomment-373308124)

In addition to this, I ended up making sure that none of my application exceptions were using HTTPException class as a base. Now the errors could easily be handled by the error handlers registered with the Flask app or Blueprints.
