### ISSUE TITLE
Allow configuration to be set on `Flask.config

### ISSUE THREAD

**Issue by justanr** [flask-restful/flask-restful#292]
I went looking for how to modify the indent level for the native json representation. I was dismayed when I found [this](https://github.com/twilio/flask-restful/blob/master/flask_restful/representations/json.py).

I'm proposing that Flask-RESTful should take advantage of `Flask.config`. I currently have a working implementation for just `restful.representations.json` [here](https://github.com/justanr/flask-restful/blob/json_config/flask_restful/representations/json.py).

However, I'm unsure of what other config options would be useful, as well as defining a "standard" for them, e.g. naming conventions, acceptable values, etc.

Tests will be written if there's interest in this.

**Comment by justanr** [comment]
Sorry about that, I'm not sure why I deleted it. I've re-added this.

**Comment by joshfriend** [comment]
I think your PR #458 takes care of this, so I'm closing.
