### ISSUE TITLE
How do I marshal a list of objects?

### ISSUE THREAD

**Issue by nickretallack** [flask-restful/flask-restful#300]
There are no examples of how to return a list of complex objects in the documentation.  The [full example](http://flask-restful.readthedocs.org/en/latest/quickstart.html#full-example) would be a perfect opportunity to show how this works.

Here's what I came up with:

``` python
todo_fields = {
    "task": fields.String,
}

todo_list_fields = {
    "tasks": fields.List(fields.Nested(todo_fields))
}

class Todo(Resource):
    @marshal_with(todo_fields)
    def get(self, todo_id):
        abort_if_todo_doesnt_exist(todo_id)
        return TODOS[todo_id]

class TodoList(Resource):
    @marshal_with(todo_list_fields)
    def get(self):
        return TODOS
```

This gets {"tasks":[{"task":"?????"}]} but it can't get you the structure they show in the example, nor can it get you an unwrapped list like [{"task":"?????"}].  Are these possible?

**Comment by adaro** [comment]
@joshfriend thanks! I have another similar question I posted to SO: http://stackoverflow.com/questions/30655146/flask-restful-marshal-with-nested-data

Can you provide an example of marshaling a POST request with an array of nested objects? I am trying to use reqparse and can't seem to get it working correctly.

**Comment by zmarffy** [comment]
> Flask-Restful can reuse the same fields list for Resources that return one item or a list of items of the same kind.
> 
> In your example, you just need to do:
> 
> ```
> class TodoList(Resource):
>     @marshall_with(todo_fields)
>     def get(self):
>         return TODOS
> ```
> 
> That will return a JSON list like: `[{"task": "xxx"}, {"task": "yyy"}]`.
> You don't need a special fields for your lists.

Can we get an explanation on that, "You don't need a special fields for your lists"?

**Comment by ambvdijk** [comment]
> Can we get an explanation on that, "You don't need a special fields for your lists"?

@zmarffy I have been strugling with the same issue. I believe the correct solution is to provide the marshal with a extra setting to instruct it to actually use the model as a list. This also corrects the swagger contracts:

```Python
class TodoList(Resource):
    @marshall_with(todo_fields, as_list=True)
    def get(self):
        return TODOS
```

Notice the as_list=True

**Comment by zmarffy** [comment]
@ambvdijk Good to know. I gotta scrutinize code rather than docs.

**Comment by ahmadalli** [comment]
@ambvdijk I've got this exception using `as_list` parameter on version `0.3.8`

```
Exception has occurred: TypeError
__init__() got an unexpected keyword argument 'as_list'
```

**Comment by bertdida** [comment]
> Flask-Restful can reuse the same fields list for Resources that return one item or a list of items of the same kind.
> 
> In your example, you just need to do:
> 
> ```
> class TodoList(Resource):
>     @marshall_with(todo_fields)
>     def get(self):
>         return TODOS
> ```
> 
> That will return a JSON list like: `[{"task": "xxx"}, {"task": "yyy"}]`.
> You don't need a special fields for your lists.

This does not put the list inside the `tasks` property. 😕

**Comment by bertdida** [comment]
Surprisingly wrapping the `TODOS` inside an attribute works,

```python
todo_fields = {
    "task": fields.String,
}

todo_list_fields = {
    "tasks": fields.List(fields.Nested(todo_fields), attribute="items")
}

class Todo(Resource):
    @marshal_with(todo_fields)
    def get(self, todo_id):
        abort_if_todo_doesnt_exist(todo_id)
        return TODOS[todo_id]

class TodoList(Resource):
    @marshal_with(todo_list_fields)
    def get(self):
        return { "items": TODOS }
```

**Comment by akansha55** [comment]
Hey, need help 
i have a rest api model structure where down bellow structure look like. 

'most'  : fields.List(fields.String(title="most", required=False, example='S, B'))

now using some function and stuff its gives me output as "S and B" instead  i want output to look like S,B 
now the thing is that its a list of string and I want that example to be like 's','b' and when i am writing that its giving me positional argument follows keyword argument  error. 
and if i don't do that and want to put S,B as one value it gives me S and B. 
if anyone understands what's the issue please help me out and tell me how can i define list of string without using comma in api model.

**Comment by cisaacson** [comment]
I tried this in the latest version and just made the model dictionary like this:

```
todo_list_fields = {
    "items": "tasks": fields.List(fields.Nested(todo_fields))
}
```
It does the same thing as the `attribute` but that is made to rename the field when exposing it. This way you effectively make a single field model dictionary and it works fine.
