### ISSUE TITLE
JSON Schema support?

### ISSUE THREAD

**Issue by nickretallack** [flask-restful/flask-restful#301]
It would be really neat if I could specify my inputs (and outputs?) using [JSON Schema](http://json-schema.org/) instead of reqparse.

It's unfortunate that existing JSON Schema implementations do not actually coerce data for you, but they do contain enough information to specify how the data should be coerced, provided you pass in the relevant formatters.

It'd be super cool if I could then serve the JSON schema to describe my API when someone calls it with the OPTIONS HTTP method.

**Comment by florije1988** [comment]
+1, it will be cool when it have the function of the JSON Schema!

**Comment by joshfriend** [comment]
See #335.
