### ISSUE TITLE
Resource list.

### ISSUE THREAD

**Issue by CMLL** [flask-restful/flask-restful#304]
The method add_resource only adds the resource if self.app is True, but only register the resources if False. If i would like to view the already registered resources in the API, wouldn't that be the best place to keep it? Why add a resource only if there is no app registered?

```python
if self.app is not None:
    self._register_view(self.app, resource, *urls, **kwargs)
else:
    self.resources.append((resource, urls, kwargs))
```

**Comment by joshfriend** [comment]
I just tried this:

```python
if self.app is not None:
    self._register_view(self.app, resource, *urls, **kwargs)
self.resources.append((resource, urls, kwargs))
```

and a ton of tests fail with duplicate route registration errors. Unless theres a reason this would be helpful, I'm not going to worry about fixing it.
