### ISSUE TITLE
Reqparse validate "all or nothing" arguments

### ISSUE THREAD

**Issue by nickretallack** [flask-restful/flask-restful#321]
I have a group of arguments I'd like to add to my request parser.  They all go together.  That is, a request is valid if it specifies all of them or none of them.  Is there a way to get reqparse to do this?

Example:

```
	parser = reqparse.RequestParser()
	parser.add_argument('required_argument', required=True)
	parser.add_argument('optional_argument')

	# grouped arguments
	parser.add_argument('first_name', type=str, group='name')
	parser.add_argument('last_name', type=str, group='name')
```

This would be valid if first_name and last_name were specified, or if neither were, but if only one and not the other is specified it would not be valid.  Is there such a feature in reqparse?

**Comment by joshfriend** [comment]
Since this would be a rather large feature, I'd rather not add a ton of new stuff to `reqparse`, only to immediately deprecate it (#335).
