### ISSUE TITLE
Allow 1/0 for True/False in inputs.boolean?

### ISSUE THREAD

**Issue by joshfriend** [flask-restful/flask-restful#332]
When creating a URL query parameter string in Objective C from a dictionary:

``` objc
@{@"not_deleted": @YES}
```

The result looks like:

```
not_deleted=1
```

Which will raise `ValueError` when parsed by Flask-RESTful. Should the `inputs.boolean` parser be extended to accept `1` as `True` and `0` as `False`?

Perhaps additionally `"yes"` and `"no"`?

**Comment by TonyPythoneer** [comment]
This is my code:
```
class UserListResource(Resource):
    request_class = user_parser

    def get(self):
        return {'list': USERS}, 200

    def post(self):
        args = self.request_class.parse_args()
        new_id = max(USERS.keys()) + 1
        USERS[new_id] = args
        print args
        return args, 200
```

I submit the data:
```
{
    "username": "Tony",
    "gender": 1,
    "email": "tony@example.com"
}
```

This is my response fields:
```
user_fields = {
    'username': fields.String
}
```

I print the parse_args() and observe it:
```
{'username': 'Tony', 'gender': AttributeError("'int' object has no attribute 'lo
wer'",), 'email': u'tony@example.com'}
```

Finally, it will not raise any error but it returns the below:
```
TypeError

TypeError: AttributeError("'int' object has no attribute 'lower'",) is not JSON serializable
```

What happen? Is it bug?

**Comment by mackjoner** [comment]
ref the comments:
https://github.com/flask-restful/flask-restful/pull/341/files#diff-3dfb63fe71f79c86d5dbf637569d7374R203

**Comment by TonyPythoneer** [comment]
I see. Oh my god, it really doesn't handle int 0/1.
