### ISSUE TITLE
JSON response not ordered

### ISSUE THREAD

**Issue by digitalcraftsman** [flask-restful/flask-restful#377]
My current API doesn't return an ordered JSON-response as defined in `resource_fields`. The `marshal`-function returns already an OrderedDict which should be turned in JSON with the right order of the keys.

**Here's my code:**

``` python
resource_fields = {
    'id': fields.Integer,
    'title': fields.String,
    'description': fields.String,
    'favorite': fields.Boolean,
}

class MainViewAPI(Resource):
    def get(self):
                # Returns a list of SQLAlchemy objects.
                # The list should now contain a few OrderedDicts
        return [marshal(item, resource_fields) for item in Bookmark.get_all()]
```

**The output with dummy data:**

``` json
[
    {
        "description": "ddddddd",
        "id": 1,
        "title": "dfdsf"
    },
    {
        "description": "dfds",
        "id": 2,
        "title": "55555"
    },
    {
        "description": null,
        "id": 4,
        "title": "dgdsgdsgf"
    }
]
```

The output's order doens't match the defined one in `resource_fields`. Any ideas?
Thanks for the help and the great Flask extension.

**Comment by Sushang-Agnihotri** [comment]
Add this config line to your code after the app definition : 

app = Flask(__name__)
app.config['JSON_SORT_KEYS'] = False
