### ISSUE TITLE
fields.Nested({fields.Url}) results in url_for() argument after ** must be a mapping.

### ISSUE THREAD

**Issue by scottwernervt** [flask-restful/flask-restful#383]
The [Full Parameter Parsing Example](https://flask-restful.readthedocs.org/en/latest/intermediate-usage.html) has an example of using `fields.Nested` to create a sub-object in the response:

```python
'links': fields.Nested({
    'friends': fields.Url('/Users/{id}/Friends', absolute=True),
    'posts': fields.Url('Users/{id}/Posts', absolute=True),
}),
```

However, when I incorporate this snippet into my own code, I get the error: `flask_restful.fields.MarshallingException: url_for() argument after ** must be a mapping, not NoneType`.

```python
role_fields = {
    'id': fields.Integer,
    'name': fields.String,
    'uri': fields.Url('role'),
}

user_fields = {
    'id': fields.Integer,
    'uri': fields.Url('user'),
    'links': fields.Nested({
        'roles': fields.Url('/users/{id}/roles'),
    }),
}

api.add_resource(User, '/users/<id>', endpoint='user')
api.add_resource(UserRoles, '/users/<id>/roles', endpoint='user_roles')
```

I get the same error if I replace `fields.Url('/users/{id}/roles')` with `fields.Url('user_roles')`.

**Comment by joshfriend** [comment]
I would guess that one of the attributes you are trying to serialize into a URL is `None`. When that happens, `url_for` is called like:

```python
url_for(endpoint, **None)
```

which raises the `TypeError` you see here.

**Comment by scottwernervt** [comment]
I created an example to demonstrate the error: https://gist.github.com/scottwernervt/4e154dc9126b1483b37b

User has the `id` attribute so I expect `fields.Url('/users/{id}/roles')` to insert it when creating the url, e.g /users/1/roles. As mentioned in the docs, it should work in the same manner as `fields.FormattedString`.

Resources
* http://127.0.0.1:5000/roles/1
* http://127.0.0.1:5000/roles/2
* http://127.0.0.1:5000/users/1 -- Fails
* http://127.0.0.1:5000/users/1/roles

**Comment by joshfriend** [comment]
Your `users` data source contains _only_ an ID (`{'id': 1}`), there is no role information in the object you are trying to serialize, thus the error. You need to include the role info in your user data you serialize if you want this to work.

**Comment by joshfriend** [comment]
It also is a problem that you are nesting the role info inside `links`. you user data would need to have a `user.links.roles` attribute for that to work.

**Comment by joshfriend** [comment]
The parameter to `fields.Url` is also the name of the endpoint, you are passing it something that would work for `FormattedString`. for your example, you need to pass `'user_roles'`, since thats the name you gave the endpoint.

**Comment by scottwernervt** [comment]
Thanks @joshfriend that cleared it up for me.
