### ISSUE TITLE
fields.Url docs incorrect in "Intermediate Usage"

### ISSUE THREAD

**Issue by joshfriend** [flask-restful/flask-restful#385]
See #383.

Also, the docstring itself is rather lacking in clarity.

**Comment by ueg1990** [comment]
what is the correct usage? i can update it in the docs

**Comment by joshfriend** [comment]
[this](http://flask-restful.readthedocs.org/en/0.3.1/fields.html#url-other-concrete-fields) is the correct usage of `fields.Url`. [this](https://github.com/flask-restful/flask-restful/blame/2c92831984c8052b21a8a9b73ecfc2fd2bda05ec/docs/intermediate-usage.rst#L120-L121) is incorrect. `fields.Url` does not accept a format string as shown in that example

**Comment by joshfriend** [comment]
Fixed by #406
