### ISSUE TITLE
reqparse.Argument

### ISSUE THREAD

**Issue by kenjones-cisco** [flask-restful/flask-restful#387]
The default location is (json, values). The call to `value = getattr(request, l, None)` where `l = 'json' `results in a `BadRequest()` exception from flask if there was no data to parse.

`flask.wrappers.Request.get_json` has a flag silent that will result in `None` being returned instead of throwing the `BadRequest()` exception when there is no data to parse. 

Options:
- calls to `get_json` uses `silent = True`
- a check if data exists prior to making the call to `get_json`
- an option for flask-restful consumers to specify `silent = True`
- a bug request to Flask proper to check for if data prior to performing `json.loads`

**Comment by kenjones-cisco** [comment]
Also to note, this will trigger it as well:
`req.unparsed_arguments = dict(Argument('').source(req))`

By calling Argument with all default parameters the json location will be checked and if the request has no data and a 'Content-Type': 'application/json' still results in performing the `json.loads` on empty/None

**Comment by kenjones-cisco** [comment]
Seems to have already been fixed with commit: 2f3a4275ee092b6948f8f6124bc25ee042c49366

Any plan to release current version soon?

**Comment by kenjones-cisco** [comment]
The commit handles the issue noted in the second comment, but the initial one holds true if the default location of ('json', 'values',) is not changed to ('values',)

**Comment by RonnyPfannschmidt** [comment]
in the strict sense not passing any data as the request body on json contenttype is wrong
since an empty string is not valid json

**Comment by joshfriend** [comment]
That is true:

```
>>> import json
>>> json.loads('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josh/.pyenv/versions/2.7.9/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/josh/.pyenv/versions/2.7.9/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/josh/.pyenv/versions/2.7.9/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Based on that and discussion in mitsuhiko/flask/#1317, I'm closing this as wontfix.

**Comment by kenjones-cisco** [comment]
I do understand the feedback issue https://github.com/mitsuhiko/flask/issues/1317, and I expected but as I listed multiple options for solving the problem as requesting a change within flask itself, I opened an issue there. But I actually expected the response that I got from them there.

But in the case of reqparse, the default is json and values because input data could come from EITHER location. If the caller to the API happened to use parameters but maintained a static content type for all requests as application/json, then I have no way to handle the issue since some users might pass in a json payload and others might leverage form data, and others still might leverage query parameters. Building the API to meet each of those needs is the reason for using this extension and the the parser. 

As such, there should be a way to avoid getting the BadRequest exception if the data was in one of the other locations being parsed out because as a provider I don't care which approach the consumer uses I just want the data from the request parsed and returned as part of the dict.

To avoid doing anything crazy, why not provide access to the silent parameter, such that if there are any exceptions while parsing any one of the multiple locations specified (by the default or through actually specifying the different locations), that the decision if it is a BadRequest be controlled by the provider. Therefore an option on the Parser to ignore errors (silent = True) parsing the data per location, and then if no data was found within any location specified then the proper exception can be raised?

**Comment by joshfriend** [comment]
> input data could come from EITHER location.

Thats a good point. I hand't thought of that. Allowing the user access to the `force` and `silent` params to `get_json` would probably be the best option in that case.

Also, the next version of flask will rise deprecation warnings when using the `json` attribute, so some change should probably be made sooner than later to use `get_json` instead...

**Comment by RonnyPfannschmidt** [comment]
on a sidenote, json is supposed to be None on valid requests that are not json

its wrong not to fail if a request claims to be json but isnt

**Comment by RonnyPfannschmidt** [comment]
a much better way to add non-standard behavior that allows silent acceptance of wrong data would be to create a custom request subclass and use that in a per application basis as customers request it
