### ISSUE TITLE
404 when string argument contains '%2F'

### ISSUE THREAD

**Issue by dvska** [flask-restful/flask-restful#393]
```
app = Flask(__name__)
api = restful.Api(app)

class QueueUrl(restful.Resource):
    def post(self, id, url):
        # DO SMTH
        return {"status": "OK"}

api.add_resource(QueueUrl, '/v1/site/<int:id>/<string:url>')
```

when I call it with 
`   curl -X POST  http://127.0.0.1:8080/v1/site/1/site.com -->  {"status": "OK"}`
but
`   curl -X POST  http://127.0.0.1:8080/v1/site/1/http%3A%2F%2Fsite.com --> 404!!!`

**Comment by joshfriend** [comment]
See mitsuhiko/flask#900

Try passing the URL as a querystring parameter instead:
`curl -X POST http://127.0.0.1:8080/v1/site/1?url=http%3A%2F%2Fsite.com`
