### ISSUE TITLE
Scaffold RESTful API from a model

### ISSUE THREAD

**Issue by scls19fr** [flask-restful/flask-restful#394]
Hello,

I wonder if RAML 
http://www.sitepoint.com/raml-restful-api-modeling-language/
http://raml.org/
couldn't be use to create (scaffold) a Flask-RESTful app.

Same idea for client:
https://github.com/kennethreitz/requests/issues/2443

See also:
https://github.com/an2deg/pyraml-parser

Kind regards

PS: I'm writing this about RAML but maybe API Blueprint https://apiblueprint.org/ or Swagger http://swagger.io/ are also good candidates

**Comment by joshfriend** [comment]
This is basically the inverse of #395. Flask-RESTful makes no attempt to be able to scaffold an API from a model. [There are already other frameworks that do that](https://flask-restless.readthedocs.org/en/latest/).

**Comment by scls19fr** [comment]
Thanks for the link.
