### ISSUE TITLE
Improve doc about documenting API RESTful

### ISSUE THREAD

**Issue by scls19fr** [flask-restful/flask-restful#395]
Hello,

I'm looking http://flask-restful.readthedocs.org/en/0.3.1/
I was looking for REST API documentation generation with flask-restful.
But I didn't find anything here.

I've found https://github.com/rantav/flask-restful-swagger
but also http://stackoverflow.com/questions/14295322/what-tools-are-available-to-auto-produce-documentation-for-a-rest-api-written-in
but nothing seems to be really standardized.

Maybe doc should be improved to give some guidance about it.

Kind regards

**Comment by stas** [comment]
We used sphinx HTTP domain extension to document the API. I believe it is one of the best options at this moment.

http://pythonhosted.org/sphinxcontrib-httpdomain/

I also don't think the project should endorse any specific tool. I think it is out of the project scope.

**Comment by joshfriend** [comment]
I've been using the Apiary format (basically markdown) for my projects. I would love a package like flask-restful-swagger for apiary docs, but I agree with @stas that it's outside the scope of this project.
