### ISSUE TITLE
Api.url_for does not work with blueprints

### ISSUE THREAD

**Issue by mjmare** [flask-restful/flask-restful#396]
This is extract of my code:

```python
api_bp = Blueprint('api', __name__)
api = Api(api_bp, prefix='/api')

class PersonApi(Resource):
    def post(self):
        # ...
        url = api.url_for(PersonApi, uuid=person.properties['uuid'])  # fails with BuildError
        # ...

api.add_resource(PersonApi,
                 '/persons/<string:uuid>', '/persons',
                 endpoint = 'persons_ep')
```
fails with 

```
BuildError: ('persons_ep', MultiDict([('uuid', u'159a17bc-0d3f-49e0-a4ca-3e19d7f61daa')]), None)
```
Omitting the parameter (for testing) does not change the error.
The alternative:

```python
url = url_for('.persons_ep', uuid=person.properties['uuid'])
```
using the Flask url_for does work.

**Comment by J12D** [comment]
Shouldn't ```def post(self):``` be ```def post(self, uuid):```?

**Comment by mjmare** [comment]
Hmmm, don't think so. The endpoint points to the "whole" Resource, not the post method. In my example it just happens to be that that my post method not only stores an object but also returns some information. this includes the "Location" of the object. It should result in something like Location: '/persons/someuuid'. Hope that makes things clearer ;-)

**Comment by SystemKeeper** [comment]
I can confirm this problem with blueprints (using more or less identical code as @mjmare).
As a workaround I'm currently doing something like this:
```python
class PersonApi(Resource):
    def post(self):
        # ...
        url = api.url_for("." + PersonApi.endpoint, uuid=person.properties['uuid']) 
        # ...
```
which works, but I really think that flask-restful should take a blueprint into account for the url_for function.
