### ISSUE TITLE
flask-restful requires username and password, but I never did that

### ISSUE THREAD

**Issue by mcescalante** [flask-restful/flask-restful#398]
I started to add a method_decorator to a resource I have, and then deleted the code, reverting it to the non-protected resource it was that worked. Now, every time that I try to access that resource, I see the error "the server at localhost requires a username and password. the server says: flask-restful"

I have cleaned all .pyc files out, and uninstalled and reinstalled flask-restful. There are no other code changes other than adding and deleting the small decorator as well as the method_decorator line in the resource. I am still seeing the "username and password" dialogue.

What could be causing this? Glad to upload pictures or provide more information if there is not enough.

**Comment by svenstaro** [comment]
Possibly your browser? Try another browser.

**Comment by mcescalante** [comment]
Just tested with Firefox (was previously using Chrome Canary) and I am seeing the exact same "Authentication Required" dialog.

**Comment by mcescalante** [comment]
Update: I am accessing a third party API, and the auth error I am getting seems to be coming from that API. But, since flask-restful is the one serving the Resource, it's showing "flask-restful" in the Authentication Required error dialogue, and this may be misleading. I'm going to update this and close it once I confirm that it is my third party causing the issue, and not anything to do with Flask-Restful. Thank you very much @svenstaro for the very prompt reply :smile:

**Comment by gregeinfrank** [comment]
I had a similar problem. Every 401 from my server was showing this authentication dialog in the browser.

Here's how I fixed it:

```python
# Flask RESTful
restful_api = Api(app)
restful_api.unauthorized = lambda a: a  # Overwrite the credentials response
```

**Comment by mcescalante** [comment]
Clever @gregeinfrank, I'm going to make a note of that. But it does look like the API that I was using to serve the photo was at fault, and that someone revoked those credentials for one reason or another.

I would suggest that if it's even possible, Flask-Restful passes the "server says: x" error through so that it doesn't display as flask-restful. In reality, in this case here, it would have optimally read "NetKernel."

**Comment by mcescalante** [comment]
Just weighing in after having working out all the kinks in the code - I think that having the option as a config variable to disable the `WWW-Authenticate` challenge raised on every 401 would be great. 

I used @gregeinfrank's fix because I just want the endpoint to return a 401 so the end-user knows that their authentication in that request is wrong, not raise another Basic authentication attempt. Looking at the other issues referenced above, it seems like there was generally hesitation to allow users to disable this `WWW-Authenticate` at some point in the past.

**Comment by joshfriend** [comment]
It's tricky because the request made by the *client* did not fail because a valid username/password was not provided, the request made by the *backend* to the external api on the client's behalf was actually the one that failed, but that error is being shown to the client directly. Perhaps returning a 400 error to the client in this case would be more appropriate, or 500 if the username/password for the other API is not provided by the client and is stored in the server configuration.

**Comment by svenstaro** [comment]
@joshfriend What do you think about adding a config for that for now? It seems to generally be a problem that people have and I don't like the hack being accepted as the general way to fix it.

**Comment by svenstaro** [comment]
Give this a spin guys and tell me how it works out for you.

**Comment by joshfriend** [comment]
[RFC2616](https://www.ietf.org/rfc/rfc2616.txt):

> The response **MUST** include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource.

I like the config option added in fe53f49, but the default should really be `True`.

**Comment by svenstaro** [comment]
This is a correctness vs. pragmatism thing. On one hand, you probably never will want your API backend to issue a Basic Auth to your browser, on the other hand it's not correct not to do so. Judging by all the different issues that were reported on this and how many people were bitten by this, I think one can argue that in this case, convenience is better than correctness but I'm happy to change it if it makes you entirely unhappy.
