### ISSUE TITLE
Adding inputs.email as one of predefined parsers

### ISSUE THREAD

**Issue by madvas** [flask-restful/flask-restful#407]
I think it would be useful if flask.ext.restful.inputs contained also email parser as it's very commonly used.

I mean as one of these:
http://flask-restful.readthedocs.org/en/latest/api.html#module-inputs

Thank you,
Matus

**Comment by joshfriend** [comment]
[It's kindof ugly](https://github.com/django/django/blob/ea3168dc6ced391d848c511a14cfcecfeac9d401/django/core/validators.py#L137), but definitely a possibility.

**Comment by max-orhai** [comment]
I'm working on this one, and should have a PR ready for review soon.

**Comment by joshfriend** [comment]
@max-orhai I took a peek at the commit you made. This issue is asking about an input validator, what you made is a serializer that validates email as it is being output.

**Comment by max-orhai** [comment]
@joshfriend  No garbage in, maybe garbage out?
An input validator is here: https://github.com/flask-restful/flask-restful/pull/422
