### ISSUE TITLE
RequestParser type bool incompatibility between json and values

### ISSUE THREAD

**Issue by atlithorn** [flask-restful/flask-restful#413]
parser = reqparse.RequestParser()
parser.add_argument('checked', type=bool)
args = parser.parse_args()

This works fine if you send json w. location as 'json' but if the location is 'values' then regardless of what you send as an argument ('false', 0, 'False') args['checked'] is always True

I realise why this happens but it's kind of a big gotcha if you switch between location types carelessly (which is what happened to me :))

**Comment by joshfriend** [comment]
see #397
