### ISSUE TITLE
how to have multiple authentication decoratores for different method ?

### ISSUE THREAD

**Issue by cshamoud** [flask-restful/flask-restful#415]
i'm wondering how to have different authentication for different methods using flask-httpauth

i have done this

class test(Resource):
        def get(self):
              self.decorators = [Clients.auth.login_required]
               ...etc
        def post(self):
              self.decorators = [Admins.auth.login_required]
               ...etc

but didn't work

any thoughts ?

**Comment by joshfriend** [comment]
Per method decorators go like this:

```python
class Foo(Resource):
    @auth.login_required
    def get(self):
        pass
```
