### ISSUE TITLE
fields.Url with key selector

### ISSUE THREAD

**Issue by ehmsen** [flask-restful/flask-restful#418]
Consider the following minimal example, which should exemplify an API that handles a user message board, where users can make posts, so every post has an associated user. In the following the first post (post #1) has been made by user with user id 42:

```python
user_fields = {
	'id' : fields.Integer,
}
class UserAPI(Resource):
	def __init__(self):
		Resource.__init__(self)
api.add_resource(UserAPI, '/v1.0.0/users/<int:id>', endpoint = 'user')

post_fields = {
	'id' : fields.Integer,
	'user' : fields.Url('user')
}
class PostAPI(Resource):
	def __init__(self):
		Resource.__init__(self)

	@marshal_with(post_fields)
	def get(self, id):
		return {'id' : 1, 'user_id' : 42}
api.add_resource(PostAPI, '/v1.0.0/posts/<int:id>', endpoint = 'post')
```
If I make a GET request for /v1.0.0/posts/1 (or any other number for that matter) I get the following JSON reply:
```json
{
    "id": 1,
    "user": "/v1.0.0/users/1"
}
```
However, the user that has made this post is the user with id 42 (see the get method on PostAPI).

I order to fix that I have looked at the source for flask restful and it seems it does not support my use case here (or am I mistaken?).
So I created the following class for my needs:
```python
class MyUrl(fields.Raw):
	def __init__(self, endpoint = None, key = None,
				 absolute = False, scheme = None):
		fields.Raw.__init__(self)
		self.key = key
		self.endpoint = endpoint
		self.absolute = absolute
		self.scheme = scheme

	def output(self, key, obj):
		try:
			data = fields.to_marshallable_type(obj)
			endpoint = self.endpoint if self.endpoint is not None else request.endpoint
			if self.key is not None and self.key in data:
				val = data[self.key]
				o = urlparse(url_for(endpoint, _external=self.absolute, id = val))
			else:
				o = urlparse(url_for(endpoint, _external=self.absolute, **data))
			if self.absolute:
				scheme = self.scheme if self.scheme is not None else o.scheme
				return urlunparse((scheme, o.netloc, o.path, "", "", ""))
			return urlunparse(("", "", o.path, "", "", ""))
		except TypeError as te:
			raise fields.MarshallingException(te)
```
which is very much a copy of fields.Url from flask restful, however it supports adding a key to the constructor, such that I can now do the following:
```python
post_fields = {
	'id' : fields.Integer,
	'user' : MyUrl('user', 'user_id')
}
```
and now I get the correct link to the user who made the post:
```json
{
    "id": 1,
    "user": "/v1.0.0/users/42"
}
```

So my question/issue:
- Am I mistaken in thinking that there is no way of achieving the result I want using existing flask restful functionality?
- If that is the case, I think you should include the functionality either using my code above or some variant thereof.

Thanks!
Martin

**Comment by joshfriend** [comment]
Try giving your URL paths more descriptive element names (not use `id` to name everything):

```python
from flask import Flask
from flask_restful import Api, Resource, Api, fields, marshal_with

app = Flask(__name__)
api = Api()

post_fields = {
    'id' : fields.Integer,
    'user' : fields.Url('user')
}

class UserAPI(Resource):
    pass

class PostAPI(Resource):
    @marshal_with(post_fields)
    def get(self, post_id):
        return {'id': post_id, 'user_id': 42}

api.add_resource(UserAPI, '/users/<int:user_id>', endpoint='user')
api.add_resource(PostAPI, '/posts/<int:post_id>', endpoint='post')

api.init_app(app)

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by CMCDragonkai** [comment]
Does `endpoint` have to be specified? I tried just using the lowercase name of the resource class, but it didn't work. It couldn't find it. Note my resource was put under a namespace, not sure if that matters.

I had to put a special unique name for the endpoint for the `Url` to find it.
