### ISSUE TITLE
Resource-level representation decorators

### ISSUE THREAD

**Issue by faraocious** [flask-restful/flask-restful#419]
This is as much a question as an issue/feature-request.

If it is in the wrong place I'm sorry, let me know and I can file it correctly.

I have some data that I need to be able to return in a resourceful, nested manner, but also a flat csv format.    The basic idea that I had was to create representation decorators that would do that formatting at the last minute, but those decorators are more about encoding than they are content.

I'm was looking through the code and couldn't find any representation decorators at the resource level, and the marshal* decorators don't seem to fit the bill either.  I feel like what i'm looking for is actually right in the middle of the two concepts,  a Content-Type dependent marshalling function.  I'm not sure what the final solution should look like, but i would be interested in helping to implement the solution.

If i'm way off base and approaching this the wrong way, let me know and I will change my own code to use best practices. I'm a bit new at this.

**Comment by joshfriend** [comment]
`marshal` and `marshal_with` only convert your objects returned from the `Resource` methods into a python `dict` containing simpler types (`int`, `float`, `str`, `bool` and the like). It **does not** convert those marshalled dicts into JSON. This is handled by the default [representation](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/representations/json.py).

You can create alternate representation serializers as defined [here in the docs.](http://flask-restful.readthedocs.org/en/0.3.2/extending.html#content-negotiation) There is an [example of an XML serializer in the repo here](https://github.com/flask-restful/flask-restful/blob/6255cad1ff2a24b1b69b1e695e46f163b9e641ec/examples/xml_representation.py). You would create a similar "representation" which would generate CSV. This representation would be used when the request has the `Content-Type: application/csv` header (or whatever content type you register the representation as).

Does that help?

**Comment by faraocious** [comment]
Thank you very much for the fast response!

I understand the use of `@api.representation()` and `@marshal_with()` functions.

representation is for encoding, which is fine.   @marshall is for type conversion but also structure (when nesting fields).  the issue i'm running into is that the structure of the returned data needs to change based on the representation. So i feel like i need one `@marshal_with()` decorator for csv, and one for json, since csv is a non-nesting.

The issue is that I am trying to return some nested data in json (in order to make the returned data more conceptual) but when trying to handle csv requests to the same endpoint, I am at a loss for how to format and return the data within flask-restful.

**Comment by joshfriend** [comment]
because of how CSV is flat, I don't think theres a way that you could make a `marshal_with` handle nested data for that case intelligently. I don't think you would want to either since the sole purpose of that function is to convert your objects to more basic types. I think you will have to do your "flattening" in the CSV representation.

**Comment by faraocious** [comment]
Right, but the representation functionality happens at the API level, so whatever that csv representation looks like, It'll have to be abstract enough to work for any resource on the API.  So `representation()` also doesn't seem like an ideal place to put the code.  << This is the trouble I'm having.
