### ISSUE TITLE
initialize in every request

### ISSUE THREAD

**Issue by stsouko** [flask-restful/flask-restful#421]
why parser initialize in every time then get request from client?
I expected this code allow  ещ reduce the load, but this don't work.

class Test(Resource):
    def __init__(self):
        parser = reqparse.RequestParser()
        parser.add_argument('field', type=str)
        self.parser = parser

    def post(self):
        args = self.parser.parse_args()

**Comment by joshfriend** [comment]
Do this:

```python
parser = RequestParser()
parser.add_argument('foo')

class Foo(Resource):
    def get(self):
        args = parser.parse_args()
```
