### ISSUE TITLE
Improve documentation for authenticating requests

### ISSUE THREAD

**Issue by czardoz** [flask-restful/flask-restful#424]
Since the primary use of this library is building RESTful APIs, there should be good docuumentation about authenticating requests with client keys, etc. 

The authentication documentation currently is very scanty, and not very clear. The only place where HTTP Basic Authentication is mentioned is [this](https://github.com/flask-restful/flask-restful/blob/master/docs/extending.rst#resource-method-decorators), which is not very clear about how one would go about implementing the ``basic_authentication()`` function.

**Comment by joshfriend** [comment]
Flask auth libraries like Flask-HTTPAuth, Flask-JWT, and Flask-Login already handle auth stuff for you, so I don't see a reason to describe implementing one of those libraries yourself in the Flask-RESTful docs.
