### ISSUE TITLE
Resource returns unexpected message if loop longer than a certain length

### ISSUE THREAD

**Issue by Tamerz** [flask-restful/flask-restful#425]
I'm probably just doing something wrong, but I have the following (using version 0.3.2):

```
class SessionApi(Resource):

    @staticmethod
    def get(session_id):

        sessions = get_wanted_session(session_id)

        if sessions:
            return sessions
        else:
            abort(404, message="Session ID {} not found.".format(session_id))
```
Along with:
```
api.add_resource(SessionApi, '/v1/session/<session_id>')
```

In that ```get_wanted_session()``` function, I'm just looping over a bunch of XML files and looking for any file with the specified field (session_id).

If the list of files is less than 362 files, it works as expected. However, if the list of files is longer, I get this response:
```
{
    "message": "",
    "status": 4
}
```
If I put a ```print(sessions)``` before the ```if sessions:``` line, I can see it prints the single result which is just a single dict inside a list.

I'm confused why the number of iterations the ```get_wanted_sessions()``` function goes through would make any difference. I'm still getting the correct list. If I kill the loop early by stopping after 150 or so files, it returns the exact same single dictionary inside a list and returns the correct result.

I don't believe it to be a timing issue, since it returns results almost instantly.

**Comment by Tamerz** [comment]
The ```get_wanted_session()``` function. You can see the commented out lines that if I uncomment cause everything to work correctly:

```
def get_wanted_session(session_id):
    # i = 0
    sessions = []
    raw_files = get_xml_files_in_folder(SESSION_FOLDER)
    for _file in raw_files:
        file_path = os.path.join(SESSION_FOLDER, _file)
        new_session = Session()
        try:
            new_session.parse_file(file_path)
        except KeyError:
            pass

        if new_session.id == session_id:
            sessions.append(new_session.get_json())

        """
        if i > 150:
            break
        i += 1
        """

    return sessions
```

**Comment by theovoss** [comment]
Have you considered using a database instead of xml files? 

```In that get_wanted_session() function, I'm just looping over a bunch of XML files and looking for any file with the specified field (session_id).```

that you're looking for a specific field makes me think that using a database might be a better solution than xml files. 

Summary: I have no clue why it is giving you different performance when the list of files is long (that's weird), but that you're looping over a huge list of files and looking at the content on each request makes me think you want a database.

**Comment by Tamerz** [comment]
@theovoss I wish I had a choice! Unfortunately, I'm working with a legacy system. The plan is to move it to a database eventually, but it is a huge project that I am not involved in.

**Comment by Tamerz** [comment]
One other thing I found, if I just use Flask and render to a template with the same code, it works fine:

```
@app.route('/session/<session_id>')
def session_page(session_id=None):

    sessions = get_wanted_session(session_id)

    if sessions:
        return render_template('sessions.html', sessions=sessions)
    else:
        return abort(404)
```

**Comment by Tamerz** [comment]
OK, I knew I was doing something wrong. There was a bad XML file causing the issue. Something was invalid in one of them and triggered this. When I remove that file, everything works as expected.

Thanks for looking.
