### ISSUE TITLE
Allow parameters to be passed to the resource class constructor on add_resource()

### ISSUE THREAD

**Issue by asmodehn** [flask-restful/flask-restful#429]
As a similar example, one can do this in flask with [Pluggable Views](http://flask.pocoo.org/docs/0.10/views/)
```
class RenderTemplateView(View):
    def __init__(self, template_name):
        self.template_name = template_name
    def dispatch_request(self):
        return render_template(self.template_name)

app.add_url_rule('/about', view_func=RenderTemplateView.as_view(
    'about_page', template_name='about.html'))
```

In my current use case of flask-restful, I need my resource to get a parameter ( storing data that will be requested later via REST ) and AFAIK it s not currently possible with add_resource ( or I cannot find a way... )

add_resource uses as_view internally, so I am guessing it is probably doable...

**Comment by mikehwang** [comment]
I also need this.  I have a branch with a fix on my fork.  PR has been submitted.  https://github.com/flask-restful/flask-restful/pull/444
