### ISSUE TITLE
nullable options for Argument?

### ISSUE THREAD

**Issue by huxuan** [flask-restful/flask-restful#432]
`required=True` doesn't satisfy when passing empty value. 
It will be better to have another option like `nullable` in SQLAlchemy.

**Comment by VladimirPal** [comment]
@huxuan Right, it's a strange behaviour, i've created pull request.

**Comment by huxuan** [comment]
To be more specific about this issue, currently when we request with empty value, e.g. something like `curl -X GET http://localhost $host/api/test?foo=&bar=1`, if the `parser` is initialized by `parser.add_argument('foo', required=True)`, `parser.parse_args()` won't do anything and this request will be marked as valid. But we do need an option to handle this kind behavior.

I think we have two choices, one is make `required=True` cover this (raise missing required paramter error), the other is add another option `nullable` which will do the same job.

And after some investigation and thinking, I prefer to have `required=True` also cover empty value request. What do you think of it? @joshfriend @VladimirPal

**Comment by joshfriend** [comment]
@huxuan apparently the issue is [already fixed?](https://github.com/flask-restful/flask-restful/pull/433#issuecomment-99103845)

**Comment by huxuan** [comment]
@joshfriend Thanks for your reply and attention.

But for my request, I am afraid not. Cause what I want is a trigger for another kind of BadRequest when requesting empty value.

For example, when requesting `curl -X GET http://localhost/api/test?foo=`, even `foo` has `required=True` or `default=bar`, this request will still be marked as a valid one, as both `required` and `default` won't take any effect.

After digging into the code base, I found at [reqparse.py#L190 in current master branch](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/reqparse.py#L190), the value for  `results` will be `['']` rather than `[]` or `''` for that specific request. So `not results` won't cover the situation for empty value. I think `Argument.parse()` should deal with empty value better. Do you have any suggestions for this? It will be my honor to have a chance to make some contribution to `flask-restful`. ;-)

**Comment by rishi-freshbooks** [comment]
Any update on this? I too am having similar issues. Thanks!

**Comment by joshfriend** [comment]
Due to #335, I'd recommend switching to marshmallow if possible.
