### ISSUE TITLE
Question: Is there a better way of using middlewares?

### ISSUE THREAD

**Issue by ianjuma** [flask-restful/flask-restful#441]
Not a big fan of flasks ``` @before_request()``` . Is there a better way to define middle-wares?; such as falcons:

```python
# Configure your WSGI server to load "things.app" (app is a WSGI callable)
app = falcon.API(middleware=[
    AuthMiddleware(),
    RequireJSON(),
    JSONTranslator()
])

db = StorageEngine()
things = ThingsResource(db)
app.add_route('/{user_id}/things', things)
```

**Comment by joshfriend** [comment]
Falcon is a WSGI framework, whereas Flask-RESTful is only a REST helper layer for Flask (Flask uses the Werkzeug WSGI framework). Thus, Flask-RESTful doesn't really have anything to do with middlewares.

I have a suggestion, however:

```python
app = Flask__name__)
api = Api(app)

middleware_classes = [
    AuthMiddleware,
    RequireJSON
    JSONTranslator,
]

for cls in middleware_classes:
    app.wsgi_app = cls(app.wsgi_app)
```

References:

* [Flask.wsgi_app](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.wsgi_app)
* [Werkzeug Middlewares](http://werkzeug.pocoo.org/docs/0.10/middlewares/)

If that doesn't suit your needs, you will probably have to raise your question in the issues list for Flask itself.

Does that help?

**Comment by ianjuma** [comment]
@joshfriend yes, thanks. The references helped a lot. :+1:
