### ISSUE TITLE
ReqParse: «Case sensitive» option has ambiguous description

### ISSUE THREAD

**Issue by MarSoft** [flask-restful/flask-restful#442]
Hello. I wanted to get Request Parser which ignores case of values passed: for it to accept both `http://example.com/system=unix` and `http://example.com/System=unix`
So I found `case_sensitive` option for RequestParser and gladly set it to `False`.
Later I spent several hours trying to determine why the hell Google authorization is failing. And it turned out that with `case_sensitve` set off RequestParser converts all **values** to lowercase! Even those which have no `choices` defined.

So I would like to ask to change description of this option from «Whether the *arguments* in the request are case sensitive or not» to «Whether **values of arguments** in the request are case sensitive or not **(this will convert *all* values to lowercase)**». And maybe append an option for ignore-case keys.

**Comment by joshfriend** [comment]
Thanks for reporting the error. Sorry it caused you so much frustration.
