### ISSUE TITLE
Inputs date min. year limit 1900

### ISSUE THREAD

**Issue by maximium** [flask-restful/flask-restful#443]
Hey guys, I wonder why year must be >= 1900 in inputs.date?
https://github.com/flask-restful/flask-restful/blob/f44ba85222d0961cb5fc78223b81c848605e78fb/flask_restful/inputs.py#L188-L189

**Comment by joshfriend** [comment]
The implementer probably misunderstood [the docs](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior) which say that `strftime` cannot be used for years < 1900:

```python
>>> d = datetime.strptime('1899-01-01', '%Y-%m-%d')
>>> d.strftime('%Y-%m-%d')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year=1899 is before 1900; the datetime strftime() methods require year >= 1900
```

Since `strftime` is not used anywhere, I'd say this check can be removed.

**Comment by maximium** [comment]
It's done, Sir
https://github.com/flask-restful/flask-restful/pull/446
