### ISSUE TITLE
How to use Flask-Cache with Flask-Restful

### ISSUE THREAD

**Issue by parkour99** [flask-restful/flask-restful#454]
Hi, when i want to use that code as follow:

```python
@cache.cached(timeout = current_app.config['CACHE_DEFAULT_TIMEOUT'])
def get(self):
     return something
```

it does not work, because not in the context of the app.
so how i use cache decorator in the front of the function.
The same question like this link :
           http://stackoverflow.com/questions/24816799/how-to-use-flask-cache-with-flask-restful

**Comment by joshfriend** [comment]
The value of the timeout is evaluated when the module containing the `Resource` is imported. There is no active application or request context active at this point, hence the context related error you see when trying to use the `current_app` proxy.

If you don't specify a value for the `timeout` parameter, the value from `CACHE_DEFAULT_TIMEOUT` in the application's config object is used instead, so what you were trying to assign for `timeout` is basically redundant.

**Comment by parkour99** [comment]
Thank you for your kind reply. i set it in the application 's config.
