### ISSUE TITLE
Does marshal_with need to be a class?

### ISSUE THREAD

**Issue by justanr** [flask-restful/flask-restful#459]
I'm working a project and using Marshmallow as my serializer (sorry guys D: ), so I wrote my own spin on `marshal_with` to use those schemas instead. I used `flask_restful.marshal_with` as a reference implementation, but it's implemented as a class with only `__init__` and `__call__`. Would a closure be more appropriate here instead? Or is the expectation for it to be subclassed and modified?

[My spin, for reference.](https://github.com/justanr/owa/blob/c636bc21fae8ae63725607f23f9c7bd03a600c12/owa/utils/schema.py#L26)

**Comment by joshfriend** [comment]
`marshal_with` was introduced in a4465e3 (the very first commit actually), so I don't know what the reason for it being a class is. I don't think subclassing it would be particularly useful. I guess it's in a state of "if it's not broke, don't fix it" state right now.

I like your marshmallow implementation, might have to try that sometime...

**Comment by justanr** [comment]
Thanks. I don't think it being a class is gonna be a bottle neck for anyone. It was more of "what the heck" moment when I saw it. I could see it being subclassed to do *something* extra but heck if I know what.
