### ISSUE TITLE
Flask-restful, marshal_with + nested data from POST

### ISSUE THREAD

**Issue by adaro** [flask-restful/flask-restful#460]
Hey guys! Thank you very much for the hard work. One question I have is using `marshal_with` when POSTing to an endpoint. Let's say I have a json object with an array of nested objects. How would parse the array of nested objects? Please take a look at my SO question: http://stackoverflow.com/questions/30655146/flask-restful-marshal-with-nested-data

Thank you very much!

**Comment by joshfriend** [comment]
_I'll copy-pasta my answer from your SO post here:_

[Here's an example in the docs of how to make a custom parser type.][custom-parser-type]

Basically, you define a function that:

* Takes the raw value of the argument pulled from the request
* Raises `ValueError` if parsing or validation fails
* Returns the argument if validation suceeds

Basic example related to your question:

```python
def pet_list_parser(pets):
    if type(pets) != list:
        raise ValueError('Expected a list!')

    # Do your validation of the pet objects here. For example:
    for pet in pets:
        if 'name' not in pet:
            raise ValueError('Pet name is required')

        # Also do any conversion of data types here
        pet['name'] = pet['name'].capitalize()

    return pets

parser = RequestParser()
parser.add_argument('pets', type=pet_list_parser)
```

As you might guess, this gets klunky and annoying rather quickly. The request parsing in Flask-RESTful isn't designed to handle nested data. It works very well for querystring arguments, headers, basic JSON, etc. and can be configured to handle nested data. However if you are going to do this a lot, save yourself some pain down the road and look into a marshalling library like [Marshmallow][marshmallow].

[custom-parser-type]: http://flask-restful.readthedocs.org/en/0.3.3/intermediate-usage.html#full-parameter-parsing-example
[marshmallow]: http://marshmallow.readthedocs.org/en/latest/
