### ISSUE TITLE
Not able to marshal result from literal sql

### ISSUE THREAD

**Issue by gverkes** [flask-restful/flask-restful#469]
I'm not able to marshal the result from a raw sql query (using from_statement), but the following works:
```Python
user = session.query("id", "name", "thenumber12").\
         from_statement(text("SELECT id, name, 12 AS"
                 "thenumber12 FROM users where name=:name")).\
                 params(name='ed').all()
print user.thenumber12 #prints 12
```
However when marshalling it doesn't detect this, for example it doesn't work when marshalling with the fields:
```
  offer_created_fields = { 
      'id': fields.Integer,
      'name': fields.String,
  }
```
So I have to manually make a dict to let the marshalling return anything.

**Comment by joshfriend** [comment]
That kind of query will return a list of [`KeyedTuple`s, which is a SQLAlchemy datastructure.](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html?highlight=keyedtuple#sqlalchemy.util.KeyedTuple) You will need to convert these to a `dict` first using `user._asdict()`.

I've run into this before myself, but haven't figured out a great way around it yet.

**Comment by NegativeDearc** [comment]
helpful!
