### ISSUE TITLE
Bad Requests always with POST/PUT method.

### ISSUE THREAD

**Issue by d555** [flask-restful/flask-restful#478]
Not matter what I tried. I'm receiving for every resource that I have in my application that `POST/PUT` method fail. `GET` method works fine.

```bash
HTTP/1.0 400 BAD REQUEST
Content-Type: application/json
Content-Length: 53
Server: Werkzeug/0.10.1 Python/2.7.8
Date: Sat, 11 Jul 2015 21:11:07 GMT

{
    "message": "Bad Request",
    "status": 400
}
```
I prepared the following environment for testing and for frustration. 
- server: `test.py`
```python
from flask import Flask, Blueprint
from flask.ext.script import Manager, Shell

app = Flask(__name__)

from apitest import api_bp
app.register_blueprint(api_bp)

manager = Manager(app)

if __name__ == '__main__':
    manager.run()
```
- resource: `apitest.py`
```python
from flask import Blueprint
from flask.ext.restful import Api, Resource

api_bp = Blueprint('api', __name__)
api = Api(api_bp)

class Test(Resource):

    def get(self):
        print 'GETTTTT'
        return

    def put(self):
        print 'PUTTTT' 
        return 

    def post(self):
        print 'POSTTT'
        return 

api.add_resource(Test, '/test')
```

As like in the documentation, the code above **works** perfectly:
```bash
curl -i http://127.0.0.1:5000/test -XPOST -d  ""
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 4
Server: Werkzeug/0.10.1 Python/2.7.8
Date: Sat, 11 Jul 2015 21:22:51 GMT

null%
```

But If I put the same code in my app in `app/api/v1/__init__.py` it always fails, not matters what I've tried, `POST` had never worked. In the console, by example, always print `GETT` with `GET` but with `POST`. The console never shows `POSTTT` from print. 

My last trie was to put the modify of `Resource` class in the code for see what's happening. And, I added a `print` line with something in the method `dispatch_request` from `Resource` class. So after this. I'm sure that when I request the respective `POST` to `Test`, the method `dispatch_request` never execute`. For `PUT` has the same behavior. But with `GET` always works fine.

I don't know how to proceed next, some help, I'll appreciate it so much.  :weary: :gun:

**Comment by justanr** [comment]
I have the feeling your production code is getting bad JSON (I've run into this issue when I type it out by hand).

**Comment by joshfriend** [comment]
Yes, that is my initial guess as well. An empty string is not valid JSON and will raise 400 Bad Request.

**Comment by d555** [comment]
No. Guys. I found the origin of the problem, but not the solution yet. I wake up this morning with the feeling was about some in the middle between  and I came up to review the initialization of the app. The error was caused by:

```python

from flask import Flask
...
from flask_wtf.csrf import CsrfProtect
...
csrf = CsrfProtect() #1
...

def create_app(config_name):
    app = Flask(__name__)
    ...
  csrf.init_app(app) #2
```

If I comment this line where `csrf` appears. Then, the `Bad Request` disappear and after that, all become normal.

**Comment by joshfriend** [comment]
Thanks for the update! I think your explanation here should be sufficient documentation wise.
