### ISSUE TITLE
Cut new release 

### ISSUE THREAD

**Issue by ihodes** [flask-restful/flask-restful#479]
It would be nice to have some of the recent changes (especially allowing users access to the settings to the JSON serialization). Thank you!

**Comment by joshfriend** [comment]
I'll try to get to it shortly

**Comment by ihodes** [comment]
We've a workaround for this, so this isn't causing causing us trouble. No rush or worries, and thanks for the library!

**Comment by joshfriend** [comment]
* [x] Update `setup.py` version
* [x] Update AUTHORS
* [x] Update CHANGES.md https://github.com/flask-restful/flask-restful/compare/0.3.3...0.3.4
* [x] Git tag new version
* [x] Upload to [PyPI](https://pypi.python.org/pypi/Flask-RESTful/0.3.4)
    * [x] `source`
    * [x] `wheel` :)
* [ ] Update RTD.org default version

**Comment by ihodes** [comment]
Awesome, thank you!
