### ISSUE TITLE
json-home

### ISSUE THREAD

**Issue by opyate** [flask-restful/flask-restful#482]
How about a [json-home](http://tools.ietf.org/html/draft-nottingham-json-home-03) plugin?
* configurable (on/off, black/whitelist)
* a re-hash of [other](http://flask.pocoo.org/snippets/108/) [ideas](https://flask-sitemap.readthedocs.org/en/latest/) to get started quickly.
* could be the basis for auto-generated API documentation

If I get enough :+1:, I'd like to give implementing this a shot.

**Comment by justanr** [comment]
json-home is basically a site map for JSON apis? That's pretty nifty, but it seems like something the end user should implement. Even though Flask-RESTful ships with a JSON implementation, it's easily extendable to include things like XML, CSV, etc.

There's also the issue of using multiple instances of `flask_restful.Api` that are registered on separate Blueprints (maybe for API versioning or hosting several APIs out of the same app).

On a more personal level, I'm not a fan of extensions that add or affect my routes like this. But that's just me.

**Comment by opyate** [comment]
> ... but it seems like something the end user should implement.

OK, I agree.
