### ISSUE TITLE
TypeError if HTTPException.description is not string

### ISSUE THREAD

**Issue by hai-ld** [flask-restful/flask-restful#486]
The change made in #438 and 1ccec7d369a29cabb1f75421b56ef9fed6b3847b alters the behaviour of `Api.handle_eror`, which now looks into `description` attribute of `HTTPException` object. However, Flask/Werkzeug doesn't seem to mention that `description` must be string, and in the case `description` is not string and is not JSON-serializable, flask-restful will throw `TypeError`. An example of such case is if `flask_restful.Resource` also use flask-principal, which raises `HTTPException` with `flask_principle.Permission` object as `description` (see [here](https://github.com/mattupstate/flask-principal/blob/70d9c3285a216e75e3eed4fc98444d50dbf3f607/flask_principal.py#L207)).

Currently, I'm fixing it by specifying a custom JSON serializer for `flask_principal.Permission`. Nevertheless, I'm asking that:
- Do you think flask-restful should handle such `TypeError` case?
- If not, is specifying a custom serializer the way to go, or we have to fix it upstream?

**Comment by joshfriend** [comment]
See discussion on #489 and chime in if you have any thoughts.
