### ISSUE TITLE
Create custom error message for 'choices' argument

### ISSUE THREAD

**Issue by aaronyan** [flask-restful/flask-restful#487]
Flask-restful will return an automatic error message when a provided value doesn’t fall in the range specified by the choices argument:

post_parser.add_argument(
    'user_priority', dest='user_priority',
    type=int, location='form',
    default=1, choices=range(5), help='The user\'s priority',
)

Is there a way to adjust the error message handled by flask-restful? I am looking to transform the current response:

{ "message": { "section": "foobar is not a valid choice" } }

to the following:

{ "message": { "section": "foobar is not a valid choice", "choices": [ "foo", "bar" ] } }

References: http://flask-restful.readthedocs.org/en/latest/intermediate-usage.html, http://flask-restful.readthedocs.org/en/latest/extending.html#custom-error-handlers

**Comment by heston** [comment]
While not exactly what you're asking for, this gets you a little closer: https://github.com/flask-restful/flask-restful/pull/518
