### ISSUE TITLE
Reqparse Boolean Arguments

### ISSUE THREAD

**Issue by iharsuvorau** [flask-restful/flask-restful#488]
When I add argument to a parser with `type=bool` and make a request with `localhost:5000/smth?attr=False` after `parser.parse_args()` I get `attr=True`. And only if I delete a mention of False from request `localhost:5000/smth` I get `attr=False`.

Why?

The only solution for me now is using `type=str` and compare an argument with a string `attr == 'False'`.

**Comment by joshfriend** [comment]
you can't use the python builtin type `bool` to parse strings:

```python
>>> bool('False')
True
>>> bool('True')
True
>>> bool('')
False
>>>
```
 
Use `inputs.boolean` from flask-restful instead.
