### ISSUE TITLE
how to put list data  and how to get raw data?

### ISSUE THREAD

**Issue by eromoe** [flask-restful/flask-restful#499]
I 'am new to flask and flask-restful,I have data like below:
```
{'settings': [{'proxy_on': False, 'max_recurrence': '0', 'domain': '00000', 'updatetime': 1441881193.521016, 'js_on': True}, {'proxy_on': False, 'max_recurrence': '1', 'domain': '11111', 'updatetime': 1441867467.8639057, 'js_on': True}, {'proxy_on': False, 'max_recurrence': '2', 'domain': '22222', 'updatetime': 1441904173.2352133, 'js_on': False}]}
```
I want to put the data to my mongodb, so I try flask-restful, but I found that 

1. parse wrong
```
setting_list_parser = reqparse.RequestParser()
setting_list_parser.add_argument('settings')

def put(self):
     args = setting_list_parser.parse_args()  # args 

#  args  = {'settings': u"{u'proxy_on': True, u'max_recurrence': u'0', u'domain': u'00000', u'updatetime': 1441924659.8950331, u'js_on': False}"}
```

then I try to get data from raw put data:

2.
```
def put(self, request):
TypeError: put() takes exactly 2 arguments (1 given)
```
3.
```
from flask import request
def put(self):
     settings = request.args.get('settings')  # settings is None
```

**Comment by joshfriend** [comment]
When you tried: 

```python
setting_list_parser.add_argument('settings')
```

You used the default parser argument type of string (but your data is JSON). `reqparse` doesn't really support parsing nested items or lists of things out of the box, so you would probably be better off using [`marshmallow`](https://github.com/marshmallow-code/flask-marshmallow).

If you don't need any sort of validation on your input data, You were getting close with your 3rd example. Use the `get_json()` method on the request object instead.
