### ISSUE TITLE
Use with mongodb database

### ISSUE THREAD

**Issue by scheung38** [flask-restful/flask-restful#501]
Can I use this with mongoDB or alternatively use my existing SQLite database to convert to mondodB?

**Comment by scheung38** [comment]
Typo I mean mongoDB

**Comment by svenstaro** [comment]
This doesn't interact with DBs on its own at all. It just helps you define a RESTful API.

**Comment by ueg1990** [comment]
Are you having any issues using mongodb with flask-restful? I was able to use it with pymongo

**Comment by scheung38** [comment]
Hi @ueg1990, Could you give example of usage? Is it just flask with pymongo? Because I also see mongo engine Thanks

**Comment by ueg1990** [comment]
here is a link to where i used pymongo with flask-restful. It may not be that easy to follow...let me know if i can help u in anyway: https://github.com/wearhacks/hackathon_hotline/blob/master/hotline/db/db_mongo.py
