### ISSUE TITLE
Issue in mocking flask_restful.reqparse.RequestParser for setting parse_args - 'RuntimeError: working outside of request context'

### ISSUE THREAD

**Issue by hussaintamboli** [flask-restful/flask-restful#503]
Hi,

I get an error when I try to mock `flask_restful.reqparse.RequestParser`

     RuntimeError: working outside of request context

On debugging I found that the exception is raised on [this line](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/reqparse.py#L291).

Code snippet for one of my GET API -

    @marshal_with(response_params)
    def get(self, filter_name=None):
        try:
            response = self.process_get_request(filter_name)
            return response
        except MyValidationError as err:
            abort(404, message=err)
        except ValueError as mistake:
            abort(400, message=mistake)

    def process_get_request(self, filter_name=None):
        params = parser_get_app_analytics.parse_args()
        page = params.get('page') or 1
        page = abs(int(page))
        user_id = params.get('user_id')
        if not user_id:
            raise ValueError("User id is empty")

        user = session.query(User).get(user_id)
        if not user:
            raise MyValidationError("User not found")
        # rest of my logic goes here

I want to test **process_get_request** method. As this method uses `parse_args` which are request args, I would need to mock it and set the request data. I have tried

    @mock.patch('flask_restful.reqparse.RequestParser', autospec=True)
    def test_process_get_request(self, parse_args_mock):
        args = parse_args_mock.return_value.parse_args.return_value.text = dict(page=None, user_id=None)
        with self.assertRaises(ValueError):
            self.job_response.process_get_request(args)

What's wrong? How do I correct my code? What's the correct way of testing such methods? 

Please help me out.

**Comment by joshfriend** [comment]
Theres a few things wrong here, firstly it looks like you mocked the whole class, not the method you wanted to test. So do this instead:

```python
@mock.patch('flask_restful.reqparse.RequestParser.parse_args')
def test_process_get_request(self, parse_args_mock):
    parse_args_mock.return_value = dict(page=None, user_id=None)
```

The `RuntimeError` is coming from you trying to use resources in your app that depend on the flask context. Fixing your mock might take care of that for you, but if it doesn't you can either mock whatever else depends on the app context or use the following in your test:

```python
with app.app_context():
    # Do things here
```

**Comment by hussaintamboli** [comment]
Thanks! My issue is fixed. Also, the `RuntimeError: working outside of request context` error is gone. And I didn't have to use app_context.
