### ISSUE TITLE
Best way to add custom headers for JSON API

### ISSUE THREAD

**Issue by Leo-G** [flask-restful/flask-restful#507]
I need to add the following content type to the headers  of requests
     Content-Type: application/vnd.api+json

I wanted to know the best to do this such that I do not have to define it for every  Resource class

**Comment by joshfriend** [comment]
[Define a new "representation" for your content type](http://flask-restful.readthedocs.org/en/0.3.4/extending.html?highlight=representation#content-negotiation)

**Comment by Leo-G** [comment]
Thank you let me  check.
