### ISSUE TITLE
Unicode message error

### ISSUE THREAD

**Issue by icersong** [flask-restful/flask-restful#508]
When use custom type function and raise error with unicode string, then it will raise "UnicodeEncodeError"

flask-restful 0.3.4

Code:

    def mytype(value):
           raise ValueError(u"If here is unicode string (e.g. chinese.中文).")
    parser = reqparse.RequestParser()
    parser.add_argument(name, type=mytype)

UnicodeEncodeError:

    File "/Users/apple/.virtualenvs/py2.6/lib/python2.6/site-packages/flask_restful/reqparse.py", line 138, in handle_validation_error
    error_msg = ' '.join([help_str, str(error)]) if help_str else str(error)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)

**Comment by joshfriend** [comment]
perhaps that line should use `six.text_type` instead of `str`?

**Comment by icersong** [comment]
that is ok, I test it success.

**Comment by joshfriend** [comment]
I think this was introduced with #431

**Comment by joshfriend** [comment]
Pretty sure #564 fixed this.
