### ISSUE TITLE
Bad Request on GET with header Content-Type

### ISSUE THREAD

**Issue by jbouzekri** [flask-restful/flask-restful#510]
I have a simple GET request on an endpoint returning a list of entity.

This query gives me back a 400 Bad request error : 

```
curl -s -D - http://localhost:5000/workdays -H 'Content-Type: application/json'
HTTP/1.1 400 BAD REQUEST
Content-Type: application/json
Content-Length: 98
Date: Wed, 30 Sep 2015 20:13:44 GMT

{
    "message": "The browser (or proxy) sent a request that this server could not understand."
}
```

If I remove the Content-Type header, there is no error. Is it not overkill to reject a GET request with a content type header ?

**Comment by joshfriend** [comment]
> Is it not overkill to reject a GET request with a content type header ?

I don't think so. You told the server to parse the request body as JSON, but the request body is not valid JSON. To illustrate:

```python
>>> import json
>>> json.loads("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josh/.pyenv/versions/2.7.10/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/josh/.pyenv/versions/2.7.10/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/josh/.pyenv/versions/2.7.10/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>
```

**Comment by jbouzekri** [comment]
I understand because of the implementation server side. But for the API users, they will have to customize their clients based on the type of query.

When using things like jquery or others, this is not very practical. I think that a ContentType in a GET query should not be parsed as it is not relevant.

**Comment by gcavalcante8808** [comment]
I'm receiving the same error when i try to put a test code to work:

    def test_create_new_page(self):
        header={ "Content-Type": "application/json"}
        data = {
            "name": "Unittest Page",
            "raw_content": "My Title\n=====",
        }
        response = self.client.post('/pages-list', data=data, headers=header)

        print(str(response.data))
        self.assertEqual(response.status_code, 201)

        # Try to submit the same data again, a 422 code is expected
        response = self.client.post('/pages-list', data=data, headers=header)
        self.assertEqual(response.status_code, 422)

I just receive a 400 http status If I specify the headers.

**Comment by bsacks99** [comment]
Has anyone found a workaround for this issue? We would like to be more forgiving for our API users. If someone leaves a content-type header in a GET request we do not want to fail the request outright.

**Comment by justanr** [comment]
Hm. On one hand, sending a Content-Type header with a GET (or HEAD or OPTIONS) is silly. On, the other, your service probably shouldn't blow up if it happens. I think ignoring a Content-Type header on a non-body request is the right way to go.

**Comment by bsacks99** [comment]
@justanr, I'm not sure I know how to do that in the Flask/flask-restful stack. Is there a workaround at this time?

**Comment by justanr** [comment]
You could probably register a handler that'll run before any Restful processing that'll check if the method is one of GET, HEAD, OPTIONS, DELETE (which *maybe* shouldn't have a body -- it's "undefined") and strip any present Content-Type headers.

**Comment by joshfriend** [comment]
I'm leaning towards the following:

* Don't remove `Content-Type` headers. [HTTP Spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html) never says that `Content-Type` must not be included on bodyless requests.
* Stop blowing up if header is provided :)

**Comment by bsacks99** [comment]
Thanks @justanr. I'll do that. I'll watch the change log, if you guys patch or fix that in a new release we'll try to upgrade.

**Comment by justanr** [comment]
@joshfriend Is this actually a Restful issue? If so, I'll try to whip up a PR this weekend. But I think the best work around is to strip the header until the issue is fixed. It's nasty and technically violates the spec, but it should work.

**Comment by bsacks99** [comment]
Just a note after further research:

We found that if the GET request does include a body the error is not raised. This behavior covers our requirements (implementing reporting API with large amount of filter data) and we believe is consistent with the HTTP spec. We also feel that the spec allows for the header on body-less requests, but we can easily accomplish this by filtering the header in a pre request hook. 

We'll still watch out for a patch and are happy to early test.

**Comment by joshfriend** [comment]
@justanr: yes, flask by itself allows that type of request.

**Comment by justanr** [comment]
@joshfriend I finally got a chance to start playing with this and I cannot reproduce with Python 2.7.6/3.4.3 Restful 0.3.5 and Flask 0.10.1

```python
from flask import Flask
from flask_restful import Resource, Api


app = Flask(__name__)
api = Api(app)


@app.route('/')
def good():
    return '{"status": "OK!"}'


class TestResource(Resource):
    def get(self):
        return {'status': "OK!"}


api.add_resource(TestResource, '/test')


if __name__ == "__main__":
    app.run(debug=True)
```

```python
curl -s -D - http://localhost:5000 -H 'Content-Type: application/json'
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 18
Server: Werkzeug/0.11.3 Python/3.4.3
Date: Fri, 08 Jan 2016 03:03:03 GMT

{"status": "OK!"}
```

```
curl -s -D - http://localhost:5000/test -H 'Content-Type: application/json'
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 24
Server: Werkzeug/0.11.3 Python/3.4.3
Date: Fri, 08 Jan 2016 03:03:28 GMT

{
    "status": "OK!"
}
```

**Comment by joshfriend** [comment]
Thats interesting, i know i have run into this myself many times when i forget to update header values in postman, but i am typically using a older version.

**Comment by joshfriend** [comment]
It's been a while since I looked at this, but the comment from @justanr seems to indicate that this is no longer an issue?

**Comment by phillip-martin** [comment]
Has anyone else experienced this since it was closed? I was able to reproduce this on a fresh install of Python 2.7.10 Restful 0.3.5 and Flask 0.10.1.

```python
from flask import Flask
from flask_restful import Resource, Api, reqparse


app = Flask(__name__)
api = Api(app)


@app.route('/')
def good():
    return '{"status": "OK!"}'


class TestResource(Resource):
    def get(self):
        return {'status': "OK!"}

@app.route('/parse')
def parse():
    parser = reqparse.RequestParser()
    parser.add_argument("place_holder", type=int, required=False)
    parser.parse_args()
    return '{"status": "OK!"}'


api.add_resource(TestResource, '/test')


if __name__ == "__main__":
    app.run(debug=True)
```

Testing:

```
curl -s -D - http://localhost:5000 -H 'Content-Type: application/json'
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 17
Server: Werkzeug/0.11.10 Python/2.7.10
Date: Thu, 28 Jul 2016 20:14:01 GMT

{"status": "OK!"}
```
```
curl -s -D - http://localhost:5000/test -H 'Content-Type: application/json'
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 24
Server: Werkzeug/0.11.10 Python/2.7.10
Date: Thu, 28 Jul 2016 20:14:40 GMT

{
    "status": "OK!"
}
```

```
curl -s -D - http://localhost:5000/parse -H 'Content-Type: application/json'
HTTP/1.0 400 BAD REQUEST
Content-Type: text/html
Content-Length: 177
Server: Werkzeug/0.11.10 Python/2.7.10
Date: Thu, 28 Jul 2016 20:15:05 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Failed to decode JSON object: No JSON object could be decoded</p>
```

It all goes wrong on this line - `parser.parse_args()`. #556 is the same issue.
Just to be safe I attempted the same with the latest master. Same thing.

**Comment by phillip-martin** [comment]
Admittedly, if `location` is set to `'args'` the request doesn't blow up:

```python
...
    parser = reqparse.RequestParser()
    parser.add_argument("place_holder", type=int, required=False, location='args')
    parser.parse_args()
...
```

I will use this as a short term fix. I've been thinking about moving the parsing over to [webargs](https://github.com/sloria/webargs) anyways.

**Comment by justanr** [comment]
In that case, I'd completely expect Restful to pitch a fit because there isn't a JSON body included with the GET request (and there never should be either). So, the issue isn't really sending a GET with a Content-Type, it's attempting to parse an non-existent content body.

I ran into this with requests when working on an API at work, ultimately it comes down to the fact that JSON libraries in Python don't seem to be okay with `''` (meaning, no content) as a JSON body. I'm actually unsure if `''` is considered valid JSON or not (I'd have to dig through the RFC to be 100%).

**Comment by phillip-martin** [comment]
@justanr, I agree with that. the `Content-Type: application/json` is a only case that triggers it, but attempting to parse a non-existent content body shouldn't happen.

**Comment by nesbtesh** [comment]
I get this error when the body is relatively large

**Comment by keymandll** [comment]
I get the same error when I do a delete method with content-type set to application/json but empty request body. The need to provide anything in the body does not seem logical, playing with removing content-type either client-side or server-side is not too nice.
As the content-type basically tells how to interpret/handle the body, for me the logical approach is if there is no body, then there is nothing to interpret/handle.

**Comment by songxiaowei112** [comment]
Me too

**Comment by boazin** [comment]
@joshfriend - I see your point when using strict=True means you validate that there is a valid JSON in the body but I wanted to raise the following:
Let's assume my POST request has params only in 'args' - location JSON shouldn't be in the game...

The problem is in https://github.com/flask-restful/flask-restful/blob/master/flask_restful/reqparse.py#L302

That creates a default argument ('' is json, values)

Not sure what is the intent of this specific code but I was wondering if it can be generalized/have a workaround...
(will be happy to PR with some pointers)

**Comment by vrde** [comment]
IMO since `GET`s should not have a body, the header `Content-Type` can be safely ignored.

I've [created a middleware](https://github.com/bigchaindb/bigchaindb/blob/e272a4e0d1cd686b17f1ae5e84b9a1d615150560/bigchaindb/web/strip_content_type_middleware.py) to do so:
```python
import logging
logger = logging.getLogger(__name__)

class StripContentTypeMiddleware:
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        if environ['REQUEST_METHOD'] == 'GET':
            try:
                del environ['CONTENT_TYPE']
            except KeyError:
                pass
            else:
                logger.debug('Remove header "Content-Type" from GET request')
        return self.app(environ, start_response)
```

**Comment by derekhe** [comment]
Still have this issue and I request to open this and fix this.

**Comment by vald-phoenix** [comment]
@vrde for GET it works perfectly, but the problem will appear when you need to send a file to an endpoint by means, for example, POST. I use `FileStorage` from `werkzeug` with `RequestParser` from `flask_restful` for validation purposes.
When I don't specify content-type and simply send a file by means Postman I get something like this in my headers from the `environ` argument.
```
'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryAQzWisQwQ6Pyo75Z'
```
And such content types in `FileStorage`.
```
Content-Disposition: form-data; name="file_obj"; filename="test.csv"
Content-Type: text/csv
```
When you perform drop of `CONTENT_TYPE` from the `environ` argument, it always happens bad request response. Any ideas?

**Comment by vrde** [comment]
@vald-phoenix I'm not sure I can help you here. Since the problem is related to `POST`, you might want to open a new issue for that.

**Comment by dkobia** [comment]
@phillip-martin `location='args'` seems to be the solution.

**Comment by WhizpoolMobileTeam** [comment]
All was working fine for previous 3 months. but suddenly we are facing issue in android app only while others(ios & web) are still going fine. i am getting response code 411 now on android even though i am sending content-length previously and now too.....


i am finding solutions for 3 days but could not able till now......

Following attachment is the function call

![image](https://user-images.githubusercontent.com/53824243/65301343-78cd3a00-db90-11e9-908e-4e9a1a101d3e.png)


and following is the other class where we make connction

![image](https://user-images.githubusercontent.com/53824243/65301383-ac0fc900-db90-11e9-98c8-a6a6f57cc180.png)

**Comment by Alvaro-Campesino** [comment]
This is still an issue in 0.3.7 
Should be re-opened

**Comment by duaneenterprises** [comment]
i concur.  still an issue
