### ISSUE TITLE
RequestParser errors deviate from documentation

### ISSUE THREAD

**Issue by heston** [flask-restful/flask-restful#514]
The docs for RequestParser state:

> If you specify the `help` value, it will be rendered as the error message when a type error is raised while parsing it.

So, one would expect this...

```python
parser = RequestParser()
parser.add_argument("id", type=regex(r"^[\w]{8}$", help="Please provide a valid ID")
```

...to generate an error response like this:

```python
{
    "message":  {
        "id": "Please provide a valid ID"
    }
}
```

In practice, the `help` value is [prepended](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/reqparse.py#L138) to the actual type error:

```python
{
    "message":  {
        "id": '(Please provide a valid ID)  Value does not match pattern: "^[\w]{8}$"'
    }
}
```

This error is not very user-friendly, and prevents the developer from completely customizing the error message.

#### Possible solutions

1. Update docs to match actual behavior.
2. Update code to match docs.
3. Allow `help` to specify an optional string interpolation token that will get replaced with the actual error string (e.g. `help="Please provide a valid id: {error_message}"`).

**Comment by joshfriend** [comment]
I like option 3! Would that be your preferred solution as well?

**Comment by freddrake** [comment]
There's another possibility that I've used in a derivative ``RequestParser``:

Provide both the error message and the help message, allowing the UI to consume them as it sees fit.  So the example response will look more like this:

~~~~~
{
    "message":  {
        "id": {
            "error": "Value does not match pattern: '^[\w]{8}$'",
            "help": "Please provide a valid ID"
        }
    }
}
~~~~~

**Comment by heston** [comment]
@joshfriend You read my mind, I was leaning toward option 3.

@freddrake That's interesting. It's certainly the most flexible. I wonder if the added complexity is needed, though. Isn't the whole point of `help` to provide a custom error message? If the developer is taking time to provide a custom message, surely they could format it how they see fit? Also, I think providing multiple errors (potentially) for each field could be confusing to consumers of the resource (although, as you mentioned, providing it under a new key makes it opt-in).

**Comment by freddrake** [comment]
I don't speak for the designers of the API.

Since the help message is associated with the argument being extracted, it's hard to make it an actionable error message; it can advise about what the value *should* be, but can't really say what is *wrong* with the value provided.

This distinction suggests to me that both the error message and the help are useful, but will often want different presentation.

It would be interesting to have a way for the UI to request just the help messages, but that should definitely be out of scope for this issue.
