### ISSUE TITLE
How to call Api.make_response instead of Flask make_response ?

### ISSUE THREAD

**Issue by asmodehn** [flask-restful/flask-restful#515]
I just recently noticed that my basic view class, simplified here, wasn't setting the content-type correctly : 

```python
class BackEnd(restful.Resource): 
    def __init__(self, logger):
        super(BackEnd, self).__init__()
        self.logger = logger

    def get(self, resource_name):
        
            #
            # HERE we get msg from external python code
            #
            output_data = json.dumps(msg)
            return make_response(output_data, 200)
```

Somehow I was expecting it to be handled by flask-restful, but it seems I am calling Flask version of make_response ( through flask/helpers.py apparently ), which doesn't set the content-type by itself.

Is my expectation wrong and should I pass the instantiated API here to call `api.make_response(output_data, 200)` ? Or a simpler way ?
Or is my expectation right, and something else is broken in my setup ?

**Comment by joshfriend** [comment]
Flask-RESTful will [call `make_response` for you](https://github.com/flask-restful/flask-restful/blob/0e443078b2145017cd2aaadb003791ebd71cc68b/flask_restful/__init__.py#L474). If you return a `Response` object from your endpoint, no further processing happens. In your case, why not just do this:

```python
def get(self, resource_name):
    # stuff...
    return msg, 200
```
