### ISSUE TITLE
Enable custom headers when handling exceptions

### ISSUE THREAD

**Issue by nharraud** [flask-restful/flask-restful#522]
The current error handler sets an empty header instead of using `HTTPException.get_headers()`:
https://github.com/flask-restful/flask-restful/blob/bfef0b09b29992487241229cebf21c41180922d9/flask_restful/__init__.py#L301

It makes it impossible to create custom exceptions providing headers.

As an example, here is my use-case. I wanted to create a specific exception for 304 status code. The *If-None-Match* section of the [rfc2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) says:
```
[...] if the request method was GET or HEAD, the server SHOULD respond with a 304
(Not Modified) response, including the cache-related header fields (particularly ETag)
of one of the entities that matched.
```
Thus I would need to specify the ETag in the headers.

**Comment by joshfriend** [comment]
I'm not sure that raising an exception for a non-error condition would be the right way to handle 3xx responses, but you have a good point. The error handler should respect the `get_headers` method of the HTTP Exception that was raised.

Would you mind making a pull request for this?

Related: #491 #450 #455

**Comment by nharraud** [comment]
Hi @joshfriend. It might not be the best way to handle `304` status you are right. After reading this [snippet from flask](http://flask.pocoo.org/snippets/95/) I just thought that it would be more convenient as I want to factorize the ETag handling code in a function. It will then be used by every get/post/put/... method.

The pull pull request's additional test contains an example of what I want to achieve.
