### ISSUE TITLE
Python 2.6 Doesn't support '{}'.format()

### ISSUE THREAD

**Issue by rgant** [flask-restful/flask-restful#526]
Unfortunately I am stuck using python 2.6, however the inputs.py validators use a feature that is only available in python 2.7:

> Changed in version 2.7: The positional argument specifiers can be omitted, so '{} {}' is equivalent to '{0} {1}'. http://stackoverflow.com/a/8498327

Ideally you could replace the instances of '{}' on format strings with '{0}'. Although I'd be just as happy if you removed python 2.6 from your setup.py.

**Comment by joshfriend** [comment]
I fixed all the instances of this in the library code. Some of the examples in the docs use it as well, but I figured there is no point bothering with them.

**Comment by rgant** [comment]
You're awesome. Thanks so much!
