### ISSUE TITLE
return html in flask-restful

### ISSUE THREAD

**Issue by ZimmerHao** [flask-restful/flask-restful#529]
how can i return html directly in flask-restful. For example, my index.html is in /xxx/index.html, and how can i make a response to return the html directly not use render_template.

**Comment by justanr** [comment]
There's a method `Api.representation` that you'll want to look into. However, you'll need some way of mapping routes to templates. I'd recommend using `flask.request.endpoint` which tells you where the request was routed to. You could do something as simple as a dictionary that maps these endpoints to templates, maybe something like:

```python
_endpoint_templates = {
    'main.index': 'index.html',
    'user.profile': 'profile.html',
    'default': 'default.html'
}

@api.representation('text/html')
def render_endpoint_template(data, code, headers):
    template = _endpoint_templates.get(request.endpoint, _endpoint_templates['default'])
    return render_template(template, **data), code, headers
```

Pretty low tech, but I'd imagine it'd go a fair distance. You'd probably want some way of automatically associating templates with endpoints so you're not constantly having to update the dictionary.

**Comment by joshfriend** [comment]
@justanr's solution would probably work (though it's probably not very robust). I think you could also return a `Response` object from the endpoint with the HTML already rendered and Flask-RESTful won't try to serialize it to JSON.

Either way, Flask-RESTful isn't the tool you want to use for rendering webpages.

**Comment by justanr** [comment]
I could see a use case for returning HTML or JSON or something else depending on the `Accept` header sent in. Think using reddit's `.json` URLs except responding to headers. Though you're right, a more robust solution would be needed.
