### ISSUE TITLE
Extend Method Decorators to apply to specific request methods

### ISSUE THREAD

**Issue by justanr** [flask-restful/flask-restful#530]
Instead of imitating `flask.view.View` with the method decorator, would it make more sense to be able to apply specific decorators to specific methods? For example, it might look like:

``` python
class Resource(MethodView):
    ...
    resource_decorators = {}

    def dispatch_request(self, *args, **kwargs):
        ...
        for decorator in self.resource_decorators.get(request.method.lower(), []):
            meth = decorator(meth)
```

Then you can choose to decorate every request through the regular `View.decorators` attribute, and selectively decorate different HTTP Requests through this. Maybe cache every `get` or restrict access for `delete/patch/post/put`.

The biggest con I can think of is that this would be a backwards breaking change.

**Comment by joshfriend** [comment]
How would this be different than the following?

```python
class Example(Resource):
    @login_required
    def get(self):
        return "Hello, World!"
```

**Comment by justanr** [comment]
It'd allow applying the decorators at dispatch time, rather than all the time as that method would be, similar to how it's done now. Makes testing easier, you'd be able to test *just* `Example.get` rather than testing `login_requried(Example.get)`.

Currently, Restful's implementation is the same as the regular `View` in Flask, just applied at a different time in dispatch. `View` applies all the decorators as part of the `View.as_view` and Restful's are applied when `Resource.dispatch_request` is called.

Rather than having a redundant feature, I think it'd be nice to use it for a slightly different use.

**Comment by joshfriend** [comment]
Ah, that makes sense. Wouldn't have to be a breaking change though, you could check when applying the decorators to the methods if the `decorators` property is a `list` or a `dict` and act accordingly.

**Comment by justanr** [comment]
Closing as the PR was merged.
