### ISSUE TITLE
Missing GET treated differently than missing POST

### ISSUE THREAD

**Issue by rbpasker** [flask-restful/flask-restful#531]
I've just started a Resource, and the class currently empty. When I try a GET, i get a 500 error, but when I try a POST, i get a 405. They should both be 405s.

![image](https://cloud.githubusercontent.com/assets/87866/11169539/b38aaf44-8b88-11e5-8f97-51b64a855be0.png)

![image](https://cloud.githubusercontent.com/assets/87866/11169537/a25e0a9a-8b88-11e5-9146-75aa471a57a6.png)

**Comment by joshfriend** [comment]
> the class currently empty.

What would be the use case for this scenario?

The exact same thing happens with plain `MethodViews` too:

```python
from flask import Flask
from flask.views import MethodView
from flask_restful import Api, Resource

app = Flask(__name__)
api = Api(app)

@api.resource('/resource')
class Example(Resource):
    pass

class Example2(MethodView):
    pass

app.add_url_rule('/methodview', view_func=Example2.as_view('methodview'))

app.run(port=5000, debug=True)
```

```
$ http :5000/resource
HTTP/1.0 500 INTERNAL SERVER ERROR
$ http :5000/methodview
HTTP/1.0 500 INTERNAL SERVER ERROR
$ http post :5000/resource
HTTP/1.0 405 METHOD NOT ALLOWED
$ http post :5000/methodview
HTTP/1.0 405 METHOD NOT ALLOWED
```

In the future, please try to include stacktraces from the console and other relevant info as text instead of screenshots. The ones you included are a bit difficult to read because they are so large.

**Comment by rbpasker** [comment]
on an empty class OPTIONS returns 200, GET returns 500, and everything else returns 405.

by adding a put(), the  GET magically goes from being a 500 to a 405

````
Traceback (most recent call last):
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/flask_restful/__init__.py", line 576, in dispatch_request
    assert meth is not None, 'Unimplemented method %r' % request.method
AssertionError: Unimplemented method 'GET'
````

**Comment by italomaia** [comment]
Any cons for changing GET's default behavior? According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6 GET if GET is not implemented/allowed, a 405 should be returned with the appropriate headers. Seems pretty doable.

**Comment by freddrake** [comment]
I ended up adding a resource class to my app that handles a missing get as a 405, regardless of the presence of other methods.  Making it just a little special with the 500 doesn't make much sense to me.

For an app with resources at /somepath/(id), but for which there's no response at /somepath, it seems nicer for /somepath to generate 405s instead of 404s is just a bit cleaner (perhaps a bit of flakiness on my part?).  But it requires registering an otherwise "empty" resource class.

(Yes, I could construct some response for /somepath, but that seems pretty arbitrary as well.)

**Comment by rbpasker** [comment]
just closed? no commit?

**Comment by freddrake** [comment]
Interesting resolution for the issue.

Given the deprecation of reqparse and having to work around little stuff like this, I'm not sure flask-restful actually adds much aside from method-based dispatch for my projects. Might be time to change things out for me.

**Comment by rbpasker** [comment]
what resolution? it was just closed. maybe that's what you mean by 'intersting'?

**Comment by freddrake** [comment]
That's exactly what I find interesting.  Not satisfactory, but interesting that this response is considered satisfactory to the maintainers.

**Comment by joshfriend** [comment]
Perhaps it wasn't clear enough in my previous comment that this behavior is inherited from Flask itself (`Resource` is a subclass of `flask.views.MethodView`). Therefore I don't think it is appropriate to fix it in Flask-RESTful. If this behavior actually causes issues for your applications, you should raise it upstream in the Flask project.

I had also asked if there were any practical scenarios where someone would want to use an empty `Resource` that had no methods defined, but received no response. A resource that supports only the OPTIONS method seems rather useless, so I'm not sure why it would even be added to the API.

I'm sorry you weren't happy with the resolution, I hope this explains it better.

You can also subclass `Resource` yourself to define `get` which raises `405 METHOD NOT ALLOWED`:

```python
class Resource(flask_restful.Resource):
    def get(self, *args, **kwargs):
        abort(405)
```

**Comment by freddrake** [comment]
Which is essentially what I've done, as described (perhaps not clearly) in my comment on 8 Feb 2016.

**Comment by justanr** [comment]
@freddrake This is the relevant "buggy" code:

flask.view.MethodView

```python
    def dispatch_request(self, *args, **kwargs):
        meth = getattr(self, request.method.lower(), None)
        # If the request method is HEAD and we don't have a handler for it
        # retry with GET.
        if meth is None and request.method == 'HEAD':
            meth = getattr(self, 'get', None)
        assert meth is not None, 'Unimplemented method %r' % request.method
        return meth(*args, **kwargs)
```
