### ISSUE TITLE
Unmarshaling

### ISSUE THREAD

**Issue by alapidas** [flask-restful/flask-restful#550]
I love the marshaling that `flask-restful` takes care of, but it doesn't look like there's an equivalent `unmarshal` feature.  Am I missing it by chance?  If not, it would be great to see that as a feature.

**Comment by joshfriend** [comment]
both [basic deserialization/request parsing](http://flask-restful.readthedocs.org/en/0.3.5/reqparse.html) and [serializing](http://flask-restful.readthedocs.org/en/0.3.5/fields.html) are already supported

**Comment by alapidas** [comment]
I was looking more for full object deserialization, similar to what the marshaling does (which is great)

**Comment by joshfriend** [comment]
Use [marshmallow](marshmallow.readthedocs.org). It should have all the features you want and more.

**Comment by alapidas** [comment]
Great suggestion - thanks.
