### ISSUE TITLE
The best way to dynamically remove endpoints and resources from a flask-restful app.

### ISSUE THREAD

**Issue by o1lo01ol1o** [flask-restful/flask-restful#551]
As asked [here](http://stackoverflow.com/questions/34443768/how-to-dynamically-remove-a-resource-and-route-from-a-flask-restful-app), what's the best way to remove a given endpoint and resource from a flask-restful app dynamically?

**Comment by justanr** [comment]
What's the usecase? It sounds like you're trying to do something but all you have is a mininuke.

**Comment by o1lo01ol1o** [comment]
I have an app that allows for (sometimes very large) objects (cpu, gpu) to be de-serialized and passed with resource classes to the provided endpoints.  When a user is finished with a given object, I need to do some cleanup.  I can remove the references to to the objects themselves, but I would also like to remove the endpoint and whatever else will be looking for it since it is conceivable that a user might want to run another analysis with the same or a different object (and thus, resource) from the same endpoint.  Does that make sense?

**Comment by justanr** [comment]
I'm not sure I understand how removing the end point helps with that. Moreover, I don't think Flask reacts kindly to removing routes (I've never tried, so I don't personally know).

A resource class represents an end point like `my site.com/api/whatever` that you send HTTP messages to.

And the way Flask handles class based views is to wrap them in a function that instantiates them and then calls dispatch_method. At the end of the request-response *should* be garbage collected, as it loses all references (unless the object registers itself somewhere - don't do that, BTW).

It sounds what you need is out of band processing ala Celery. A request to handle a GPU is sent and the request is stuffed into a messaging queue for Celery to pick up. When that's down, maybe Celery does something to notify whoever.

**Comment by o1lo01ol1o** [comment]
I understand, thanks.  Currently Celery is overkill for this task but is probably something I'll look into in the future.  In the meantime, do you know if there's a way to tell flask to "overwrite" whatever is associated with an endpoint if a new resource is registered to an existing endpoint?

**Comment by justanr** [comment]
I'm still not sure why you believe that's needed. Flask doesn't support adding new routes after the first request has been served. If you're really intrepid, you can do it by modifying the dictionary that holds the view functions, but that's really unsafe to do without locking grossness.

I think I'm misunderstanding why you feel the need for this. Do you have some sample code I could see?

**Comment by o1lo01ol1o** [comment]
> Flask doesn't support adding new routes after the first request has been served.

That surprises, me I've so far had no issues adding new endpoints the the app at any time.  I can confirm this though I can't post the code.  The below maybe gives an idea, though it's obviously untested.

In the example below, a user might need a given meat recipe to be served for some time and then she might need to alter the recipe and update the existing endpoint with the new meat.  She would need it to be the same address as the sandwich guy is outside the scope of this ecosystem and might only know one place to to get the meat he needs for a given order.  So if I can't remove the endpoint or associate it with a new resource, I would need to at least mark is as inactive and get the request to the new location of the meat.  Does this make sense?  Is there a much simpler design for this use-case that I'm missing?

```python
from flask import Flask
from flask_restful import Resource, Api

app = Flask(__name__)
api = Api(app)

FRIDGE = {'meats': [],
          'condiments': [],
          'cheeses': []}

class Meat(Resource):
    def __init__(self, twelve_gb_meat_model=None, two_gb_mayo=None, **kwargs):
        super(Meat, self).__init__(**kwargs)
        self.models = twelve_gb_meat_model, two_gb_mayo

    def post(self, args):
        return self.mix_n_serve_json()

class Cheese(Resource):
    def __init__(self, six_gb_fermenting_cheese=None, **kwargs):
        super(Cheese, self).__init__(**kwargs)
        self.models = six_gb_fermenting_cheese

    def post(self, args):
        return self.slice_n_serve_json()

def make_serving_station(api, url, uid, cheese_idx, meat_idx, condiment_idx):

    api.add_resource(Meat, url + uid + "/MeatServer/",
                     resource_class_kwargs={ 'twelve_gb_meat_model': FRIDGE['meats'][meat_idx],
                                             'two_gb_mayo': FRIDGE['meats'][condiment_idx],
                                             })

    api.add_resource(Cheese, url + uid +  "/CheeseServer/",
                     resource_class_kwargs={ 'six_gb_fermenting_cheese': FRIDGE['cheeses'][cheese_idx]
                                             })
    return api


@app.route("/publish_server/", methods= ['get', 'post'])
def publish_server():
    if 'post' in request.method:
        url = request.data['url']
        usr = request.data['usr']
        idxs = request.data['idxs']
        make_serving_station(api, url, usr, *idxs)
```

**Comment by justanr** [comment]
Why not determine which suppliers to use at run time rather than when you register the route? That seems to be your biggest problem right there.

Instead of how you're doing it in that example, make part of the URL a variable: `/MeatServer/<uid:int>`

And then have this:

```python
class Meat(Resource):
    def __init__(self, meat_servers):
        self._servers = meat_servers

     def post(self, uid):
         self.acquire_server(uid)
         return self.mix_n_serve()
```

Meat::acquire_server could do whatever it needed to either get the appropriate supplier (in this case, a list index look up) or raise some error (NoServersFree sounds like a good name).

No need to dynamically register routes or any funny business like that.

**Comment by o1lo01ol1o** [comment]
Yes, you're right, that does make more sense.  I had been unreasonably wedded to dynamically configured routes and environments, but that's clearly not going to be worth it on the flask level.  Thanks for the help!
