### ISSUE TITLE
Different behavior when type=list in add_argument [Breaking Change]

### ISSUE THREAD

**Issue by sibeliusseraphini** [flask-restful/flask-restful#555]
I've noticed that when you don't set a location and have a argument with type list, the behavior os parsing them is different than when I set up the location='json'

Example:
```
parse = reqparse.RequestParser()
parse.add_argument('arg1', type=list)
parse.add_argument('arg2', type=list, location='json')
args = parse.parse_args()
```

When a have a POST using the Content-Type = application/json like this:
```
{"arg1": [{"id": "123", "name": "testing"}], "arg2": [{"id": "123", "name": "testing"}]}
```

I have this result:
```
args['arg1'] equals ["id", "name"]
args['arg2'] equals [{"id": "123", "name": "testing"}]
```

**Comment by sibeliusseraphini** [comment]
This wasn't happening on Flask-RESTful 0.2.12

**Comment by sibeliusseraphini** [comment]
this should be consider a breaking change if the behavior doesn't work like before

**Comment by joshfriend** [comment]
This is probably related to #380. I was unable to find a good solution for this and the PR I did submit to Werkzeug was declined. Due to #335 I don't feel that it is worth the effort to chase this down further.
