### ISSUE TITLE
Adding callables to marshall

### ISSUE THREAD

**Issue by AbdealiJK** [flask-restful/flask-restful#557]
I wanted to make a field which creates a marshall using a function instead of an attribute.

So, I tried:

    pub_fields = {"id": fields.String, "token" : fields.String(attribute='get_auth_token')}

But that didn't work. it gave out:
```
{
    "id": "568672ca277e9067c6c3594e",
    "token": "<bound method User.get_auth_token of <User: user1>>"
}
```

It would be great if you could check whether the attribute is callable and call it (if that works out?) OR If there is another argument to fields.String (and other fields also?) like `callable`, similar to `attribute`

**Comment by joshfriend** [comment]
Try passing a callable to the `attribute` property:

http://flask-restful.readthedocs.org/en/0.3.5/fields.html#renaming-attributes

It's a good idea for an improvement though.

**Comment by joshfriend** [comment]
Marshmallow has this feature, I'd suggest using that instead. (seed #335)
