### ISSUE TITLE
What does the `operators` field in `Argument` do?

### ISSUE THREAD

**Issue by ParthGandhi** [flask-restful/flask-restful#560]
I'm referring to: https://flask-restful-cn.readthedocs.org/en/0.3.4/api.html#reqparse.Argument
I looked over the code, and can't seem to figure out what it does/when it would be used.

**Comment by joshfriend** [comment]
I'm honestly not sure. It was part of the [first commit](https://github.com/flask-restful/flask-restful/commit/a4465e3e9cc4c30e7f53e0b908f734a42ed32da4) and hasn't been changed yet.
