### ISSUE TITLE
Split flask-restful: flask-reqparse, flask-marshal

### ISSUE THREAD

**Issue by fernandojunior** [flask-restful/flask-restful#562]
What do you think about to split Flask-RESTful in more 2 pypi packages (flask-reqparse, flask-marshal). This way, other non-rest projects can use those tools?

**Comment by echoyuanliang** [comment]
I think it's a good idea, I have already used the reqparse and marshal in non-rest projects  for some days

**Comment by italomaia** [comment]
"request parsing" is deprecated, as seem here http://flask-restful.readthedocs.org/en/0.3.5/reqparse.html There are other libraries for the job.

**Comment by fernandojunior** [comment]
Hum, OK.
I did not notice it. 
Ty.
