### ISSUE TITLE
Omitting or including a field with marshal

### ISSUE THREAD

**Issue by santtu** [flask-restful/flask-restful#566]
I have a situation where output of a resource with `marshal` may or may not contain certain fields. So far this has been handled with a pattern like:

```python
def marshal_with_maybe(fields_1, fields_2):
   ...
   # in wrapper def
   if obj.is_good:
     fields = fields_1
   else:
     fields = fields_2
   return marshal(obj, fields)
```
This is a lot of work to omit or include a few fields in the response.

I was thinking that it would be cool to be able to include a **condition** for fields to determine whether it is included or omitted. For example:

```python
fields = {
    # this would be emitted only if `maybe.is_good` is true
    'maybe': fields.Nested({ .... }, omit=lambda value: not value.is_good),

    # does not make much sense, but follows same logic as `attribute`
    'never': fields.String("hello", omit=True)  
}
```

An alternative to a new field for field formatters would be that if `attribute` is callable, it could return a special value to omit the field, or throw an `FieldOmitted` exception.

This would be quite a big change so for now **I am looking for opinions and comments on this**. Maybe also someone has already found a nice way to get conditional fields in current Flask-Restful version?

(A bit of background: There are users of the API, class A and B. Both have an attribute which for class A users is implicit and fixed and makes no sense to show to class A users -- actually given the field, it is actually preferred to **not** show it to class A users. For class B users the field is explicit, modifiable and class B users need to know its value to be able to use the API to its full power.)

**Comment by atlithorn** [comment]
+1 for this
Only problem is this will create an extra innermost loop in ```marshal``` for *all* calls (at least afaics)
We have solved it in the past by filtering on ```None``` after ```marshal``` when required.

**Comment by smaye81** [comment]
I have this same issue, so this is a big +1 for me also.

What about a new type of field where you pass it a type and an optional lambda to determine the field's inclusion.  If no lambda is given, field's inclusion is based on it existing in the object being marshalled

```
fields = {
    # checks for existence before marshalling
    'maybe': fields.Optional(fields.String),

    # checks for validity using the passed lambda
    'maybe_custom': fields.Optional(fields.String, lambda value: not value.is_good)
}
```

**Comment by santtu** [comment]
@smaye81: As a clarification it doesn't much matter whether there is explicit `fields.Optional` or an `omit` flag for all fields as the core change needs to occur within the `marshal` method.

I do think that *if* done, using a signal with `fields.Optional` would be cleaner as it would not tie the field omit decision to any particular flag field or method. (Try-expect in Python is optimised to handle the no-exceptions-thrown case with minimum overhead, so using exceptions would probably be more efficient than explicit flag or field check, since omitting a field is less likely than including a field.)

I think the code relevant to this question is at https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L638. @atlithorn I believe is correct that it is difficult to add a test to include or omit a field without adding wrapping or an extra loop. 

OTOH adding code itself shouldn't be the issue, but whether it affects the performance of the loop significantly or not. And that's of course only if this really is considered performance critical (remember that marshalling is done at the *end* of request processing which is likely to be several magnitudes more work than marshalling itself.)

The most recent version of omitting fields I've used uses a `marshal_maybe` decorator that makes a pass over the fields, removing any that are conditionally omitted. Unfortunately it also needs to re-implement a lot of `marshal` *and* `marshal_with`'s functionality (envelope handling, handling return tuples, list vs. scalar and so on) which is just not ... clean.

I could look more into this and make a pull request, but before that I'd like to get @joshfriend's opinion whether this kind of feature could potentially be included in flask-restful at all.

**Comment by joshfriend** [comment]
I think marshmallow is a better solution for parsing/marshalling data. There's more discussion over on #335. The tl;dr is that I don't more major features to be added reqparse.
