### ISSUE TITLE
Reqparse headers lower case values.

### ISSUE THREAD

**Issue by Jonovono** [flask-restful/flask-restful#572]
Hi. When I do something like this:

    parser.add_argument('os_version', type=str, required=True, location='headers', default='ios')

Even if I include os_version in the header it does not seem to work.

But if I change it to:

    parser.add_argument('Os-Version', type=str, required=True, location='headers', default='ios')

it will work. Is there a reason it can't support the lower case underscore way? Thanks.

**Comment by joshfriend** [comment]
`-` and `_` are not upper/lower case versions of each other.

```python
>>> '-'.upper()
'-'
>>> '_'.upper()
'_'
```
