### ISSUE TITLE
 for database models defined using SQLAlchemy (or Flask-SQLAlchemy) ？

### ISSUE THREAD

**Issue by iloveyo123u1** [flask-restful/flask-restful#574]
hi,there

maybe we need **marshal_with_model**

can you : +1: 
Flask-restful  provides simple generation of ReSTful APIs for database models defined using SQLAlchemy (or Flask-SQLAlchemy).  ??

like django-rest-framework 

like this:
https://github.com/anjianshi/flask-restful-extend#marshal_with_model

----------------------------------------------------------------------------------------------
```
class MyModel(db.Model):
    __tablename__ = 'tasks'
    uid = db.Column(db.Integer, primary_key=True)
    create_date = db.Column(db.String(30))
    description = db.Column(db.String(200))
    done = db.Column(db.Integer)
    title = db.Column(db.String(50))

    def __init__(self, create_date, description, done, title):
        self.create_date = create_date
        self.description = description
        self.done = done
        self.title = title

class MyRoutes(Resource):
        # With `marshal_with_model`, you can return an model instance or model query
        # in view function directly.
        @marshal_with_model(MyModel, excludes=['uid'])
        def get(self):
          return MyModel.query      # response: [my_model1, my_model2, ...]
```

--------------------------------------------------------------------

thank you so much !

**Comment by svenstaro** [comment]
You should do this with marshmallow instead.
