### ISSUE TITLE
None gets passed while using reqparse, reqparse only validating for keys

### ISSUE THREAD

**Issue by Rahul91** [flask-restful/flask-restful#590]
I am using flask-restful and using reqparse to parse the request parameters. 
None gets passed for a valid key, until I write a method to raise an exception and pass that method in kwargs['type']
Shouldn't be there a more simple and obvious way like nullable or not_empty flags(for string type)?
Also I am new to reqparse, so please guide me if there is an alternative to this. 
Thanks

**Comment by joshfriend** [comment]
Look into [`webargs`](http://webargs.readthedocs.io/en/latest/) for request parsing.

 See also #335
