### ISSUE TITLE
BUG  coding problem

### ISSUE THREAD

**Issue by wysfl** [flask-restful/flask-restful#591]
```python

# -*- coding: utf-8 -*-
from flask import Flask
from flask_restful import Resource, Api
app = Flask(__name__)
api = Api(app)

app.config["RESTFUL_JSON"] = {'ensure_ascii':False}

class HelloWorld(Resource):
    def  get(self):
        return {'msg': '你好世界！'}

api.add_resource(HelloWorld, '/')

if __name__ == '__main__':
    app.run(debug=True)


# result:
# {
#     "msg": "浣犲ソ涓栫晫锛�"
# }

```

**Comment by wysfl** [comment]
This is what I want to be the result
```json
 {
     "msg": "你好世界！"
 }
```

**Comment by mackjoner** [comment]
ref: https://github.com/flask-restful/flask-restful/issues/552

**Comment by songxiaowei112** [comment]
You can try u'你好世界!'  instant '你好世界!'

**Comment by dpylr** [comment]
I fix this problem by modify the  DEFAULT_REPRESENTATIONS  and default_mediatype  in __init__.py
it works fine, but many tests failed!

https://github.com/dpylr/flask-restful/commit/bacc2eeffa2a9cbf2ab998c3a572cd8607e9e861

**Comment by songxiaowei112** [comment]
我最近也找到一个解决方案，这个问题出现的原因好像是flask调用了json字符串化的json.dumps，所以修改flask中的json参数即可，详情定义下面这个类
class NonASCIIJsonEncoder(json.JSONEncoder):
    """
    sxw 2016-9-21
    重设json.dumps中参数设置，使之支持中文
    """
    def __init__(self, **kwargs):
        kwargs['ensure_ascii'] = False
        super(NonASCIIJsonEncoder, self).__init__(**kwargs)
flask工厂函数中配置json_encoder
 # 设置flask-json支持中文
    app.json_encoder = NonASCIIJsonEncoder
就能解决问题，github新手，不好意思。

**Comment by joshfriend** [comment]
I'm going to close this since it seems to be a misunderstanding proper configuration, see #552 and #626.
