### ISSUE TITLE
Splitting key by `.` in marshalling

### ISSUE THREAD

**Issue by vovanz** [flask-restful/flask-restful#595]
Hi, guys.

I have no words, just **WTF?!**

[This function](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/fields.py#L36) is used everywhere in marshaling to get value from data.

```python
def get_value(key, obj, default=None):
    """Helper for pulling a keyed value off various types of objects"""
    if isinstance(key, int):
        return _get_value_for_key(key, obj, default)
    elif callable(key):
        return key(obj)
    else:
        return _get_value_for_keys(key.split('.'), obj, default)
```

Take a look at this line ` return _get_value_for_keys(key.split('.'), obj, default)`:
`key` is splitted by `.` before being passed to the next level.
It leads to unexpected behavior when you use a `key` that contains `.` in it.

**Example:** I used key `cognito-identity.amazonaws.com` in my output and this key was also used in data.
Because of this strange behavior `marshal` was searching data for keys `cognito-identity`, `amazonaws` and `com`, instead of searching for the whole key. Of course, this keys wasn't found and I got `null` in output.

What is this? Is it a bug or an intentional behavior?
If it was intentional then what is it for? And why is it undocumented?

P. S. Sorry for being so emotional, I've just spent more than 3 hours debugging an app...

**Comment by joshfriend** [comment]
This behavior was added by #104. Please use marshmallow instead (see #335), or [override the attribute getter behavior.](http://flask-restful.readthedocs.io/en/0.3.5/fields.html#renaming-attributes)
