### ISSUE TITLE
Service Temporarily Unavailable: http://flask-restful.readthedocs.io is down

### ISSUE THREAD

**Issue by bholagabbar** [flask-restful/flask-restful#601]
The website doesn't seem to be working any more
![capture](https://cloud.githubusercontent.com/assets/11693595/16610347/907ea8ae-430f-11e6-83e4-02e5965687cb.PNG)

**Comment by bholagabbar** [comment]
Seems to working now. Weird. I tried accessing it with a VPN

**Comment by joshfriend** [comment]
Please report any future outages to the ReadTheDocs team. There's nothing I can do about about service interruptions on their site (or bad network configurations with your VPN).
