### ISSUE TITLE
Wrong/Deprecated usage in 0.3.5 docs 

### ISSUE THREAD

**Issue by bholagabbar** [flask-restful/flask-restful#603]
On page [http://flask-restful-cn.readthedocs.io/en/0.3.5/extending.html](http://flask-restful-cn.readthedocs.io/en/0.3.5/extending.html), which is a part of the Documentation for Flask-RESTful 0.3.5, **_on line 5 of the code snippet_**, you have `api = restful.Api(app)` which is no longer in use/deprecated in 0.3.5.

As we know, in on 0.3.5 we are simply using `api=Api(app)` and the import is `from flask_restful import Resource, Api` instead of `from flask.ext import restful`. `restful.Api` has been used in several places.

I think this needs to be corrected.

**Comment by bholagabbar** [comment]
Would like to fix this. However, in the docs folder there seems to be only one 'extending.rst' and this issue is version specific. Not sure where to make the changes

**Comment by joshfriend** [comment]
Please feel free to submit a pull request which addresses these issues.

(see #420)

**Comment by bholagabbar** [comment]
So we can confirm that this is an issue and needs to be fixed yes?

**Comment by joshfriend** [comment]
yes
