### ISSUE TITLE
What's the advantage of using the built-in CORS functionality vs. flask_cors?

### ISSUE THREAD

**Issue by torotil** [flask-restful/flask-restful#607]

**Comment by joshfriend** [comment]
There is none. Please [search the issues list for CORS related topics](https://github.com/flask-restful/flask-restful/issues?utf8=%E2%9C%93&q=cors).

**Comment by torotil** [comment]
I did that and none of those issues answered the question. So the recommendation is to use flask-cors?

**Comment by joshfriend** [comment]
> You should use Flask-CORS instead.

#600
