### ISSUE TITLE
Using Flask Restful with Blueprints in a large project

### ISSUE THREAD

**Issue by crhuber** [flask-restful/flask-restful#608]
I have the following folder structure

```
├── app
│   ├── __init__.py
│   ├── main
│   │   ├── __init__.py
│   │   ├── forms.py
│   │   ├── views.py
│   └── templates
│       ├── base.html
│       └── home.html
├── config.py
├── manage.py
```
I want to use flask-restful as a blueprint in this structure. 

__init__.py

```
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app
```

main/\__init__.py

```
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views 

```

I've seen the examples in the docs but they are too simplistic for a large application structure. 

Using the same pattern above I got the following error:

`AttributeError: 'Blueprint' object has no attribute 'add_resource'`

How would I follow the same pattern but using Flask-restful in a folder called 'api' as a blueprint?

**Comment by AndrewYang17** [comment]
I currently facing this problem, did you manage to figure it out? @crhuber
