### ISSUE TITLE
the function Argument.source can not handle the data  from the request.data

### ISSUE THREAD

**Issue by zuoxiaoliangcoder** [flask-restful/flask-restful#615]
while I use the requests.post(url, data=json.dumps(dict("a":1))) to test the flask-restful, I find that the flask_restful.reqparse.Argument.source()　function can not handler the data correctly. I get the {"a": null}.It is wrong. In the Flask_restful, get the param of the request  by flask.request.json or flask.request.value(usually I do not set the value of the flask_restful.reqparse.Argument.location, so the value of the Argument.location is ('json', 'value')).
 but when I use requests.post(url,data=json.dumps(dict("a":1))). the request.Headers has not the property of the {Content-Type': 'application/json'}, which result the request.json is null  and we can get the data by request.data.
I think it should be solved.

**Comment by joshfriend** [comment]
> Headers has not the property of the {Content-Type': 'application/json'}, which result the request.json is null

If you don't tell flask that you are seinding it JSON in the request, it won't know that you sent it JSON in the request and `request.json` will be `None`. You need to send the proper headers with your request, or just use the `json` kwarg on `requests.post()`
