### ISSUE TITLE
unpack with tuple as return value

### ISSUE THREAD

**Issue by fariza** [flask-restful/flask-restful#619]
This is a problem that I run into, but I didn't find any reference in the documentation.

If we take the following example

```python
from flask_restful import Api, Resource
from flask import Flask

app = Flask(__name__, )
api = Api(app)


class MyResource(Resource):
    def get(self, attribute):
        if attribute == 'string':
            return 'one two'
        if attribute == 'tuple':
            return ('one', 'two')
        if attribute == 'list':
            return ['one', 'two']
        return "Nothing there"

api.add_resource(MyResource, '/<string:attribute>/', endpoint='example')

app.run(host='0.0.0.0', debug=True, use_reloader=True)
```

If we access:

 * `http://localhost:5000/string/`  => `"one two" `
 * `http://localhost:5000/list/` => `['one', 'two']`
 * `http://localhost:5000/tuple/` => `one`

The problem with the tuple, it that the unpack method takes the second element as code and doesn't raise a warning or anything,  so we think everything works as expected.

The most obvious solution is add the code to the return statement `return ('one', 'two'), 200`
But the fact that the code is not mandatory in the return makes it too easy to make a mistake

**Comment by joshfriend** [comment]
Is this different from Flask's [response parsing](http://flask.pocoo.org/docs/0.11/quickstart/#about-responses)?
