### ISSUE TITLE
Updating 'Define Custom Error Messages' in Documentation

### ISSUE THREAD

**Issue by ashwinkumar01** [flask-restful/flask-restful#620]
The section makes no mention of the fact that in fact it depends on the specific Error Classes in werkzeug.exceptions. The examples given also violate this rule, therefore I am updating the section to reflect this. The pull request I submitted addresses this issue

https://github.com/flask-restful/flask-restful/pull/597

**Comment by joshfriend** [comment]
Please just add a comment to your existing pull request to "bump" it. Creating a new issue with the exact same text just adds noise.
