### ISSUE TITLE
reqparse.RequestParser.add_argument type=list does not raise TypeError when input is "str" 

### ISSUE THREAD

**Issue by bdh1011** [flask-restful/flask-restful#627]
I think "type=list" on reqparse.RequestParser.add_argument would raise error if input data is not list type. however, I found add_argument just convert str to list. Isn't it weird?

**Comment by freddrake** [comment]
``ArgumentParser`` wants to do conversion, not type-checking. To verify input values, you'll generally need to provide your own conversion functions that perform the required checks.

This is a good thing, since you probably want to be checking the content of a list or dict as well.

**Comment by bdh1011** [comment]
@freddrake Oh ok, thank you for answer. 
As you said, I had added some type check code in the function. 
But I want to make it more clean by letting `ArgumentParser` to do type checking.
How do you think about it?

**Comment by joshfriend** [comment]
You may be able to subclass `ArgumentParser` to fit your needs

**Comment by freddrake** [comment]
@bdh1011:  While there's a very real distinction between input validation (which is what you really want when you say "type checking") and conversion, a sane conversion API is going to do validation on input anyway.  The only real threat is that some conversions might be expensive relative to the corresponding input validation.  That's not usually a problem with data included in a web request.

Should that be an issue in your application, the conversion could perform the validation and return an object that lets you request the conversion when you need it.  This would allow all input validation to happen before any expensive conversions.

(For expensive conversions, I'm thinking about things like loading large data objects or data that has to be retrieved over a network.)
