### ISSUE TITLE
flask-restful-cn on RTD

### ISSUE THREAD

**Issue by ThiefMaster** [flask-restful/flask-restful#628]
There's flask-restful-cn on readthedocs which has a better google rank than the official docs and is built from [this fork](https://github.com/strahe/flask-restful) which is somewhat outdated. Have you considered asking the guy to take it down in favor of a single canonical documentation? I have no idea how complete/good their chinese translation is (as I don't speak chinese) but maybe having a partial translation in the official docs would be better than the current mess of two docs for the same project on RTD.

The links in the RTD panel on http://flask-restful.readthedocs.io/ also redirect to `-cn` for some reason...

**Comment by joshfriend** [comment]
Thats rather unfortunate :(

@strahe has disabled issues on that repo and has no contact info on their github profile page. Maybe @ mention here will work?

Sphinx documentation and ReadTheDocs support localization and I'd gladly accept PRs to support other languages in the docs.

https://read-the-docs.readthedocs.io/en/latest/localization.html
http://www.sphinx-doc.org/en/stable/intl.html

**Comment by strahe** [comment]
@ThiefMaster @joshfriend Thank you for reminding me，I have closed that repo.
