### ISSUE TITLE
Support for same resource with multiple HTTP verbs endpoints

### ISSUE THREAD

**Issue by harit-sunrun** [flask-restful/flask-restful#63]
Consider the following

I have resources `User` and `Transaction`
A `User` has one to many `Transaction`. I was trying to design the endpoint similar to following but something I do is not right

```
api.add_resource(UserResource, '/users/<uuid>', '/users/<uuid>/transactions')

class UserResource(restful.Resource):
    # /users/<uuid> match here
    def get(self, uuid):
        return {'method': 'get user -> uuid'}
    # /users/<uuid>/transactions should match here
    def get(self, uuid, **kwargs):
        return {'method': 'get user transactions -> uuid'}

    def post(self, uuid):
        return {'method': 'post user -> uuid'}

    def put(self, uuid):
        return {'method': 'put user -> uuid'}

    def delete(self, uuid):
        return {'method': 'delete user -> uuid'}
```

When I test this, I get
hhimanshu@air14:18:22 ⮀ ~PYTHONPATH ⮀ ⭠ restful± ⮀ curl  -X GET http://127.0.0.1:5000/users/uuid/transactions
{"method": "get user transactions -> uuid"}                                                                                          hhimanshu@air14:21:03 ⮀ ~PYTHONPATH ⮀ ⭠ restful± ⮀ curl  -X GET http://127.0.0.1:5000/users/uuid
{"method": "get user transactions -> uuid"}

It always routes me into get which is shown in comments
Is there a way I can route my endpoints to different get, put, post and delete methods in same resource based on how my endpoints look?

GET /users/uuid/transactions # all transactions for a user

GET /users/uuid/transactions/yyyy # user transactions for year yyyy

GET /users/uuid/transactions/yyyy/mm # user transactions for year yyyy, month mm

GET /users/uuid/transactions/yyyy/mm/dd # user transactions for year yyyy, month mm and day dd

What do you recommend would be the best way to use Flask-RESTful in this case?

**Comment by r0b1n1sl4m** [comment]
I'm new with restful routing and looking for help someone please help me:
api.add_resource(UserRoutes, '/api/user/', '/api/user/<int:user_id>/', '/api/user/<int:user_id>/notes/')
what is the best way to apply this format using same resource?

**Comment by sibblegp** [comment]
You really can't and shouldn't use the same resource since they do different things.  Use a separate resource for each.

**Comment by r0b1n1sl4m** [comment]
Thanks for your help. You right I can't use the same resource for this kind of route so I'm using different resource now.
