### ISSUE TITLE
Representations decorator doesnt work

### ISSUE THREAD

**Issue by ddc67cd** [flask-restful/flask-restful#640]
I've discovered that `@api.representation` and `api.representations['text/csv'] = func` are not equal, first one doesn't works as expected (in my case, restful uses decorated function for 'application/json'). It seems that some magic happens when you access a representations object directly.

**Comment by joshfriend** [comment]
Here's the [`@api.representation` decorator](
https://github.com/flask-restful/flask-restful/blob/975ae4e502f42f2c9c6c95670af40ac93ea830be/flask_restful/__init__.py#L526-L550
):

```python
class Api:
    def representation(self, mediatype):
        def wrapper(func):
            self.representations[mediatype] = func
            return func
        return wrapper
```

So this:

```python
@api.representation('text/csv')
def render_csv(*args):
    pass
```

is exactly the same as:

```python
api.representations['text/csv'] = render_csv
```

Please provide more details about your issue, like an example which demonstrates your issue. "doesn't works as expected" doesn't give me anything to go on.

**Comment by ddc67cd** [comment]
Thank you for your reply. You're right, decorator has nothing to do with my issue. After spending some time debugging the problem, I figured that problem belongs to werkzeug/chrome.
Chrome sends header "Accept:application/json, text/plain, */*", all types are being equal. Due to random key order in python dictionaries and algorithm used in werkzeug (https://github.com/pallets/werkzeug/blob/0bc61df6e1ae9f2ffdf5d066aa3cd9d5ebcb307d/werkzeug/datastructures.py#L1726), sometimes it choosing text/csv, sometimes - application/json. Is it expected behavior?

**Comment by joshfriend** [comment]
Werkzeug will preserve the ordering of the items in the `Accept` header (the `Accept` class extends `ImmutableList`) and `Request.accept_mimetypes.best_match` says:

> If two items have the same quality, the one is returned that comes first.

`Api.representations` is an `OrderedDict`, so `application/json` should always be chosen in this scenario unless you override `Api.representations` in some way which would make it a regular `dict`, e.g.

```python
api = Api(app)
api.representations = {
  'application/json': render_json,
  'text/csv': render_csv,
}
```

**Comment by ddc67cd** [comment]
Thank you for explanation. It was my fault, I've been using old version (0.3.2) with dict instead of OrderedDict.

**Comment by joshfriend** [comment]
> I've been using old version

Argh, I really should have asked about that to begin with! Glad you got it sorted out though.
