### ISSUE TITLE
function caching on imported resources?

### ISSUE THREAD

**Issue by i-a-n** [flask-restful/flask-restful#642]
Hey there, I've set up your basic "hello world" API app, and everything works fine. However, it seems to be caching, server-side, any output from functions `import`ed, as described in your intermediate usage ["project structure"](http://flask-restful.readthedocs.io/en/0.3.5/intermediate-usage.html#project-structure) doc. For instance:

```
from flask import Flask
from flask_restful import Resource, Api
from resources.randomImported import RandomImported # identical structure to class below

import random

app = Flask(__name__)
api = Api(app)

class RandomDefault(Resource):
    def get(self):
        return {'number': random.random()}

api.add_resource(RandomDefault, '/random')
api.add_resource(RandomImported, '/random-imported')
```
In the above example, the endpoint `random` works flawlessly (you reload the `/random` endpoint and get a new random number each time). However, the endpoint `random-imported` does *not* work. When you load it the first time, you get a random number as expected. However, further reloads only return the original number. The result is cached somewhere.

This is consistent across sessions, browsers, etc. It's cached somewhere server-side, but only when `import`ed as above. Am I missing something obvious? Is this some python-level caching? When I strip it down to just python files and `print()` the error doesn't occur, so I'm guessing it has something to do with `flask-restful`.

Thanks in advance.

**Comment by i-a-n** [comment]
I should note: stopping then restarting the server will "clear the cache" so to speak; you'll get a new random number again the first time, and then further requests will continue to be that first number until the server is stopped and started again.

**Comment by naydichev** [comment]
Problem seems like pebkac.

**Comment by i-a-n** [comment]
Ah, the issue was that I had defined the random number above the Class in the imported file. Disregard! And thanks @naydichev!
