### ISSUE TITLE
add_resource does not preserve api function docstring

### ISSUE THREAD

**Issue by izmailoff** [flask-restful/flask-restful#643]
I'm trying to auto generate API help using this piece of code:

```
@app.route('/api/help', methods=['GET'])
def api_help():
    """Returns all registered APIs available in this application."""
    func_list = {}
    for rule in app.url_map.iter_rules():
        if rule.endpoint != 'static':
            func_list[rule.rule] = app.view_functions[rule.endpoint].__doc__
    return jsonify(func_list)
```

It relies on `__doc__` of a function and works fine for APIs defined with a `route` decorator:

`@app.route('/someapi'...`

However, when a route is registered with `add_resource` the docstring is lost.

The help api returns data in this format:

```
{
  "/api/help": "Returns all registered APIs available in this application.", 
  "someapi": null
}
```

tried on latest versions:

> Name: Werkzeug
> Version: 0.11.11
> 
> Name: Flask
> Version: 0.11.1
> 
> python --version
> Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

**Comment by joshfriend** [comment]
The documentation [_is_ preserved](https://github.com/pallets/flask/blob/master/flask/views.py#L99), just not quite how you were expecting. With resources, the class is the view function, so you can't document get/post/etc separately.
