### ISSUE TITLE
Api.init_app() does not work as intended

### ISSUE THREAD

**Issue by deelaka** [flask-restful/flask-restful#644]
The example below should run fine yet it fails and the url's  do not get registered, thus accessing the '/' url fails with a *404*.

```
from views import app, ManageUser
from flask_restful import Api

if __name__ == '__main__':
    api = Api()
    api.init_app(app)
    api.add_resource(ManageUser, '/')

    app.run(debug=True)
```

However without using `init_app()` if I provide the `Api()` constructor with the `app` instance, the web app runs perfectly fine and the urls are properly registered.

**Comment by joshfriend** [comment]
see #203 

`init_app` is when the registered resources are added to the flask app, so registering one with the `api` object afterwords does not add it to the flask `app`.
