### ISSUE TITLE
Weird marshaling lists

### ISSUE THREAD

**Issue by Ignalion** [flask-restful/flask-restful#647]
Hi guys,

I have a bit weird issue here.
I want to return response like list of results or SQLAlchemy query. They are, unfortunately, of type `<class 'sqlalchemy.util._collections.result'>` that I believe is misinterpreted by the marshal as list.

So, the issue is the following.
The structure of query result is like object with attributes 'name' and 'time' that is datetime.datetime object. As far as I understand, json can't serialize datetime object so I tried to use marshal_with decorator but there was no luck.

I made a short code for generate test data like this:

```

test_fields = {
    'name': fields.String,
    'time': fields.DateTime,
}


class TestList(Resource):
    @marshal_with(test_fields)
    def get(self, filters=None):
        return get_test_list(filters)
```

But it doesn't work.
Actually, for each element it generates structure like this:
`
[
        {
            "name": null, 
            "time": null
        }, 
        {
            "name": null, 
            "time": null
        },
    ], 
`

Thus I believe that it tries to parse each element of `<class 'sqlalchemy.util._collections.result'>` as an item that have 'name' and 'title' attributes that is obviously incorrect.

Can you please advise any workaround?

Thanks,
Constantine

**Comment by joshfriend** [comment]
See #469
