### ISSUE TITLE
Pretty print JSON output

### ISSUE THREAD

**Issue by alexjurkiewicz** [flask-restful/flask-restful#649]
Hi, I'd like the ability for JSON output to be pretty printed, so humans doing testing can get a better view of the data. Basically, I'd like the JSON output to be created with `indent=2, sort_keys=True` if pretty printing is requested.

Support for this was added in #73 but it looks like the option was later removed, in that `flask_restful.representations.json.settings` doesn't exist. Is there a new approach to supporting this, or was support dropped entirely?

**Comment by justanr** [comment]
https://github.com/flask-restful/flask-restful/blob/e28f7662a86b2aae52c1e0af17c60077e9adcbc4/flask_restful/representations/json.py

You can create a `RESTFUL_JSON` key on your flask config that correspond to the standard library's `json.dumps` arguments.
