### ISSUE TITLE
Missing trailing slash, redirect without Location header

### ISSUE THREAD

**Issue by mindflayer** [flask-restful/flask-restful#65]
Hi there,
I've just noticed we are having a strange behavior with the trailing slash:

this is a simple Flask demo, the one at http://flask.pocoo.org/docs/quickstart/ with a different url:

<pre>
$ curl -I http://127.0.0.1:5000/hello/
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 12
Server: Werkzeug/0.8.3 Python/2.7.3
Date: Tue, 09 Apr 2013 15:05:19 GMT

$ curl -I http://127.0.0.1:5000/hello
HTTP/1.0 301 MOVED PERMANENTLY
Content-Type: text/html; charset=utf-8
Content-Length: 263
Location: http://127.0.0.1:5000/hello/
Server: Werkzeug/0.8.3 Python/2.7.3
Date: Tue, 09 Apr 2013 15:05:21 GMT
</pre>

my flask-restful API:

<pre>
$ curl -I http://127.0.0.1:5000/objects/
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 2
Server: Werkzeug/0.8.3 Python/2.7.3
Date: Tue, 09 Apr 2013 15:07:10 GMT

$ curl -I http://127.0.0.1:5000/objects
HTTP/1.0 301 MOVED PERMANENTLY
Content-Type: application/json
Content-Length: 47
Server: Werkzeug/0.8.3 Python/2.7.3
Date: Tue, 09 Apr 2013 15:07:29 GMT
</pre>

As you can see it's a redirect without the Location header.

Regards,
Giorgio

**Comment by vinaykonanki** [comment]
using "strict_slashes=False" in add_resource solved the redirect. both with/without trail slash will return the same output.
