### ISSUE TITLE
Internal Server error periodically

### ISSUE THREAD

**Issue by praving55** [flask-restful/flask-restful#651]
Hi All,
I am experiencing exactly the same issue as [http://stackoverflow.com/questions/34249356/flask-api-not-receiving-requests-all-of-a-sudden](http://stackoverflow.com/questions/34249356/flask-api-not-receiving-requests-all-of-a-sudden).

This is a year old thread. Is the issue still persist or I could be doing something wrong?

Thanks and regards,
Pravin Goyal

**Comment by danlindow** [comment]
Are you using anything to daemonize flask? You should not be running the development server in production at all. Gunicorn is pretty straight forward to setup and use.

**Comment by joshfriend** [comment]
As the linked SO posts seem to indicate, I think it's a problem of using the built in debug http server instead of something like Gunicorn
