### ISSUE TITLE
Documentation lacks on adding list of query parameters

### ISSUE THREAD

**Issue by enod** [flask-restful/flask-restful#653]
Hi all,

I would like to add query parameter which is list in my API endpoint. However documentation mostly described it in request body. 

What I want to do is:
https://myurl.com&start_date=2014-10-13&end_date=2014-10-13&fields=title,datetime
where start_date, end_date and fields are defined in query parameters.
And also wondering if flask restful has validation method for fields parameter.

**Comment by joshfriend** [comment]
Your URL should look like `...fields=title&fields=datetime` and use the `multiple` feature

http://flask-restful.readthedocs.io/en/0.3.5/reqparse.html#multiple-values-lists

otherwise you will need to parse the list yourself.

**Comment by tobyweed** [comment]
Any documentation on how to do this when passing values by adding them to the add_resource url and passing them in def get? As in:

```
class SearchEvents(Resource):
    def get(self, name, start_date, end_date):
         #do something

api.add_resource(endpoints.SearchEvents, '/events?name=<string:name>&start_date=<string:start_date>&end_date=<string:end_date>')
```

When trying the above via postman I get url not found.

**Comment by joshfriend** [comment]
> I get url not found.

Yeah, I don't _think_ flask looks at anything in the querystring for routing.
