### ISSUE TITLE
Possible slight code example error in docs

### ISSUE THREAD

**Issue by pirxthepilot** [flask-restful/flask-restful#658]
I was reading this page in the docs:

https://flask-restful.readthedocs.io/en/latest/intermediate-usage.html#passing-constructor-parameters-into-resources

I tested it using the example code, but I got an error. I changed the line:

```
def __init__(**kwargs):
```

into:

```
def __init__(self, **kwargs):
```

which seems to have fixed it. I'm not a python expert so I am not sure if this was a slight error in writing the doc.

**Comment by joshfriend** [comment]
Yes, there is supposed to be a `self` as the first parameter to `__init__`. Thanks for pointing that out!

**Comment by cdnsteve** [comment]
@joshfriend just checked and looks like this is resolved in the source on master already.
https://github.com/flask-restful/flask-restful/blob/master/docs/intermediate-usage.rst#passing-constructor-parameters-into-resources

Somehow the docs might just need to get re-deployed to readthedocs?
Thanks
