### ISSUE TITLE
CORS headers for non-successful returns

### ISSUE THREAD

**Issue by bow** [flask-restful/flask-restful#659]
Hello developers,

I'm aware that [Flask-RESTful does support adding CORS headers](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/utils/cors.py) to various responses as [tested here](https://github.com/flask-restful/flask-restful/blob/master/tests/test_cors.py). However, I found that this is not the case when an exception is raised somewhere in the code (e.g. 401 when expecting some sort of authentication or 422).

Is this an intentional limitation or are there any plans on adding these CORS headers  to non-successful HTTP responses / HTTP responses created from internal exceptions?

Thanks in advance!

**Comment by joshfriend** [comment]
See [this comment](https://github.com/flask-restful/flask-restful/issues/229#issuecomment-63161039)
