### ISSUE TITLE
Is there any planned release?

### ISSUE THREAD

**Issue by lipis** [flask-restful/flask-restful#665]
The last published version was in https://pypi.python.org/pypi/Flask-RESTful Dec 2015.. Arguably there are not many changes.. but still it's good idea to update once in a while :)

**Comment by songxiaowei112** [comment]
I love python,this project which I want to maintenance.

**Comment by Toilal** [comment]
Please @joshfriend, it seems you have merged some pull request, so would it be possible to release to pypi ? Else what's the problem ?

**Comment by joshfriend** [comment]
https://pypi.python.org/pypi/Flask-RESTful/0.3.6
