### ISSUE TITLE
Working with optional arguments

### ISSUE THREAD

**Issue by SirScott** [flask-restful/flask-restful#666]
Using Flask-Restful 0.3.5 with Python 3.5.2 and Flask 0.11.1, I'm curious if it's possible to distinguish between an optional argument that wasn't provided and one that was provided, but with a value of None.

Assume a parser like this:

```(python)
reqparser = reqparser.RequestParser()
reqparser.add_argument('foo', required=False)
args = reqparser.parse_args()
```

In my route code, I need to introduce some logic depending upon whether or not 'foo' was provided in the request.  My initial reaction was to do this with `if 'foo' in args`, but it appears that it always exists as a key in args.  Instead, I need to interrogate the request's data:  `if b'foo' in request.data`.

Is this the right way to do this?  I feel like I'm missing something, as by using Flask-Restful, needing to access Flask's request.data directly is something I wouldn't expect to do.

Thank you!

**Comment by SirScott** [comment]
Yeah, i totally was reading something wrong.  Sorry for the noise.  This works as I'd expect: you can check for the existence of the key in the parsed argument's namespace!

**Comment by ohadperry** [comment]
@ScottSturdivant 
can you paste your entire code? I'm trying multiple variations and 
```
parser = reqparse.RequestParser()
parser.add_argument('currency', type=str, store_missing=True, default='USD')

args = parser.parse_args()
```
also tried `store_missing=False`. and `required=False` explictly.

**Comment by ScottSturdivant** [comment]
Here's `app.py`:

```python
from flask_restful import reqparse
from flask import Flask
app = Flask(__name__)


@app.route('/')
def index():
    parser = reqparse.RequestParser()
    parser.add_argument('foo', store_missing=False)
    args = parser.parse_args()

    return str('foo' in args)
```

Run the server with `FLASK_APP=app.py flask run`, then the output when querying the endpoint:

```
$ curl localhost:5000         
False
                                                                                                                                                                                        
$ curl "localhost:5000/?foo=1"
True
```

Your error sounds like a problem elsewhere in the stack.
