### ISSUE TITLE
is there a way to marshal datetime.date in flask_restful?

### ISSUE THREAD

**Issue by devyash** [flask-restful/flask-restful#667]
Currently the fields that are supported are only Datetime.datetime [here](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/fields.py) is there a way to use datetime.date attribute?

**Comment by ashwinkumar01** [comment]
Have you tried using Marshmallow?

**Comment by joshfriend** [comment]
Marshmallow is what I recommend. You can also [define custom fields for marshalling](http://flask-restful.readthedocs.io/en/0.3.5/fields.html#custom-fields-multiple-values)
