### ISSUE TITLE
abort(404, message="foo") shouldn't add text to message.

### ISSUE THREAD

**Issue by frankstratton** [flask-restful/flask-restful#67]
There are two issues here:
1) If I'm defining outputs for my error messages, I don't want Flask-Restful to add a non-overridable text to my potentially public facing output.  It's just confusing.  If I pass a message kwarg to abort it shouldn't append data to that message.

2) Bug in finding "close matches" when using url params

My Code:

```
abort(404, message="user {} not found".format(args['with_id']))
```

The output:

```
curl localhost:5003/foo/z4s6hp33im0h?with_id=123

{
"message": "user 123 not found. You have requested this URI [/foo/z4s6hp33im0h] but did you mean /foo/<key> ?"
}
```

**Comment by madhavan020985** [comment]
Is this fix available in 0.10.1... when i had an abort,404 with custom message, it added a lot more message like,
abort(404, {'message': 'custom error message to appear in body'})
gives,

{"status": 404, "message": "Not Found. You have requested this URI [/api/orca/v1.0/1234/reboot] but did you mean /api/orca/v1.0/<string:SerialNumber>/<string:Action> or /api/orca/v1.0/checkout or /api/orca/v1.0/checkin ?"}

**Comment by joshfriend** [comment]
@madhavan020985 you need to set `ERROR_404_HELP` to `False` in your app config.

**Comment by NiklasRosenstein** [comment]
Wouldnt it make more sense to be able to configure this per Api or per Resource? Maybe I want this feature on one API but not on another.

**Comment by zogzog** [comment]
> @madhavan020985 you need to set `ERROR_404_HELP` to `False` in your app config.

This does not work with a blueprint.
