### ISSUE TITLE
Thought about Jazzband?

### ISSUE THREAD

**Issue by lwm** [flask-restful/flask-restful#672]
https://jazzband.co/

This project seems to lack contributors and is getting stuck under issues.

Jazz band is made for this.

**Comment by lwm** [comment]
bump bump bump. Anyone of the 153 people watching this have anything to say about it? Clearly there is a huge maintenance burden on this package and I am sure some of us can help out!? The fantastic [pip-tools](https://github.com/jazzband/pip-tools) (was totally unmaintained at some point) package took the Jazzband plunge and has been made all the better for it.

**Comment by italomaia** [comment]
This project seems to be maintained still. I don't think it is in a "jazzband" situation. Sometimes things go slow. Maybe it just need more maintainers or something.
