### ISSUE TITLE
Tests are failing because of a werkzeug change

### ISSUE THREAD

**Issue by aluttik** [flask-restful/flask-restful#673]
[This PR](https://github.com/pallets/werkzeug/pull/1003/files) in made it into `Werkzeug 1.12.0` , so now `flask.abort` is a function and `abort.mapping` throws an error. This is what's breaking the build on master.

`abort.mapping` is used once in the tests [here](https://github.com/flask-restful/flask-restful/blob/master/tests/test_api.py#L811).

**Comment by joshfriend** [comment]
The commit message on pallets/werkzeug#1003 was:

> Move abort documentation from rst into code

🤦‍♂️
