### ISSUE TITLE
Is this project maintained or obsolete?

### ISSUE THREAD

**Issue by boosh** [flask-restful/flask-restful#677]
The docs on the [request parsing](http://flask-restful.readthedocs.io/en/0.3.5/reqparse.html) page recommend using marshmallow for arg parsing.

Given marshmallow can handle input and output parsing, and that this project hasn't seen a new release in 2 years I guess it's redundant? If so, it'd be useful to highlight it's no longer maintained to stop people wasting their time.

**Comment by joshfriend** [comment]
Fresh release here: https://pypi.python.org/pypi/Flask-RESTful/0.3.6

I don't spend tons of time on this anymore, but it still works well as is. I would encourage people to migrate to marshmallow/webargs though.
