### ISSUE TITLE
sort_keys in debug mode may lead to compare error (data type mismatch)

### ISSUE THREAD

**Issue by imhuwq** [flask-restful/flask-restful#678]
``` python
def output_json(data, code, headers=None):
    """Makes a Flask response with a JSON encoded body"""

    settings = current_app.config.get('RESTFUL_JSON', {})

    # If we're in debug mode, and the indent is not set, we set it to a
    # reasonable value here.  Note that this won't override any existing value
    # that was set.  We also set the "sort_keys" value.
    if current_app.debug:
        settings.setdefault('indent', 4)
        settings.setdefault('sort_keys', True)

    # always end the json dumps with a new line
    # see https://github.com/mitsuhiko/flask/pull/1262
    dumped = dumps(data, **settings) + "\n"
    resp = make_response(dumped, code)
    resp.headers.extend(headers or {})
    return resp
``` 

as you can see , `sort_keys` is turned on on debug mode. However, in Python3, comparison between different data type is not supported.

```
>>> a = {"100":100, 100: 100}
>>> a
{100: 100, '100': 100}
>>> items = sorted(a.items(), key=lambda kv: kv[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() < int()
>>> 

```

And anybody can explain the necessity to sort keys in debug mode? I'm thinking about turn it off permanently.

**Comment by joshfriend** [comment]
how does the sorting of keys in JSON make the python types any more or less orderable?

**Comment by imhuwq** [comment]
Hi @joshfriend, thank you for your reply. 
The sorting may produce a more beautiful output, but the unexpected exception is, in my opinion, rather confusing. And it's help is only limited to debug purpose, so why not turn it off.
This is my first time opening an issue on github, so please forgive me if I'm being offensive in my words.

**Comment by joshfriend** [comment]
`sort_keys` is the default behavior for `DEBUG=True` only. You can also override it using the `RESTFUL_JSON` config variable in your app's config object. e.g:

```python
RESTFUL_JSON = {
    'sort_keys': False,
}
```

I think I understand your issue now, though. Key sorting should probably be opt-in since it imposes some limitations on the data being serialized which like you said, may not be very obvious to most people (including myself apparently).

**Comment by freddrake** [comment]
JSON requires the keys to be strings, though.  How do you expect the example structure you showed to be serialized?

**Comment by imhuwq** [comment]
Hi @freddrake , the build-in python json module can dumps that to str keys. 
``` python
>>> data = {"100":"str", 100:"int"}
>>> import json
>>> json.dumps(data)
'{"100": "int", "100": "str"}'

```

**Comment by freddrake** [comment]
Egads!  That so feels like a bug to me.
