### ISSUE TITLE
init_app does not set the application

### ISSUE THREAD

**Issue by lennartblom** [flask-restful/flask-restful#679]
We are currently setting up a API-infrastructure in which we selected flask-restful for defining our routes and it's resources.

Our previous structure would lead us to define the following calls:

In **app/extensions.py** we do: 
```
api = flask_restful.Api()
```

In **app/init.py** we do:
```
class OurFlaskApplication(Flask):
    def _configure_extensions(self) -> None:
        extensions.debugger.init_app(self.app)

            extensions.api.init_app(self.app)
```

But apparently the .init_app() call does not set the flask_restful's Api.app with self.app (the parameter of .init_app().

Is this done on purpose, or is it simply just forgotten to add?

The @SIEVERSCloudDevelopment Team would appreciate your feedback! 

Thank you very much in advance!

Kind regards from Germany!

**Comment by joshfriend** [comment]
This is intentional, please read #319, #360, #644
