### ISSUE TITLE
0.3.6 breaks list arguments

### ISSUE THREAD

**Issue by suurjaak** [flask-restful/flask-restful#681]
```
parser = flask_restful.reqparse.RequestParser()
parser.add_argument('tables',
                    default=[],
                    type=list,
                    location='json',
                    help='Tables to query if not all')
args = parser.parse_args()
```

Making POST with
```
{
  "tables": ["alerts", "events"]
}
```

results in args["tables"] being `['a', 'l', 'e', 'r', 't', 's']`.

**Comment by joshfriend** [comment]
probably because of #645 :(

**Comment by JeffZen** [comment]
I am also running into this problem.  

If I modify line 178 in reqparse.py to be:
`values = [source.get(name)]`

It works with lists being passed in. 

The exception is being thrown at line 193:
`value = self.convert(value, operator)`
value = [25,26], operator = '=' when it fails for me.

I get an exception that says: Int object is not iterable

**Comment by melgor** [comment]
I'm also have same issue. Are you planning to revert this commit and release new package?

**Comment by abdidarmawan007** [comment]
i have problem with this, please fix this issue in new release

**Comment by trondhindenes** [comment]
can repro.

**Comment by patrickyan** [comment]
So what's the latest actually stable version?

**Comment by ruiaylin** [comment]
i meet the same problem in 0.3.6 and i downgrade  to 0.3.5 . Now it work perfectly

**Comment by dmsimard** [comment]
Also seeing this, have pinned to 0.3.5 in the meantime.

**Comment by dschmide** [comment]
This bug is still happening please re-open

**Comment by billyrrr** [comment]
@dschmide Are you able to reproduce this error in a test case? I can help look into it after that
