### ISSUE TITLE
0.3.6 Docs broken link

### ISSUE THREAD

**Issue by streeck** [flask-restful/flask-restful#684]
The following link is broken:
http://flask-restful.readthedocs.io/en/0.3.6/

And although http://flask-restful.readthedocs.io/en/0.3.5/ works, it shows the following:

![image](https://user-images.githubusercontent.com/4401006/26897851-4726327c-4ba0-11e7-84c1-6f85f8740164.png)

**Comment by expobrain** [comment]
Also the **API Docs** page is broken as well http://flask-restful.readthedocs.io/en/0.3.5/api.html

**Comment by streeck** [comment]
Indeed @expobrain, this has been reported in #661 by the way ;).
