### ISSUE TITLE
Is this library compatibly with 3.6?

### ISSUE THREAD

**Issue by Ahmed** [flask-restful/flask-restful#687]
Hi Team:
The current document doesn't mention the library is compatible with 3.6
https://flask-restful.readthedocs.io/en/0.3.5/

Do I need to make a pull request to fix that?

**Comment by joshfriend** [comment]
https://github.com/flask-restful/flask-restful/blob/0.3.6/setup.py

**Comment by Ahmed** [comment]
Hmm, that's a nice way of replying. Couldn't find 3.6 document, that's why I asked. Thanks anyway.
