### ISSUE TITLE
How can I create POST, GET, PUT on one resource in flask restful??

### ISSUE THREAD

**Issue by vimox-shah** [flask-restful/flask-restful#706]
class User(Resource):
      def post(self):
         return true
      def put(self, id):
        return true
      def get(self, _id):
        return true

Is this possible?? or I have to create different resource for every http method?

**Comment by cprieto** [comment]
Easy way to know, write it, test it...

And yes, it is totally possible.

**Comment by vimox-shah** [comment]
how to add multiple urls in same resource?

**Comment by joshfriend** [comment]
Did you try reading [the docs](https://flask-restful.readthedocs.io/en/latest/quickstart.html#resourceful-routing) or even try the code you posted above?
