### ISSUE TITLE
How to handle assertion error?

### ISSUE THREAD

**Issue by vimox-shah** [flask-restful/flask-restful#708]
If i am handling using abort still it gives html response why?

**Comment by joshfriend** [comment]
please provide a code sample that replicates this issue

**Comment by vimox-shah** [comment]
here is the snippet @joshfriend    
     try:
            doc_meta_params = DocumentOrganizationDataController()
            _doc_id, _doc_meta, _page_meta = doc_meta_params.document_meta_params()
            document_extraction_collection = ms.mongo.db.document_extraction
            doc_meta = document_extraction_collection.find_one_and_update(
                {'_id': ObjectId(_doc_id)},
                {
                    "$set": {'doc_meta': _doc_meta, 'page_meta': _page_meta}
                },
                return_document=ReturnDocument.AFTER)

            doc_meta_schema = DocumentMetaSerializer()
            doc_meta = bson_id_to_str(doc_meta)
            return doc_meta_schema.jsonify(doc_meta)

        except Exception as errors:
            message = "Database Error"
            status = 500
            abort(status, message)

**Comment by joshfriend** [comment]
> Please note that if you add an error handler for “500 Internal Server Error”, Flask will not trigger it if it’s running in Debug mode.

http://flask.pocoo.org/docs/0.12/patterns/errorpages/#error-handlers

http://werkzeug.pocoo.org/docs/0.12/exceptions/#werkzeug.exceptions.abort

https://stackoverflow.com/a/15004612/1255482
