### ISSUE TITLE
Docs are not building correctly

### ISSUE THREAD

**Issue by prmtl** [flask-restful/flask-restful#715]
API docs page is empty: http://flask-restful.readthedocs.io/en/latest/api.html due to the missing flask-restful app requirements.
There are bunch of ImportErrors in the build log on ReadTheDocs page:
```
/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/checkouts/latest/docs/api.rst:9: WARNING: autodoc: failed to import function 'marshal' from module 'flask_restful'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 560, in import_object
    __import__(self.modname)
ImportError: No module named 'flask_restful'
```

Fix is described in RTD docs: http://docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc

**Comment by joshfriend** [comment]
Oh wow, thanks so much for finally figuring out how to fix #661 for me!

**Comment by prmtl** [comment]
Oh, sorry that I've reported a duplicated.

**Comment by joshfriend** [comment]
@prmtl that is totally OK! You are the only one who has figured out how to actually fix it!
