### ISSUE TITLE
Better tutorial for large project

### ISSUE THREAD

**Issue by miff** [flask-restful/flask-restful#716]
Please help,
Working on some research to determinate witch technology and framework suits for large medical API. Found that Flask-restful is almost excellent, but have 'trouble' to organize structure of project
```
hapi/
    api.py
    modules/
         __init__.py
         module1.py
         module2.py
```
Try from [here](https://flask-restful.readthedocs.io/en/latest/intermediate-usage.html), but it's confusing, must say that am not familiar with Flask / Flask-restful at all, this is first time to 'playing'
Thanks

**Comment by joshfriend** [comment]
This is a topic that [has been discussed at great length by numerous people](https://www.google.com/search?q=large+flask+project+architecture). There isn't really a "right" way, you need to do what makes sense and feels comfortable to you. I suggest reading what others have done for some ideas.
