### ISSUE TITLE
RequestParser does not take arguments from URL on remote server

### ISSUE THREAD

**Issue by kchoam** [flask-restful/flask-restful#718]
I have a project. Everything is awesome on my local device. But on remote server, where it should be run, RequestParser does not take any arguments/parameters in the URL. 

Example:
`parser = reqparse.RequestParser()`
`parser.add_argument('foo1')`
`parser.add_argument('foo2')`
`args = parser.parse_args()`

The `args['foo1']` and `args['foo2']` will always `null` even I add `/example?foo1=a&foo2=b`
but this is only happen on my remote server. Any thought or solution? Thanks

**Comment by freddrake** [comment]
Do you have a reverse proxy between the network and your application?  This sounds like the query string isn't being passed along.

**Comment by kchoam** [comment]
Thank you for your comment. It seems so because when I try to log the requested URL, the URL is different. I requested /example?foo1=hello&foo2=world, it just log URL /example without parameters. I will start asking my remote server host about this and inform any update. Thank you so much 👍
