### ISSUE TITLE
In python3.6 , fields.Url is different from new version

### ISSUE THREAD

**Issue by tianruoliang** [flask-restful/flask-restful#720]
python3.6
Flask-RESTful (0.3.6)
`pip install flask-restful`
It's the same as before

    class Url(Raw):
        ...
        def __init__(self, endpoint=None, absolute=False, scheme=None):
            ...

Actually, in GitHub

    class Url(Raw):
        ...
        def __init__(self, endpoint=None, absolute=False, scheme=None, **kwargs):
            ...

I don't know why

**Comment by joshfriend** [comment]
The commit you commented on earlier (efca71f09db9e6ca2c483b09ba9257899da011be) is not yet released on pypi. You need to look at the 0.3.6 tag if you want to see the source of the current pypi version

**Comment by tianruoliang** [comment]
@joshfriend thank you
