### ISSUE TITLE
Suggestion / PR - make return code for parse_args() configurable

### ISSUE THREAD

**Issue by skamsie** [flask-restful/flask-restful#721]
I would like to be able to configure which return code is used when aborting inside the `parse_args` method:

https://github.com/flask-restful/flask-restful/blob/f71b4f61d96c43748ca1cb9002f874a8d8276312/flask_restful/reqparse.py#L311-L312

It is currently set to `400` without being able to change it without overriding the method or doing ugly hacks. My proposal is to have it as a keyword argument to the method with the default of 400.

Why? Without going into polemics about which return code is more appropriate for missing / improper arguments (400, 422 or even 412), let's say that an api already returns code `xxx` for argument related errors and switching to flask-restful reqparse will be less painful.

I can make a PR if this idea is approved.

**Comment by joshfriend** [comment]
like `parser.parse_args(http_exception=422)`?
If so, 👍

**Comment by skamsie** [comment]
I created a PR. However I can't figure out how to write a test. Whatever I try, I can;t get this `errors` dict to be populated during a test.

https://github.com/flask-restful/flask-restful/pull/722/files#diff-dfb1c961dc7a64b875a11db32125a87cL303
