### ISSUE TITLE
Example value is null in an array of arrays.

### ISSUE THREAD

**Issue by panuhorsmalahti** [flask-restful/flask-restful#725]
I'm defining the API documentation as follows:
```
@api.doc(model=fields.List(fields.List(fields.Nested(MyClass.flask_model))))
```

where `MyClass.flask_model` is `api.model('MyObject', { ... })`.

The example value in the Swagger documentation is `[[ null ]]` instead of null being an object with example values. In addition, the model documentation contains `{}` instead of list of the properties with descriptions.

It seems that this bug is triggered depending on the `api.doc` for another class in another namespace. If the `api.doc` for another class is `@api.doc(model=MyClass.flask_model)` the bug doesn't trigger, but it does if I change it to `@api.doc(model=api.model('FooBar', {}))`.

This seems to only affect the documentation.

This sounds like the same issue as #13.

I'm using Python 3.6.3, Flask 0.12.2 and flask-restplus 0.10.1.

**Comment by joshfriend** [comment]
this is not flask-restplus
