### ISSUE TITLE
type is a dict or list how to set the type = ??

### ISSUE THREAD

**Issue by zhangkaka** [flask-restful/flask-restful#728]
def post(self):
        parser = reqparse.RequestParser()
        parser.add_argument('name', type=str, help='name cannot be blank',
                        required=True)
        parser.add_argument('status', type=str, help='status cannot be blank',
                        required=True)
        parser.add_argument('ip', type=str, help='ip cannot be blank',
                        required=True)
        parser.add_argument('time_stamp', type=str, help='time_stamp cannot be blank')
        parser.add_argument('port', type=int, help='port cannot be blank')
        parser.add_argument('proc_name', type=str, help='proc_name cannot be blank')
        parser.add_argument('grains', type=str, help='grains cannot be blank')

        args = parser.parse_args(strict=True)
        print args
        
      if the filed is a python dictionary,how can set the type?
      for example grains = {'os': 'Linux'} 
 parser.add_argument('grains', type=dict, help='grains cannot be blank') ????

**Comment by joshfriend** [comment]
flask-restful doesnt do nested fields, you will need to come up with your own parser for that type, but I would reccomend `webargs` instead
