### ISSUE TITLE
No module named config.py

### ISSUE THREAD

**Issue by MauroCE** [flask-restful/flask-restful#732]
I just created a new environment from command line by using the  following:
`conda create -p my_env python=3.5`
Then I activated it
`activate %cd%\my_env`
And then I installed some packages using the anaconda cloud instructions:
`conda install -c anaconda numpy`                  (https://anaconda.org/anaconda/numpy)
`conda install -c anaconda pandas `                 (https://anaconda.org/anaconda/pandas)
`conda install -c conda-forge time`                   (https://anaconda.org/conda-forge/time)
`conda install -c anaconda flask`                       (https://anaconda.org/anaconda/flask)
`conda install -c anaconda flask-wtf`                 (https://anaconda.org/anaconda/flask-wtf)
`conda install -c conda-forge cassandra-driver` (https://anaconda.org/conda-forge/cassandra-driver)

Then, I also installed flask-restful by following again the commands for anaconda
`conda instal -c conda-forge flask-restful`         (https://anaconda.org/conda-forge/flask-restful)

Everything seemed fine when I started importing modules after I wrote "python" to get the prompts.

`import numpy`
`import pandas`
`import time`
 However when I wrote `import flask_restful`, I get 

> No module named config

 as follows:

```
>>> import numpy
>>> import pandas
>>> import time
>>> import flask
>>> import flask_restful
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Me\Desktop\Myfolder\MySubfolder\learning_flask_env\lib\site-packages\flask_restful\__init__.py", line 21, in <module>
    import config
ImportError: No module named 'config'
```

**Comment by jklapuch** [comment]
It's probably a little too late, but could you tell me a name of your "MySubfolder" ? It may be a problem with module names.

**Comment by joshfriend** [comment]
there is no import of a module named `config` in flask-restful: https://github.com/flask-restful/flask-restful/blob/0.3.6/flask_restful/__init__.py#L21
