### ISSUE TITLE
Check for empty strings in reqparse

### ISSUE THREAD

**Issue by BrokeRU** [flask-restful/flask-restful#741]
Hi! How can I check if an argument is an empty string or not?

Example data:
```
{
    "name": "",
    logo:""
}
```

Example RequestParser:
```
field_parser = reqparse.RequestParser()
field_parser.add_argument('name', required=True, nullable=False)
field_parser.add_argument('logo')
```

The `name` argument is not None and it is in the request data. So how can I check string arguments for empty strings?

**Comment by joshfriend** [comment]
make a custom function that checks the string length and throws an exception if length is 0, then [use that as the argument's `type`](https://flask-restful.readthedocs.io/en/latest/api.html#reqparse.Argument)

```python
def non_empty_string(s):
    if not s:
        raise ValueError("Must not be empty string")
    return s

parser.add_argument('name', required=True, nullable=False, type=non_empty_string)
