### ISSUE TITLE
Marshall a list of single Strings

### ISSUE THREAD

**Issue by IntegersOfK** [flask-restful/flask-restful#742]
How can I model to respond with an array/list of strings?

I want to be able to do this:
```
my_model = api.model('list_of_strings',
    fields.String(description='metric name')
)
```

So I can reply:
```["string1","string2","string3"]```

There are lots of tools which require a list of simple objects without keys.

Am I forced to always use a key the traditional way?

```
search_request = api.model('search_request', {
    'target': fields.String()
})
```

Alternatively, if I return the list myself (without a model) is there some way to create ad-hoc documentation for this endpoint so the swagger definition can show that it returns a list of strings?

Thanks!

**Comment by joshfriend** [comment]
This is flask-restful, you are using flask-restplus

**Comment by IntegersOfK** [comment]
Embarrassing mistake, thanks.

**Comment by joshfriend** [comment]
Happens surprisingly often 😆
