### ISSUE TITLE
how to add argument by myself after decrypt the request paramters

### ISSUE THREAD

**Issue by HJaycee** [flask-restful/flask-restful#751]
for example:
`post data = {"data":"some AES encrypted string"}`

I want to decrypt the encrypted string to a dict and add the dict to ` reqparse.RequestParser().parse_args()`

**Comment by joshfriend** [comment]
See [the docs for the `type` parameter of `add_argument`](http://flask-restful.readthedocs.io/en/latest/api.html#reqparse.Argument).

```python
def encrypted_string(s):
    // do your decryption here
    return decrypted_string

parser.add_argument('data', type=encrypted_string)
```
