### ISSUE TITLE
Reqeust Parser not parsing a list of dicts 

### ISSUE THREAD

**Issue by ravitejachebrolu** [flask-restful/flask-restful#754]
Example:
 { "Datalist": [{  "Value": 0, "Daily": 0, "Date": "5/9/2018 2:32:03 PM", "Sample": 0, "Floor": 120},
                      {  "Value": 0, "Daily": 0, "Date": "5/9/2018 2:32:03 PM", "Sample": 0, "Floor": 120}]}

self.reqparse.add_argument('Datalist', type=list, required=True, location='json') 

In version 0.3.5 
returned the data as list of dict (expected)

In version 0.3.6
returns a list of key names as below
['Value','Daily','Date','Sample','Floor']

**Comment by joshfriend** [comment]
reqparse does not handle nested data, you should use something else instead, like [Marshmallow](https://pypi.org/project/marshmallow/).

**Comment by leonharetd** [comment]
i can use this 
Example:
{ "Datalist": [{ "Value": 0, "Daily": 0, "Date": "5/9/2018 2:32:03 PM", "Sample": 0, "Floor": 120},
self.reqparse.add_argument('Datalist', type=dict, required=True, location='json', actions='append')
