### ISSUE TITLE
carousel with arg parsing

### ISSUE THREAD

**Issue by kaldown** [flask-restful/flask-restful#757]
What is the proper way to retrieve args from get method?

1. https://flask-restful.readthedocs.io/en/latest/quickstart.html#resourceful-routing
2. RequestParsing
3. Marshmallow
4. Decorator 

Whole doc is trying to mislead

**Comment by liuzheng1990** [comment]
> What is the proper way to retrieve args from get method?
> 
> 1. https://flask-restful.readthedocs.io/en/latest/quickstart.html#resourceful-routing
> 2. RequestParsing
> 3. Marshmallow
> 4. Decorator
> 
> Whole doc is trying to mislead

I guess it depends on what kind of args you want to retrieve. If you want URL path parameters, then 1. If you want URL args (e.g. `?module=flaskrestful`), then 2 and 3. From the doc, it seems `reqparser` is going to be deprecated, but I'm not sure about the progress. 3. Marshmallow and `flask.request` is definitely more reliable, but I agree that the doc should give more details regarding this point. Currently it's still about `reqparser`, although it's going to be deprecated.
