### ISSUE TITLE
[ReqParse] How to validate Json params in this format,i don't know how to say in English

### ISSUE THREAD

**Issue by Tangyiming** [flask-restful/flask-restful#761]
Hi,i'm new to flask/flask-restful. Could anybody help me 😢 

How can I validate every param include subA and subB ❓ 

Thank you for your answering 😄 

![_20180625163608](https://user-images.githubusercontent.com/18328731/41839940-184d0aaa-7897-11e8-8252-1224d66088cf.png)
![_20180625163636](https://user-images.githubusercontent.com/18328731/41839941-18ac230a-7897-11e8-8b26-b09a1d6d18f7.png)

**Comment by joshfriend** [comment]
Use [marshmallow](https://marshmallow.readthedocs.io/en/latest/)
