### ISSUE TITLE
when i try to run a sample api iam getting the following error

### ISSUE THREAD

**Issue by kodati9** [flask-restful/flask-restful#765]
Traceback (most recent call last):
  File "/Users/padma/PycharmProjects/untitled3/untitled3.py", line 2, in <module>
    from flask_restful import Api, Resource, reqparse
ImportError: No module named flask_restful

**Comment by joshfriend** [comment]
You have to install the package to be able to use it.

https://www.jetbrains.com/help/pycharm/creating-and-running-your-first-python-project.html

**Comment by kodati9** [comment]
When I try to install IAM.getting the error...
