### ISSUE TITLE
is there any plan for release 0.3.7?

### ISSUE THREAD

**Issue by rc-alexg** [flask-restful/flask-restful#776]
Specifically I would like to get the fixes related to `reqparser` like on this [merged PR](https://github.com/flask-restful/flask-restful/pull/705) without having to rely on the specific fixed commit.

**Comment by labeneator** [comment]
It has just hit pypi (commit  b47780a)! There will be much rejoicing today

**Comment by joshfriend** [comment]
Sorry for the long delay, I don't get much opportunity to work on this anymore

**Comment by labeneator** [comment]
@joshfriend any way we can help? Some of us are keen users of flask-restful
