### ISSUE TITLE
What is the best way to expose and endpoint for checking the health of the service?

### ISSUE THREAD

**Issue by viiicky** [flask-restful/flask-restful#777]
flask-restful looks cool. I was wondering if there is any "configuration" where I can set an endpoint that can be pinged to check the status of the service, i.e. whether the service is up and running or not, something like `/ping` or `/ready`.

I "feel" a little odd to create a new resource just for one single endpoint that will do nothing but always return constant `200`. Didn't find any such settings in the doc.

Will it be good to define a configuration which allows to assign any string, say `ready` to an implicit endpoint which does nothing but just returns `200`, of course if the service is up. The same can then be used in a kubernetes deployment file for the field:
```
readinessProbe:
          httpGet:
            path: /ready
            port: 5687
```

**Comment by joshfriend** [comment]
There is no such feature currently available, and also no plans to add one. You'll have to add it in your app as you've described.

**Comment by viiicky** [comment]
ok, for this single resource I decided to add it directly though `@app.route`:
```
# /ready call for health check
@app.route('/ready', methods=['GET'])
def index():
    return jsonify({"message": "service is ready!"})
```
Thanks anyway.
