### ISSUE TITLE
SwaggerUI is not at all working with the newer version

### ISSUE THREAD

**Issue by dineshkumarj86** [flask-restful/flask-restful#781]
When i am using flask-restplus==0.12.1, the swagger ui is breaking as shown below

![image](https://user-images.githubusercontent.com/11755470/46581447-9627f780-ca56-11e8-850d-0f755b14eaff.png)

But, when i am using flask_restplus==0.9.2, the swagger ui is working fine.

![image](https://user-images.githubusercontent.com/11755470/46581145-96bd8f80-ca50-11e8-9c9f-28197a949f10.png)

Can anyone please suggest, what is going wrong here

**Comment by dineshkumarj86** [comment]
Not an issue.. its due to swagger ui update. So closing it

**Comment by joshfriend** [comment]
this is flask-restful, _not flask-restplus_
