### ISSUE TITLE
How to get a different error code when using add_resource.

### ISSUE THREAD

**Issue by rohit-conn** [flask-restful/flask-restful#806]
Currently I have simple app with no database connectivity.
`api.add_resource(<someClass>,'/<path>/<int:num>')`

Here by default if I pass a string for the num value I get a 404.
How do I change this behavior to get my own custom error code.

**Comment by joshfriend** [comment]
You could make the parameter a string, check inside your view method if it is a valid int, and if it is not, throw a non 404 error of your choosing
