### ISSUE TITLE
request parser action='append' not support list of dict

### ISSUE THREAD

**Issue by heyhpython** [flask-restful/flask-restful#807]
when I want to post this data to the server
{
	"files":{"oid":"test1", "file_type":1, "uri":"././"},
	"files":{"oid":"test2", "file_type":2, "uri":".1/.1/"}
}
my parser is :
    parser = RequestParser()
    parser.add_argument('files', type=dict, action='append', help='', location='json', required=True)
and I only get 
{'files': [{'oid': 'test2', 'file_type': 2, 'uri': '.1/.1/'}]}

so is there any way to solve this?

**Comment by joshfriend** [comment]
Use [marshmallow](https://marshmallow.readthedocs.io/en/3.0/)
