### ISSUE TITLE
Complex get parsing

### ISSUE THREAD

**Issue by rohit-conn** [flask-restful/flask-restful#808]
I have an endpoint
`/search?name={config_name}&data.{key}={value}`
Here data is a json object with multiple key value pairs.
I want to use add_argument to parse `data.{key}`. Is it possible via regex in parser.add_argument.
Or is there any other work around for this.

**Comment by joshfriend** [comment]
This is not supported, you'll have to look elsewhere for something to parse that, or write it yourself.
