### ISSUE TITLE
reqparse can't pass empty list as a param

### ISSUE THREAD

**Issue by yejialin** [flask-restful/flask-restful#818]
for example, i have code like this.
```
rp = reqparse.RequestParser()
rp.add_argument("books", type=str, location="json", action="append")
```
if i pass body  **{"books": []}**  in request,
i got parsed args  **{"books": None}**

then i read the source code in flask_restful reqparse.py
```
Class Argument(object):
    ......
    def parse(self, request, bundle_errors=False):
        ....
        ....
        if not results and self.required:
            if isinstance(self.location, six.string_types):
                error_msg = u"Missing required parameter in {0}".format(
                    _friendly_location.get(self.location, self.location)
                )
            else:
                friendly_locations = [_friendly_location.get(loc, loc)
                                      for loc in self.location]
                error_msg = u"Missing required parameter in {0}".format(
                    ' or '.join(friendly_locations)
                )
            if current_app.config.get("BUNDLE_ERRORS", False) or bundle_errors:
                return self.handle_validation_error(ValueError(error_msg), bundle_errors)
            self.handle_validation_error(ValueError(error_msg), bundle_errors)

        if not results:
            if callable(self.default):
                return self.default(), _not_found
            else:
                return self.default, _not_found

        if self.action == 'append':
            return results, _found

```
i think if i pass empty list, it should will reach  if self.action == 'append' 
but i will get into
 ```
        if not results:
            if callable(self.default):
                return self.default(), _not_found
            else:
                return self.default, _not_found
```
and return None, _not_found(False)
i think maybe the if condition maybe is if result is not None? is this a bug?

thanks

**Comment by billyrrr** [comment]
It looks like that the if conditions should be “if result is None” instead, but it might take a long time to fix this issue as there are other effects for switching the if statement. Maybe for now you want to add a keyword argument `default=list` to get your code working.

**Comment by yejialin** [comment]
`default=list` is not work for me, because if request not pass this key, and i also will get `key: []`,
but in my code the value `[]` and `None` means different.

**Comment by billyrrr** [comment]
I see that you need a way to get different returns for when the request does not contain key (which expects {“books”: None} and when the request contains key but has empty lost as value (which expects {“books”: []} ). I think that flask-RESTful can’t do that for now, and it maybe a bug since in the second case, the key “books” is found, but we see not_found in the return value. Probably we need an else statement for the `if name in source` and fix other places too. Let me do some testing over the weekend and post more details.

**Comment by yejialin** [comment]
Wait for your response  (｡•̀ᴗ-)

**Comment by joshfriend** [comment]
You should define a custom argument `type` or use a different tool like Marshmallow

**Comment by IterableTrucks** [comment]
Be aware that `location` must be string (('json','values') by default) and `append` must not be 'append', then a custom `type` will work.
