### ISSUE TITLE
Add option to sort `fields.List` when presented with a set

### ISSUE THREAD

**Issue by asottile** [flask-restful/flask-restful#822]
Currently the code produces the following:

https://github.com/flask-restful/flask-restful/blob/f6921bbcc3a392cd92a1381357b5efa069cc55ea/flask_restful/fields.py#L181-L183

which has undefined ordering

----

Proposal:

- introduce a `sort` keyword-only argument to `fields.List`, defaulting to `False`
- (note, it must default to `False` even for sets as you could potentially be marshalling unsortable data)

----

Workaround

```python
class SortedList(fields.List):
    def format(self, value):
        return super(SortedList, self).format(sorted(value))
```

**Comment by joshfriend** [comment]
This is a pretty niche use case that is better supported by the custom solution you've come up with.
