### ISSUE TITLE
Double HTTP request

### ISSUE THREAD

**Issue by gabrielgambarra** [flask-restful/flask-restful#824]
I got a problem with my API. When I run the server and make some request, I notice it makes a double HTTP request: the first request is always 'OPTIONS' and then comes the request I want (POST or GET).

Here an example of what console shows me when I make a login:

`127.0.0.1 - - [02/Jul/2019 10:12:18] "OPTIONS /auth HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2019 10:12:18] "OPTIONS /auth HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2019 10:12:18] "POST /auth HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2019 10:12:18] "POST /auth HTTP/1.1" 200 -`

More informations: I'm using Angular 7.

**Comment by joshfriend** [comment]
This is expected, read up on what [CORS](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) is/does
