### ISSUE TITLE
Best way to add custom headers ?

### ISSUE THREAD

**Issue by lra** [flask-restful/flask-restful#84]
Hi,

I looked at the source code and am wondering what is the suggested way to add custom headers to the API responses.

Thanks for any pointer.

**Comment by linkyndy** [comment]
Why not add the custom headers to your resource's endpoint return method?

```python
class User(Resource):
    def get(self):
        # Some code
        return {'id': 1, 'name': 'John Doe'}, 200, {'X-My-Custom-Header': 'Custom Value'}
```

**Comment by fronbasal** [comment]
Any update on @linkyndy's suggestion?
