### ISSUE TITLE
render_template only returns a string

### ISSUE THREAD

**Issue by joegasewicz** [flask-restful/flask-restful#841]
I tried to return  Flask's `render_template` but it only returns a plain string. 
Would it be possible to return the expected HTML content as this is the expected outcome from a Flask application, it could help dev's new to the Flask API / Flask-Restful API...? Or perhaps we could log a warning to the console to  update `representations` ..?

**Comment by joshfriend** [comment]
This library isn't designed for returning HTML pages, you will want to use plain old flask views for that

**Comment by joegasewicz** [comment]
Hey @joshfriend that's not entirely true, you can actually use Flask-Restful like this:
```
class Home(Resource):

    def get(self):
        res = make_response(render_template("index.html"), 200)
        return res
```

Just an idea, sorry if it was a far out pitch, was fun to implment anyway , lol thanks.
