### ISSUE TITLE
reqparse: Add method to add multiple arguments

### ISSUE THREAD

**Issue by alonme** [flask-restful/flask-restful#845]
Currently the `add_argument` method can accept only one argument.

I have a use case where different endpoints use the same arguments, so i created `Argument` objects and i want to reuse them.

Adding an 'add_arguments' method would simplify this, as i would be able to add my many arguments using one function call.

Will happily implement.

**Comment by joshfriend** [comment]
Everyone should switch to Marshmallow and webargs for request parsing. They are better than reqparse and are also actively maintained.

**Comment by alonme** [comment]
@joshfriend - maybe its worth to write about these in the documentation.
