### ISSUE TITLE
[Suggestion] : Replace json with simplejson for Decimal serializing

### ISSUE THREAD

**Issue by gwasserfall** [flask-restful/flask-restful#849]
When serializing a Decimal object obtained from a mysql query, the following exception is thrown
```
TypeError: Object of type Decimal is not JSON serializable
```
Replacing json with simplejson in **flask_restful/representations/json.py**:4 fixes the issue. I haven't found anyone else with the same issue so may not be very important. And also requires another dependancy

**Comment by erebrus** [comment]
I don't get it. I see the issue was marked as completed, but looking at the code, the change isn't there. The default json is still used and so DECIMAL can't be serialised.
