### ISSUE TITLE
importing the ABCs deprecated

### ISSUE THREAD

**Issue by gdoumenc** [flask-restful/flask-restful#851]
=============================== warnings summary ===============================
/home/studiogdo/.local/share/virtualenvs/coworks-C8kiIu6_/lib/python3.7/site-packages/flask_restful/__init__.py:17
  /home/studiogdo/.local/share/virtualenvs/coworks-C8kiIu6_/lib/python3.7/site-packages/flask_restful/__init__.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by joshfriend** [comment]
#835
