### ISSUE TITLE
No routes registered for resources

### ISSUE THREAD

**Issue by zgoda** [flask-restful/flask-restful#853]
Flask-RESTFul does not register routes for resources, resulting in 404 on any resource path.

https://github.com/zgoda/issues/tree/master/flask-restful/no-routes-registered

python3.8 on linux x64

```shell
$ pip list
Package       Version Location                                                      
------------- ------- --------------------------------------------------------------
aniso8601     8.0.0   
Click         7.0     
Flask         1.1.1   
Flask-RESTful 0.3.7   
itsdangerous  1.1.0   
Jinja2        2.10.3  
MarkupSafe    1.1.1   
pip           19.3.1  
pkg-resources 0.0.0   
pony          0.7.11  
python-dotenv 0.10.3  
pytz          2019.3  
setuptools    39.0.1  
six           1.13.0  
todos         1.0.0   /home/jarek/work/issues/flask-restful/no-routes-registered/src
Werkzeug      0.16.0  
wheel         0.33.6
```

The code registers resource under path `/todos` and then:

```shell
$ frt routes
Endpoint  Methods  Rule
--------  -------  -----------------------
index     GET      /
static    GET      /static/<path:filename>
```

Am I doing anything wrong? The exact same application structure (factory, resources, models, extension registration, etc) works fine with Flask-RESTPlus, fails with Flask-RESTFul.

**Comment by zgoda** [comment]
Okay, found the reason - resource paths have to be registered **before** extension is initialized. I'm not sure this is a bug or feature.

**Comment by joshfriend** [comment]
If you are using blueprints it is expected that routes added after calling `init_app` to register the blueprint will not be registered: https://github.com/pallets/flask/blob/38eb5d3b49d628785a470e2e773fc5ac82e3c8e4/src/flask/blueprints.py#L206-L208

otherwise, without knowing more about how you have your app set up, i dont think i can tell you what the difference in behavior between this and flask-restplus is.

**Comment by zgoda** [comment]
I linked the code that exhibits this behaviour. Extension is bound to application, not to blueprint. Having 2nd look at the docs I see everywhere that resources are registered before initialization so this may well be feature. Bit counterintuitive but OK.
