### ISSUE TITLE
How can I marshal a comma-separated DB field into a fields.List?

### ISSUE THREAD

**Issue by caffeinatedMike** [flask-restful/flask-restful#857]
I have a field in an inherited database, let's call it `tags`, that stores comma-separated values. I want to marshal this field into a list by splitting the value by a comma. 

So, if the DB field holds the value:  
```a,b,c,d,e```  
I want to marshal that value into:  
```python3  
{
    "tags": [
        "a",
        "b",
        "c",
        "d",
        "e"
    ]
}
```

How could I accomplish this?

**Comment by joshfriend** [comment]
Make a [custom field type](https://flask-restful.readthedocs.io/en/latest/fields.html#custom-fields-multiple-values)
