### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by smoolya17** [flask-restful/flask-restful#867]
I am new to flask-restful & trying to post a request

    def post(self):
        req_json = request.get_json()
        doc_id = req_json['docid']

My post data is as:

`curl http://localhost:5000/ -d "{    "labels": {        "predictSensorData": "XPo",        "predictFailure": "Camera_Output"    },    "docid": "<key>"}" -X POST`

I get the following error:

```
 doc_id = req_json['docid']
TypeError: 'NoneType' object is not subscriptable
```
How do I solve this error?

**Comment by joshfriend** [comment]
You did not specify that your post body data from cURL was json, so `request.get_json()` does not return anything

https://stackoverflow.com/a/7173011/1255482
