### ISSUE TITLE
How can I get the Token from Headers

### ISSUE THREAD

**Issue by WRAllen** [flask-restful/flask-restful#872]
as the title, I want to get the Token which is in the request headers。
and I know
```python
# this can get Token from RequestParser
parser = reqparse.RequestParser()
parser.add_argument("Token")
```
but how to get Token from Headers?

**Comment by joshfriend** [comment]
please [read the docs about this](https://flask-restful.readthedocs.io/en/latest/reqparse.html#argument-locations)
