### ISSUE TITLE
Question wrt maintenance?

### ISSUE THREAD

**Issue by curlup** [flask-restful/flask-restful#882]
We like your software and are considering using it for our open-source system, thank you for writing it!

Is this software thought to be actively maintained or something? Is it that there's only one person behind it? Is michiganlabs involved in any way? 

Any insights will be helpful.
Thanks

**Comment by joshfriend** [comment]
> Is this software thought to be actively maintained or something?

No, not really. I merge bugfixes or really simple PRs occasionally so people don't need to use forks for their projects. I also answer issues when I have time.

> Is it that there's only one person behind it?

There are 3 people with commit access, I am the only one who is really active in responding to issues or merging PRs.

> Is michiganlabs involved in any way?

I work for MichiganLabs, we used to use flask-restful lots for projects, but haven't recently. We've found better solutions for the things that Flask-RESTful used to provide us.

Please see #883 for the list of alternatives that I recommend.
