### ISSUE TITLE
New GitHub release?

### ISSUE THREAD

**Issue by nileshpatra** [flask-restful/flask-restful#890]
Hi,
It's been 6 years without any release. It'd be great if there can be a new upstream release now.
I need the version thingy for a project.
Thanks!

**Comment by nileshpatra** [comment]
@dougblack could you please do the needful? :)

**Comment by ajaissle** [comment]
Seems like a "GitHub releases" vs "git tags" situation:

Latest GitHub release: 0.2.12 (4 Mar 2014)
Latest git tag: 0.3.9 (17 May 2020)

Git tags act as official releases, but are not in sync with the "GitHub releases", thus not presented right in the WebUI.

**Comment by joshfriend** [comment]
the git tags show up on the releases list, idk what everyone is talking about here https://github.com/flask-restful/flask-restful/releases

**Comment by rafrafek** [comment]
This is what people see, the project looks dead at first sight. Maybe removing Releases would be better than keeping them?

<img width="240" alt="image" src="https://user-images.githubusercontent.com/23004737/195042167-a97598b1-f1a8-4e67-bae4-9036e8ab7e9f.png">
