### ISSUE TITLE
How flask restful specify the ssl_context ?

### ISSUE THREAD

**Issue by max-yue** [flask-restful/flask-restful#891]
from flask import Flask    
app = Flask(__name__)    
app.run('0.0.0.0', debug=True, port=8100, ssl_context=('your_path/XXXX.pem', 'your_path/XXXX.key')) 

How flask restful specify the ssl_context ?

**Comment by joshfriend** [comment]
looks like you already have it figured out. this is just a framework that adds view functions to flask apps
