### ISSUE TITLE
这个文档有中文的吗，求一份中文教程，视频也可以

### ISSUE THREAD

**Issue by c834482351** [flask-restful/flask-restful#895]

**Comment by eppen** [comment]
https://wizardforcel.gitbooks.io/flask-extension-docs/content/flask-restful.html

**Comment by c834482351** [comment]
非常感谢！

**Comment by c834482351** [comment]
> https://wizardforcel.gitbooks.io/flask-extension-docs/content/flask-restful.html

非常感谢!
