### ISSUE TITLE
Mask for marshal_with output

### ISSUE THREAD

**Issue by macfire** [flask-restful/flask-restful#908]
Does flask-restful currently have the ability to mask output based on incoming request?

For example, if I have a model `Car` with fields `make`, `model`, `color`, `engine_specs`.
* Resource `/api/car/<id>/summary` returns `make` and `model`
* Resource `/api/car/<id>` returns all attributes

Instead of having 2 separate Resources for same Model, I'd like to use one Resource, but have the incoming request specify which fields to return.

I found [Flask-RESTX](https://flask-restx.readthedocs.io/en/latest/mask.html) that uses a custom header to specify which fields to return. 
Is it currently possible to accomplish similar with Flask Restful?

**Comment by joshfriend** [comment]
That does not currently exist, sorry

**Comment by macfire** [comment]
Thanks for reply.

I resolved by adding a custom header in the Javascript request options, and defining schema options on server.

__Javascript:__
```javascript
let request_object = new Request(url, {
            method: 'PATCH',
            body: JSON.stringify(_data),
            headers: new Headers({
                'Content-Type': 'application/json', 
                'X-CSRFToken': csrf_token,
                'X-Mask': _mask
            })
        });
```


__Python:__    
_(using marshmallow and webargs for validation and parsing)_
```python

car_full_schema = CarSchema()
car_summary_schema = CarSchema(only('make', 'model'))

def patch(self, user_id):

    mask = request.headers["X-Mask"]

    car_schema = None
    if mask == 'summary':
         car_schema = car_summary_schema
    else:
         car_schema = car_full_schema  # default

    args = parser.parse(car_schema, request)

    # .... rest of process to validate and save #

```
