### ISSUE TITLE
supported vs end of life (eol) versions

### ISSUE THREAD

**Issue by aaronk-cb** [flask-restful/flask-restful#909]
What versions of flask-restful are supported vs end of life (EOL)?

**Comment by joshfriend** [comment]
LIke most free software, you are responsible for supporting the software you use, or relying on the kindness of strangers 😃.

As stated in [the license](https://github.com/flask-restful/flask-restful/blob/master/LICENSE), no warranty is given or implied.

**Comment by aaronk-cb** [comment]
Thanks Josh.  I take that to mean that flask-restful is effectively completely unsupported (unless adopted for support by a specific consumer), and cannot be expected to investigate whether security vulnerabilities affect the software or are fixed in the software.
