### ISSUE TITLE
Bump version to 0.3.9

### ISSUE THREAD

**Issue by rena2damas** [flask-restful/flask-restful#916]
https://github.com/flask-restful/flask-restful/blob/fc9b34c39472284a57c50d94fec5b51fe8d71e14/flask_restful/__version__.py#L3

**Comment by LefterisJP** [comment]
Is it planned to bump the version. It's the only thing needed to make this work with the new flask.

**Comment by rena2damas** [comment]
@joshfriend any idea on when to pick this up ? Need help on that ?

**Comment by joshfriend** [comment]
https://pypi.org/project/Flask-RESTful/0.3.9/

**Comment by LefterisJP** [comment]
Oh wow that was fast @joshfriend thank you so much :pray: 
We can delete the ugly commit pinning on our side :sweat_smile:
