### ISSUE TITLE
<Define Custom Error Messages > Not working！！！

### ISSUE THREAD

**Issue by Deep-sea-boy** [flask-restful/flask-restful#918]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/37582640/120885785-46da6080-c61d-11eb-83de-14abe49bdc9f.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/37582640/120885852-a0db2600-c61d-11eb-8705-cdf5c0002020.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/37582640/120885793-548fe600-c61d-11eb-8897-c352200b4588.png">

Why always get《"message": "Internal Server Error"》？？ I want my Custom error。。

**Comment by 13528080556** [comment]
You need to change the key in the errors to the corresponding exception type name "ZeroDivisionError".
