### ISSUE TITLE
Are there Decorators to name a Method in  Resource class?  

### ISSUE THREAD

**Issue by rosjat** [flask-restful/flask-restful#920]
I hope the title gets the thing i want to do here.

lets say i define a custom Resorce like so 

```
class ApiProduct(Resource):

    def get(self, id):
        product = ProductRepository.get_product_by_id(id)
        return jsonify(product)

    def undo_delete(self, id):
        ProductRepository.undo_delete_product(id)
        product =ProductRepository.get_product_by_id(id)
        if(product.Deleted == False):
            return '', 204
        return 404
```

and what i am looking for is more or less a way to make undo_delete available with a other name to the Request. So is there a existing decorator that does that, so undo_delete becomes a undodelete for the supported request methods?

**Comment by joshfriend** [comment]
`Resource` is a fancy wrapper for `MethodView` from Flask, so a resource is just a collection of methods that respond to HTTP verbs. You can't map the verbs to methods in any way other than naming the method `post` or `get`, etc. 

Flask 2.x can sortof do this now though:

```python
@app.delete('/foo')
def delete_foo():
    pass
```

**Comment by rosjat** [comment]
ok thanks,

i can live with that, and having  methods named like some_thing is ok for me 

cheers

Markus
