### ISSUE TITLE
Memory issue or I am dumb

### ISSUE THREAD

**Issue by collinsmarra** [flask-restful/flask-restful#923]
I was looking into flask-restful and blueprints. So I wanted json output as in flask-restful documentation;

```
from flask import Flask, Blueprint
from flask_restful import Api

app = Flask(__name__)
api_bp = Blueprint("api", __name__)
api = Api(api_bp)

@api.representation("application/json")
def out_json(data, code, headers=None):
    resp = api.make_response(json.dumps(data), code)
    resp.headers.extend(headers or {})
    return resp

@api.blueprint.route("/")
def home():
    message = "hello world"
    return out_json({"message":message}, 200)

app.register_blueprint(api_bp)

if __name__ == "__main__":
   app.run(debug=True)
```

when you run the above code and make a request to the server ie
`curl -sk "http://127.0.0.1:5000/" ` it consumes all the memory and you will not get the response from the server. I also observed that insane memory consumption continues even after you have cancelled the request.
The server does not acknowledge that it has received the request however.

**Comment by joshfriend** [comment]
You did recursion in an infinite loop. `api.make_response()` calls the function that you registered with `@api.representation`, which is `out_json()`. `out_json()` calls `api.make_response()` and you should see now why this is a problem!

Either stick with the default json response formatter, or follow [the docs](https://flask-restful.readthedocs.io/en/latest/extending.html#response-formats) on how to make one properly.
