### ISSUE TITLE
curl command throws an error

### ISSUE THREAD

**Issue by earik87** [flask-restful/flask-restful#929]
First of all, thanks to the creators of this flask-restful documentation! It is extremely useful.

The command `curl http://localhost:5000/todo1 -d "data=Remember the milk" -X PUT ` will throw the error below for the first time users of `curl` commands in windows. 

```
Invoke-WebRequest : A positional parameter cannot be found that accepts argument 'data=Remember the milk'.
At line:1 char:1
+ curl http://localhost:5000/todo1 -d "data=Remember the milk" -X PUT
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

I spent an hour for searching the solution. Following command fixes the issue. 
`Remove-item alias:curl`

The explanation is [here.](https://stackoverflow.com/questions/25044010/running-curl-on-64-bit-windows/25045154#25045154
)

We should somehow give a hyper-link to the stackoverflow for making the first-time users life easier. What do you think?

**Comment by ukos-git** [comment]
This discussion belongs to the PS community: https://github.com/PowerShell/PowerShell/pull/1901 and https://github.com/PowerShell/PowerShell-RFC/issues/16
