### ISSUE TITLE
Swagger creates every http method for endpoints.

### ISSUE THREAD

**Issue by gupta-shrinath** [flask-restful/flask-restful#934]
I have a resource 'Students' which should have a 
- GET method and url for that will have a path variable email
- PATCH method and url for that will have a path variable id

App.py
`api.add_resource(Students,api_version + '/student/<string:email>','/student/<string:id>')`

Students Resource
```
class Students(MethodResource,Resource):

    @doc(description='Get student information',tags=['Student'])
    @marshal_with(StudentResponseSchema,code='200',description='Returns active student json') 
    def get(self,email,id=None):
		..
 
    @doc(description='Update student nick name and avatar url provided in request body',tags=['Student']) 
    @use_kwargs(UpdateStudentClassAvatarRequestSchema,location=('json'))
    @marshal_with(ResponseSchema,code='200')
    def patch(self,id,avatar_url,nick_name,email=None):
		..


```
My issue is Swagger is displaying both get and patch method for every url
![Screenshot from 2022-03-12 08-48-52](https://user-images.githubusercontent.com/42563130/158001860-4a2b1742-d6e3-4dc6-a46d-23018e2520af.png)
Please ignore PATCH /v1/student/last_login/{id}

**Comment by joshfriend** [comment]
Flask-RESTful provides no swagger integration, so this issue is more likely related to whatever package you used to add that. Please file your issue there.

**Comment by gupta-shrinath** [comment]
My bad.
