### ISSUE TITLE
Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

### ISSUE THREAD

**Issue by bikashsaud** [flask-restful/flask-restful#953]
When I POST or PUT request, it can not parse the form data and show error like:
```
{'message': "Did not attempt to load JSON data because the request Content-Type was not 'application/json'."}
```
But when I use dependencies ```   
Flask==1.1.2
Flask-RESTful==0.3.8``` 
It works fine.

**Comment by npbcts** [comment]
this error bother me for long time, I use dependencies Flask==2.2.2 Flask-restful==0.3.9

**Comment by Nicoco220983** [comment]
I think that the issue comes from this commit in Werkzeug:
https://github.com/pallets/werkzeug/commit/bf4ede275335644102cd72c421c2b6976bc69883

This seems to be a new bug in flask-restful

**Comment by azzamsa** [comment]
Any solutions for this?

```
Flask = "2.2.2"
Flask-RESTful = "0.3.9"
```

**Comment by azzamsa** [comment]
I managed to solve the issue. I put the full explanation in [my StackOverflow answer](https://stackoverflow.com/a/74213679/6000005)

**Comment by loucadufault** [comment]
You can use [`Request.get_json(force=True)`](https://flask.palletsprojects.com/en/2.2.x/api/?highlight=json#flask.Request.get_json).

**Comment by xinzhengzhangCHN** [comment]
parser.add_argument('icon', type=FileStorage, location='files')

all parser.add_argument() need the location='' 
Then the problem disapear, all things calm down to  normal again.
Clock. Clock. Clock,,,,

**Comment by vacosti** [comment]
Hello guys!

@xinzhengzhangCHN , in my case, even adding the parameter location (in my use case, form) is not working:

```python
class Ideas(Resource):
    def __init__(self) -> None:
        self.parser = reqparse.RequestParser(bundle_errors=True)

        self.parser.add_argument(ARGS_NAMES.authorization, required=True, location='headers')
        self.parser.add_argument(ARGS_NAMES.idea_id, type=int, location='form')
        self.parser.add_argument(ARGS_NAMES.idea_name, type=str, location='form')
        self.parser.add_argument(ARGS_NAMES.amount_to_stake, type=float, location='form')
        self.parser.add_argument(ARGS_NAMES.idea_description, type=str, location='form')
        self.parser.add_argument(ARGS_NAMES.idea_color, type=str, location='form')
        self.parser.add_argument(ARGS_NAMES.image, type=FileStorage, location='files')

        self.args = self.parser.parse_args(strict=True)

        super().__init__()
```

I keep getting the following error as a response in Postman:

`"message": "Did not attempt to load JSON data because the request Content-Type was not 'application/json'."`

My Postman request:

![image](https://github.com/user-attachments/assets/5ee3d197-9edc-41a3-92ef-da03e3833421)

![image](https://github.com/user-attachments/assets/434a2b2b-bff1-4135-9e30-941dec7261ab)
Notice that the Content-Type is multipart/form-data.

Is anybody else having the issue?

Thanks in advance!

**Comment by vacosti** [comment]
Hi There! I've tried to debug the source code of `RequestParser` and found out that setting the `strict` parameter to `False` (or not changing the default, which is `False`) in `parse_args` solves the issue:

 ```python 
self.args = self.parser.parse_args(strict=False) #or:
self.args = self.parser.parse_args()
```

The downside is that now any parameter can be sent in the request, and even if such a parameter is not defined by the `RequestParser.add_argument(...)`, an error will not be thrown. 

If I have time I will debug it further and see if there is a proper solution.

**Comment by holysoles** [comment]
for anyone else who finds this issue, I'd suggest moving to[ flask-restx](https://github.com/python-restx/flask-restx?tab=readme-ov-file), they merged in a fix some time ago, is maintained, and its easy to migrate from this package.

**Comment by rovermask** [comment]
In my case removing "args = parser.parse_args(strict=True)" from app.py worked for me
