### ISSUE TITLE
Flask 2.3 Incompatibility: app.propagate_exceptions is depreciated

### ISSUE THREAD

**Issue by BrianHVB** [flask-restful/flask-restful#957]
Running Flask-Restful with Flask 2.2.x produces the warning: _DeprecationWarning: 'propagate_exceptions' is deprecated and will be removed in Flask 2.3._

The [Flask changelog](https://flask.palletsprojects.com/en/2.2.x/changes/) notes the deprecation and [associated commit](https://github.com/pallets/flask/issues/4716).

It looks like the property is only used in a single place

https://github.com/flask-restful/flask-restful/blob/fc9b34c39472284a57c50d94fec5b51fe8d71e14/flask_restful/__init__.py#L283

The fix is to reference `propagate_exceptions` as a config value instead, e.g.
```python
if not isinstance(e, HTTPException) and current_app.config.get('PROPAGATE_EXCEPTIONS', False)
```

**Comment by transreductionist** [comment]
Here is a pull request to fix Flak-RESTful code dependence on the Flask `propagate_exceptions`. When `propagate_exceptions` is deprecated Flask-RESTful will fail. The pull request chooses a sensible value when `app.config['PROPAGATE_EXCEPTIONS'] is None (default).

[Flask-RESTful will fail when Flask deprecates propagate_exceptions: Fix](https://github.com/flask-restful/flask-restful/pull/962)
