### ISSUE TITLE
Is flask-restful dead?

### ISSUE THREAD

**Issue by EpicRelations** [flask-restful/flask-restful#976]
Hi everyone,

the last release of flask-restful was in 2014. Is the project still appropriate for production environments? 

Thanks for your support in advance.

**Comment by joshfriend** [comment]
The last release was actually less than a year ago https://pypi.org/project/Flask-RESTful/0.3.10/

I do not spend much time at all maintaining this anymore, mostly just merging and releasing compatibility fixes with Flask/Werkzeug.

Over the years I was still using and updating flask-restful heavily, I ended up moving away from using it and developed a very lightweight API wrapper for each project that I used instead. Other projects provide better request parsing and response marshalling already, so just use those instead (ie Marshmallow)

**Comment by EpicRelations** [comment]
Thanks for your quick reply. I'll check Marshmallow. Best, Seb
